const makeEntry = ({
  id,
  word,
  usIpa,
  ukIpa = usIpa,
  importance = 3,
  topics,
  ko,
  zh,
  englishDefinition,
  noteEn,
  noteKo,
  noteZh,
  exampleEn,
  exampleKo,
  exampleZh,
  collocations = [],
}) => ({
  id,
  word,
  usIpa,
  ukIpa,
  importance,
  topics,
  meaning: { en: englishDefinition, ko, zh },
  note: { en: noteEn, ko: noteKo, zh: noteZh },
  collocations,
  examples: [
    {
      en: exampleEn,
      ko: exampleKo,
      zh: exampleZh,
    },
  ],
})

export const CELPIP_VOCABULARY_EXTRA = [
  makeEntry({
    id: 'agenda',
    word: 'agenda',
    usIpa: '/əˈdʒendə/',
    ukIpa: '/əˈdʒendə/',
    importance: 4,
    topics: ['work-school', 'community-civic'],
    ko: '안건; 의제',
    zh: '议程；议题',
    englishDefinition: 'a list of topics to be discussed in a meeting or event',
    noteEn: 'Common in workplace, class, and community-meeting listening tasks.',
    noteKo: '직장, 수업, 지역 회의 듣기에서 자주 나옵니다.',
    noteZh: '在职场、课堂和社区会议听力中经常出现。',
    exampleEn: 'The first item on the agenda is the parking policy update.',
    exampleKo: '의제의 첫 번째 항목은 주차 정책 업데이트입니다.',
    exampleZh: '议程的第一项是停车政策更新。',
    collocations: ['meeting agenda', 'agenda item', 'set the agenda'],
  }),
  makeEntry({
    id: 'allocate',
    word: 'allocate',
    usIpa: '/ˈæləˌkeɪt/',
    ukIpa: '/ˈæləkeɪt/',
    importance: 4,
    topics: ['work-school', 'shopping-banking'],
    ko: '배정하다; 할당하다',
    zh: '分配；拨给',
    englishDefinition: 'to officially give time, money, space, or resources for a purpose',
    noteEn: 'Useful for budgeting, staffing, and project planning questions.',
    noteKo: '예산, 인력, 프로젝트 계획 문제에서 유용합니다.',
    noteZh: '在预算、人力和项目规划题中很有用。',
    exampleEn: 'The school will allocate more funds to student support programs.',
    exampleKo: '학교는 학생 지원 프로그램에 더 많은 자금을 배정할 예정입니다.',
    exampleZh: '学校将为学生支持项目分配更多资金。',
    collocations: ['allocate funds', 'allocate time', 'allocate resources'],
  }),
  makeEntry({
    id: 'amend',
    word: 'amend',
    usIpa: '/əˈmend/',
    ukIpa: '/əˈmend/',
    importance: 3,
    topics: ['community-civic', 'work-school'],
    ko: '수정하다; 개정하다',
    zh: '修改；修订',
    englishDefinition: 'to change a document, rule, or plan in order to improve it',
    noteEn: 'Appears in policy, contract, and meeting-summary contexts.',
    noteKo: '정책, 계약, 회의 요약 문맥에서 보입니다.',
    noteZh: '会出现在政策、合同和会议摘要语境中。',
    exampleEn: 'The committee voted to amend the rule before approving it.',
    exampleKo: '위원회는 규정을 승인하기 전에 수정하기로 표결했습니다.',
    exampleZh: '委员会投票决定在批准前修改该规定。',
    collocations: ['amend a rule', 'amend a proposal', 'amend the policy'],
  }),
  makeEntry({
    id: 'approval',
    word: 'approval',
    usIpa: '/əˈpruːvəl/',
    ukIpa: '/əˈpruːvəl/',
    importance: 5,
    topics: ['housing-services', 'work-school', 'shopping-banking'],
    ko: '승인; 허가',
    zh: '批准；许可',
    englishDefinition: 'official permission to do something or use something',
    noteEn: 'One of the most common document and process words in CELPIP.',
    noteKo: 'CELPIP에서 가장 자주 나오는 서류·절차 단어 중 하나입니다.',
    noteZh: '这是 CELPIP 中最常见的文件和流程词之一。',
    exampleEn: 'Final approval may take up to five business days.',
    exampleKo: '최종 승인은 영업일 기준 최대 5일이 걸릴 수 있습니다.',
    exampleZh: '最终批准可能需要最多五个工作日。',
    collocations: ['receive approval', 'final approval', 'manager approval'],
  }),
  makeEntry({
    id: 'assistance',
    word: 'assistance',
    usIpa: '/əˈsɪstəns/',
    ukIpa: '/əˈsɪstəns/',
    importance: 4,
    topics: ['health-emergency', 'community-civic', 'travel-transit'],
    ko: '도움; 지원',
    zh: '帮助；援助',
    englishDefinition: 'help or support given to someone',
    noteEn: 'Often appears in service counters, accessibility, and emergency situations.',
    noteKo: '서비스 창구, 접근성, 응급 상황에서 자주 보입니다.',
    noteZh: '常出现在服务柜台、无障碍和紧急情况中。',
    exampleEn: 'Passengers who need assistance should speak to staff at the gate.',
    exampleKo: '도움이 필요한 승객은 게이트 직원에게 말씀하셔야 합니다.',
    exampleZh: '需要帮助的乘客应与登机口工作人员联系。',
    collocations: ['financial assistance', 'special assistance', 'request assistance'],
  }),
  makeEntry({
    id: 'assessment',
    word: 'assessment',
    usIpa: '/əˈsesmənt/',
    ukIpa: '/əˈsesmənt/',
    importance: 4,
    topics: ['work-school', 'health-emergency'],
    ko: '평가; 사정',
    zh: '评估；评定',
    englishDefinition: 'the act of judging a situation, skill, or need',
    noteEn: 'Useful in school grading and medical evaluation contexts.',
    noteKo: '학교 평가와 의료 사정 문맥에서 유용합니다.',
    noteZh: '在学校评分和医疗评估语境中很有用。',
    exampleEn: 'Students will receive the assessment results by email next week.',
    exampleKo: '학생들은 다음 주에 이메일로 평가 결과를 받게 됩니다.',
    exampleZh: '学生们将在下周通过电子邮件收到评估结果。',
    collocations: ['risk assessment', 'assessment results', 'initial assessment'],
  }),
  makeEntry({
    id: 'availability',
    word: 'availability',
    usIpa: '/əˌveɪləˈbɪləti/',
    ukIpa: '/əˌveɪləˈbɪləti/',
    importance: 5,
    topics: ['housing-services', 'travel-transit', 'work-school'],
    ko: '가능 여부; 이용 가능 상태',
    zh: '可用性；空余情况',
    englishDefinition: 'whether something is free, open, or ready to use',
    noteEn: 'This word often decides the correct option in booking and scheduling tasks.',
    noteKo: '예약과 일정 문제에서 정답을 가르는 핵심 단어입니다.',
    noteZh: '在预订和排期题里，这个词常常决定正确答案。',
    exampleEn: 'Please check room availability before submitting the request.',
    exampleKo: '요청서를 제출하기 전에 방 이용 가능 여부를 확인해 주세요.',
    exampleZh: '提交申请前请先确认房间是否有空。',
    collocations: ['check availability', 'limited availability', 'staff availability'],
  }),
  makeEntry({
    id: 'baggage',
    word: 'baggage',
    usIpa: '/ˈbæɡɪdʒ/',
    ukIpa: '/ˈbæɡɪdʒ/',
    importance: 4,
    topics: ['travel-transit'],
    ko: '수하물',
    zh: '行李',
    englishDefinition: 'bags and suitcases that travelers take with them',
    noteEn: 'Useful for airport, train, and bus announcements.',
    noteKo: '공항, 기차, 버스 안내 방송에서 유용합니다.',
    noteZh: '在机场、火车和巴士广播中很有用。',
    exampleEn: 'Oversized baggage must be checked at the special counter.',
    exampleKo: '규격 초과 수하물은 별도 카운터에서 부쳐야 합니다.',
    exampleZh: '超大行李必须在特别柜台托运。',
    collocations: ['checked baggage', 'baggage claim', 'carry-on baggage'],
  }),
  makeEntry({
    id: 'bank-statement',
    word: 'bank statement',
    usIpa: '/ˈbæŋk ˌsteɪtmənt/',
    ukIpa: '/ˈbæŋk ˌsteɪtmənt/',
    importance: 4,
    topics: ['shopping-banking', 'housing-services'],
    ko: '은행 거래 내역서',
    zh: '银行对账单',
    englishDefinition: 'an official record showing money moving in and out of a bank account',
    noteEn: 'Often appears in address verification, refunds, and payment disputes.',
    noteKo: '주소 확인, 환불, 결제 분쟁에서 자주 보입니다.',
    noteZh: '常见于地址核验、退款和付款纠纷情境中。',
    exampleEn: 'You may need a recent bank statement as proof of address.',
    exampleKo: '주소 증빙으로 최근 은행 거래 내역서가 필요할 수 있습니다.',
    exampleZh: '你可能需要最近的银行对账单作为地址证明。',
    collocations: ['monthly statement', 'recent bank statement', 'download a statement'],
  }),
  makeEntry({
    id: 'barcode',
    word: 'barcode',
    usIpa: '/ˈbɑːrˌkoʊd/',
    ukIpa: '/ˈbɑːˌkəʊd/',
    importance: 3,
    topics: ['shopping-banking', 'technology-communication'],
    ko: '바코드',
    zh: '条形码',
    englishDefinition: 'a printed set of lines used to identify a product electronically',
    noteEn: 'Useful in self-checkout, shipping, and receipt problems.',
    noteKo: '셀프 계산대, 배송, 영수증 문제에서 유용합니다.',
    noteZh: '在自助结账、配送和收据问题中很实用。',
    exampleEn: 'The cashier said the barcode would not scan properly.',
    exampleKo: '계산원은 바코드가 제대로 스캔되지 않는다고 말했습니다.',
    exampleZh: '收银员说条形码无法正确扫描。',
    collocations: ['scan the barcode', 'barcode label', 'damaged barcode'],
  }),
  makeEntry({
    id: 'billing',
    word: 'billing',
    usIpa: '/ˈbɪlɪŋ/',
    ukIpa: '/ˈbɪlɪŋ/',
    importance: 4,
    topics: ['shopping-banking', 'technology-communication'],
    ko: '청구; 요금 부과',
    zh: '计费；账单处理',
    englishDefinition: 'the process of charging a customer for a service or product',
    noteEn: 'Very common in phone, internet, and subscription disputes.',
    noteKo: '휴대폰, 인터넷, 구독 관련 분쟁에서 매우 자주 나옵니다.',
    noteZh: '在手机、网络和订阅纠纷中非常常见。',
    exampleEn: 'Please contact billing if you think you were charged twice.',
    exampleKo: '이중 청구된 것 같으면 청구 부서에 연락해 주세요.',
    exampleZh: '如果你觉得被重复收费，请联系计费部门。',
    collocations: ['billing cycle', 'billing department', 'billing issue'],
  }),
  makeEntry({
    id: 'booklet',
    word: 'booklet',
    usIpa: '/ˈbʊklət/',
    ukIpa: '/ˈbʊklət/',
    importance: 3,
    topics: ['work-school', 'community-civic'],
    ko: '소책자',
    zh: '小册子',
    englishDefinition: 'a small book with information or instructions',
    noteEn: 'Useful when directions are given through printed materials.',
    noteKo: '인쇄 자료로 안내가 주어질 때 유용한 단어입니다.',
    noteZh: '当指示通过纸质资料给出时很实用。',
    exampleEn: 'New students should read the orientation booklet carefully.',
    exampleKo: '신입생은 오리엔테이션 소책자를 주의 깊게 읽어야 합니다.',
    exampleZh: '新生应仔细阅读迎新小册子。',
    collocations: ['information booklet', 'course booklet', 'safety booklet'],
  }),
  makeEntry({
    id: 'broadband',
    word: 'broadband',
    usIpa: '/ˈbrɔːdˌbænd/',
    ukIpa: '/ˈbrɔːdbænd/',
    importance: 3,
    topics: ['technology-communication', 'housing-services'],
    ko: '광대역 인터넷; 초고속 인터넷',
    zh: '宽带网络',
    englishDefinition: 'high-speed internet service',
    noteEn: 'Appears in home service and technical support conversations.',
    noteKo: '가정용 서비스와 기술 지원 대화에서 자주 보입니다.',
    noteZh: '会出现在家庭服务和技术支持对话中。',
    exampleEn: 'The landlord said broadband installation is scheduled for Monday.',
    exampleKo: '집주인은 광대역 인터넷 설치가 월요일로 예정되어 있다고 했습니다.',
    exampleZh: '房东说宽带安装安排在周一。',
    collocations: ['broadband plan', 'broadband provider', 'broadband installation'],
  }),
  makeEntry({
    id: 'bulletin',
    word: 'bulletin',
    usIpa: '/ˈbʊlətɪn/',
    ukIpa: '/ˈbʊlətɪn/',
    importance: 3,
    topics: ['community-civic', 'news-opinion'],
    ko: '공지; 게시문',
    zh: '公告；简报',
    englishDefinition: 'an official short notice or public message',
    noteEn: 'Useful for campus and community noticeboard tasks.',
    noteKo: '학교·지역 공지 게시판 문제에서 유용합니다.',
    noteZh: '在校园和社区公告栏任务中很有用。',
    exampleEn: 'The weather bulletin warned residents about heavy rain overnight.',
    exampleKo: '기상 공지는 주민들에게 밤사이 폭우를 경고했습니다.',
    exampleZh: '天气简报提醒居民夜间会有大雨。',
    collocations: ['news bulletin', 'public bulletin', 'bulletin board'],
  }),
  makeEntry({
    id: 'campus',
    word: 'campus',
    usIpa: '/ˈkæmpəs/',
    ukIpa: '/ˈkæmpəs/',
    importance: 4,
    topics: ['work-school'],
    ko: '캠퍼스; 학교 부지',
    zh: '校园',
    englishDefinition: 'the buildings and grounds of a college, university, or school',
    noteEn: 'Very frequent in student services, orientation, and class logistics.',
    noteKo: '학생 서비스, 오리엔테이션, 수업 운영에서 매우 자주 나옵니다.',
    noteZh: '在学生服务、迎新和课程安排中非常常见。',
    exampleEn: 'Visitors must park in the west lot while on campus.',
    exampleKo: '방문객은 캠퍼스 내에 있는 동안 서쪽 주차장을 이용해야 합니다.',
    exampleZh: '访客在校园内时必须停在西侧停车场。',
    collocations: ['on campus', 'campus event', 'campus security'],
  }),
  makeEntry({
    id: 'candidate',
    word: 'candidate',
    usIpa: '/ˈkændɪdət/',
    ukIpa: '/ˈkændɪdət/',
    importance: 4,
    topics: ['work-school'],
    ko: '지원자; 후보자',
    zh: '候选人；应聘者',
    englishDefinition: 'a person being considered for a job, program, or position',
    noteEn: 'Useful for interview, hiring, and scholarship conversations.',
    noteKo: '면접, 채용, 장학금 대화에서 유용합니다.',
    noteZh: '在面试、招聘和奖学金对话中很有用。',
    exampleEn: 'Each candidate will be interviewed for about twenty minutes.',
    exampleKo: '각 지원자는 약 20분 동안 면접을 보게 됩니다.',
    exampleZh: '每位候选人将接受大约二十分钟的面试。',
    collocations: ['job candidate', 'strong candidate', 'candidate profile'],
  }),
  makeEntry({
    id: 'cancellation',
    word: 'cancellation',
    usIpa: '/ˌkænsəˈleɪʃən/',
    ukIpa: '/ˌkænsəˈleɪʃən/',
    importance: 4,
    topics: ['travel-transit', 'housing-services', 'shopping-banking'],
    ko: '취소',
    zh: '取消',
    englishDefinition: 'the act of deciding that something planned will not happen',
    noteEn: 'Extremely common in travel, booking, and service calls.',
    noteKo: '여행, 예약, 서비스 전화에서 매우 자주 나옵니다.',
    noteZh: '在旅行、预订和服务电话中非常常见。',
    exampleEn: 'There is no fee for cancellation if you call at least 24 hours ahead.',
    exampleKo: '24시간 전에 전화하면 취소 수수료가 없습니다.',
    exampleZh: '如果提前至少24小时致电，则不收取消费。',
    collocations: ['cancellation policy', 'free cancellation', 'last-minute cancellation'],
  }),
  makeEntry({
    id: 'caretaker',
    word: 'caretaker',
    usIpa: '/ˈkerˌteɪkər/',
    ukIpa: '/ˈkeəˌteɪkə/',
    importance: 3,
    topics: ['housing-services', 'health-emergency'],
    ko: '관리인; 돌보는 사람',
    zh: '看护人；管理员',
    englishDefinition: 'a person who takes care of a building, place, or person',
    noteEn: 'Often appears in apartment, school, or elder-care contexts.',
    noteKo: '아파트, 학교, 노인 돌봄 문맥에서 자주 보입니다.',
    noteZh: '常见于公寓、学校或老人照护语境中。',
    exampleEn: 'Please leave a note for the caretaker if the office is closed.',
    exampleKo: '사무실이 닫혀 있으면 관리인에게 메모를 남겨 주세요.',
    exampleZh: '如果办公室关门，请给管理员留张便条。',
    collocations: ['building caretaker', 'temporary caretaker', 'caretaker service'],
  }),
  makeEntry({
    id: 'cashback',
    word: 'cash back',
    usIpa: '/ˈkæʃ ˌbæk/',
    ukIpa: '/ˈkæʃ ˌbæk/',
    importance: 3,
    topics: ['shopping-banking'],
    ko: '캐시백; 현금 환급',
    zh: '返现',
    englishDefinition: 'money returned to a customer after a purchase',
    noteEn: 'Useful for card promotions and shopping-service questions.',
    noteKo: '카드 프로모션과 쇼핑 서비스 문제에서 유용합니다.',
    noteZh: '在信用卡促销和购物服务题中很有用。',
    exampleEn: 'This card offers cash back on grocery and gas purchases.',
    exampleKo: '이 카드는 식료품과 주유 구매에 캐시백을 제공합니다.',
    exampleZh: '这张卡在购买食品和汽油时提供返现。',
    collocations: ['cash back offer', 'earn cash back', 'cash back reward'],
  }),
  makeEntry({
    id: 'certificate',
    word: 'certificate',
    usIpa: '/sərˈtɪfəkət/',
    ukIpa: '/səˈtɪfɪkət/',
    importance: 4,
    topics: ['work-school', 'community-civic'],
    ko: '증명서; 자격증',
    zh: '证书；证明',
    englishDefinition: 'an official paper that proves something is true or completed',
    noteEn: 'A common document word for jobs, schools, and government offices.',
    noteKo: '직장, 학교, 관공서에서 자주 나오는 서류 단어입니다.',
    noteZh: '这是在工作、学校和政府机构中常见的文件词。',
    exampleEn: 'Please upload your language certificate with the application.',
    exampleKo: '지원서와 함께 어학 증명서를 업로드해 주세요.',
    exampleZh: '请在申请时上传你的语言证书。',
    collocations: ['birth certificate', 'completion certificate', 'training certificate'],
  }),
  makeEntry({
    id: 'checklist',
    word: 'checklist',
    usIpa: '/ˈtʃekˌlɪst/',
    ukIpa: '/ˈtʃeklɪst/',
    importance: 3,
    topics: ['work-school', 'community-civic', 'problem-solving'],
    ko: '점검 목록; 체크리스트',
    zh: '核对清单',
    englishDefinition: 'a list of things that must be checked or completed',
    noteEn: 'Helpful for instruction tasks where order and completeness matter.',
    noteKo: '순서와 완성도가 중요한 안내 문제에서 도움이 됩니다.',
    noteZh: '在顺序和完整性重要的说明题中很有帮助。',
    exampleEn: 'Use the checklist to make sure all required forms are included.',
    exampleKo: '필요한 서류가 모두 포함되었는지 체크리스트로 확인하세요.',
    exampleZh: '请用清单确认所有必需表格都已包含。',
    collocations: ['safety checklist', 'move-in checklist', 'application checklist'],
  }),
  makeEntry({
    id: 'childcare',
    word: 'childcare',
    usIpa: '/ˈtʃaɪldˌker/',
    ukIpa: '/ˈtʃaɪldkeə/',
    importance: 4,
    topics: ['people-relationships', 'work-school', 'community-civic'],
    ko: '보육; 아이 돌봄',
    zh: '托儿；儿童照护',
    englishDefinition: 'the care of children, especially while parents are working',
    noteEn: 'Often appears in scheduling, budgeting, and family-support contexts.',
    noteKo: '일정, 예산, 가족 지원 문맥에서 자주 나옵니다.',
    noteZh: '常见于时间安排、预算和家庭支持语境中。',
    exampleEn: 'The workshop starts at six, so childcare will be needed.',
    exampleKo: '워크숍이 6시에 시작해서 아이 돌봄이 필요할 것입니다.',
    exampleZh: '讲座六点开始，所以需要安排托儿服务。',
    collocations: ['childcare center', 'childcare costs', 'childcare support'],
  }),
  makeEntry({
    id: 'clinic',
    word: 'clinic',
    usIpa: '/ˈklɪnɪk/',
    ukIpa: '/ˈklɪnɪk/',
    importance: 4,
    topics: ['health-emergency'],
    ko: '클리닉; 진료소',
    zh: '诊所',
    englishDefinition: 'a medical place where patients receive treatment or advice',
    noteEn: 'A core word for health appointments, symptoms, and referrals.',
    noteKo: '건강 예약, 증상, 의뢰 문제의 핵심 단어입니다.',
    noteZh: '这是健康预约、症状和转诊题的核心词。',
    exampleEn: 'The clinic opens at eight-thirty and accepts walk-in patients.',
    exampleKo: '그 진료소는 8시 30분에 문을 열고 예약 없이 온 환자도 받습니다.',
    exampleZh: '这家诊所八点半开门，也接受无需预约的病人。',
    collocations: ['medical clinic', 'walk-in clinic', 'community clinic'],
  }),
  makeEntry({
    id: 'cooperate',
    word: 'cooperate',
    usIpa: '/koʊˈɑːpəˌreɪt/',
    ukIpa: '/kəʊˈɒpəreɪt/',
    importance: 3,
    topics: ['work-school', 'people-relationships'],
    ko: '협력하다',
    zh: '合作',
    englishDefinition: 'to work together willingly toward a shared goal',
    noteEn: 'Shows up in teamwork, customer service, and conflict questions.',
    noteKo: '팀워크, 고객 서비스, 갈등 문제에서 보입니다.',
    noteZh: '会出现在团队合作、客户服务和冲突题中。',
    exampleEn: 'Both departments agreed to cooperate on the new training plan.',
    exampleKo: '두 부서는 새 교육 계획에 협력하기로 동의했습니다.',
    exampleZh: '两个部门同意合作推进新的培训计划。',
    collocations: ['cooperate fully', 'cooperate with staff', 'refuse to cooperate'],
  }),
  makeEntry({
    id: 'counter',
    word: 'counter',
    usIpa: '/ˈkaʊntər/',
    ukIpa: '/ˈkaʊntə/',
    importance: 3,
    topics: ['travel-transit', 'shopping-banking', 'community-civic'],
    ko: '창구; 계산대',
    zh: '柜台',
    englishDefinition: 'a long flat surface where customers are served',
    noteEn: 'Very useful for airport, bank, and service-desk listening items.',
    noteKo: '공항, 은행, 서비스 데스크 듣기에서 매우 유용합니다.',
    noteZh: '在机场、银行和服务台听力中非常有用。',
    exampleEn: 'Please go to counter twelve for oversized baggage.',
    exampleKo: '규격 초과 수하물은 12번 창구로 가 주세요.',
    exampleZh: '超大行李请到12号柜台办理。',
    collocations: ['service counter', 'front counter', 'ticket counter'],
  }),
  makeEntry({
    id: 'credential',
    word: 'credential',
    usIpa: '/krəˈdenʃəl/',
    ukIpa: '/krəˈdenʃəl/',
    importance: 4,
    topics: ['work-school', 'technology-communication'],
    ko: '자격; 인증 정보',
    zh: '资格；登录凭证',
    englishDefinition: 'a qualification or a piece of information used to prove identity',
    noteEn: 'Useful because it can mean education, certification, or login details.',
    noteKo: '학력, 자격증, 로그인 정보 모두를 뜻할 수 있어 중요합니다.',
    noteZh: '它既可以指学历资格，也可以指登录凭证，所以很重要。',
    exampleEn: 'Please bring your credentials to the interview and check-in desk.',
    exampleKo: '면접과 접수 데스크에 자격 증빙 자료를 가져오세요.',
    exampleZh: '请把你的资格证明带到面试和报到柜台。',
    collocations: ['academic credentials', 'login credentials', 'verify credentials'],
  }),
  makeEntry({
    id: 'crosswalk',
    word: 'crosswalk',
    usIpa: '/ˈkrɔːsˌwɔːk/',
    ukIpa: '/ˈkrɒsˌwɔːk/',
    importance: 3,
    topics: ['travel-transit', 'community-civic'],
    ko: '횡단보도',
    zh: '人行横道',
    englishDefinition: 'a marked place where people can cross a road safely',
    noteEn: 'Shows up in directions, public safety, and traffic announcements.',
    noteKo: '길 안내, 공공 안전, 교통 안내에서 보입니다.',
    noteZh: '会出现在路线说明、公共安全和交通通知中。',
    exampleEn: 'Pedestrians should use the crosswalk near the library entrance.',
    exampleKo: '보행자는 도서관 입구 근처 횡단보도를 이용해야 합니다.',
    exampleZh: '行人应使用图书馆入口附近的人行横道。',
    collocations: ['marked crosswalk', 'crosswalk signal', 'use the crosswalk'],
  }),
  makeEntry({
    id: 'curfew',
    word: 'curfew',
    usIpa: '/ˈkɝːfjuː/',
    ukIpa: '/ˈkɜːfjuː/',
    importance: 3,
    topics: ['community-civic', 'housing-services'],
    ko: '통행 금지 시간; 귀가 제한 시간',
    zh: '宵禁；门禁时间',
    englishDefinition: 'a rule that requires people to be indoors by a certain time',
    noteEn: 'Useful in residence, hostel, and public safety rules.',
    noteKo: '기숙사, 호스텔, 공공 안전 규정에서 유용합니다.',
    noteZh: '在宿舍、旅舍和公共安全规定中很有用。',
    exampleEn: 'The residence hall has a weekend curfew for visitors.',
    exampleKo: '그 기숙사는 주말 방문객에게 통행 제한 시간이 있습니다.',
    exampleZh: '那栋宿舍楼对访客设有周末门禁时间。',
    collocations: ['strict curfew', 'curfew hours', 'break curfew'],
  }),
  makeEntry({
    id: 'designate',
    word: 'designate',
    usIpa: '/ˈdezɪɡˌneɪt/',
    ukIpa: '/ˈdezɪɡneɪt/',
    importance: 3,
    topics: ['community-civic', 'housing-services', 'travel-transit'],
    ko: '지정하다',
    zh: '指定',
    englishDefinition: 'to officially choose or mark something for a particular purpose',
    noteEn: 'Useful for parking areas, pickup zones, and special-use spaces.',
    noteKo: '주차 구역, 승하차 구역, 특별 사용 공간에서 유용합니다.',
    noteZh: '在停车区、上下车区域和专用空间里很常用。',
    exampleEn: 'Please use the designated entrance during the repair period.',
    exampleKo: '수리 기간 동안 지정된 출입구를 이용해 주세요.',
    exampleZh: '维修期间请使用指定入口。',
    collocations: ['designated area', 'designated entrance', 'designate a zone'],
  }),
  makeEntry({
    id: 'device',
    word: 'device',
    usIpa: '/dɪˈvaɪs/',
    ukIpa: '/dɪˈvaɪs/',
    importance: 4,
    topics: ['technology-communication'],
    ko: '기기; 장치',
    zh: '设备；装置',
    englishDefinition: 'a phone, tablet, computer, or other piece of equipment',
    noteEn: 'A high-frequency technology word across login, app, and repair tasks.',
    noteKo: '로그인, 앱, 수리 문제 전반에서 자주 나오는 기술 단어입니다.',
    noteZh: '这是登录、应用和维修题中的高频科技词。',
    exampleEn: 'The app will not open on older devices after the update.',
    exampleKo: '업데이트 후에는 오래된 기기에서 앱이 열리지 않습니다.',
    exampleZh: '更新后，该应用在旧设备上无法打开。',
    collocations: ['mobile device', 'compatible device', 'device settings'],
  }),
  makeEntry({
    id: 'donation',
    word: 'donation',
    usIpa: '/doʊˈneɪʃən/',
    ukIpa: '/dəʊˈneɪʃən/',
    importance: 3,
    topics: ['community-civic', 'people-relationships'],
    ko: '기부; 기부금',
    zh: '捐赠；捐款',
    englishDefinition: 'money or goods that are given to help a person or organization',
    noteEn: 'Appears in volunteer, school, and local event contexts.',
    noteKo: '봉사, 학교, 지역 행사 문맥에서 보입니다.',
    noteZh: '会出现在志愿活动、学校和社区活动语境中。',
    exampleEn: 'All ticket sales will go toward the food-bank donation drive.',
    exampleKo: '모든 티켓 판매 수익은 푸드뱅크 기부 행사에 사용됩니다.',
    exampleZh: '所有门票收入都将用于食物银行募捐活动。',
    collocations: ['make a donation', 'donation drive', 'charitable donation'],
  }),
  makeEntry({
    id: 'draft',
    word: 'draft',
    usIpa: '/dræft/',
    ukIpa: '/drɑːft/',
    importance: 3,
    topics: ['work-school', 'news-opinion'],
    ko: '초안',
    zh: '草稿',
    englishDefinition: 'an early version of a piece of writing or plan',
    noteEn: 'Useful for emails, reports, and proposal discussions.',
    noteKo: '이메일, 보고서, 제안서 대화에서 유용합니다.',
    noteZh: '在邮件、报告和提案讨论中很有用。',
    exampleEn: 'Please send me the first draft before Thursday afternoon.',
    exampleKo: '목요일 오후 전까지 첫 초안을 보내 주세요.',
    exampleZh: '请在周四下午前把第一版草稿发给我。',
    collocations: ['first draft', 'draft report', 'finalize the draft'],
  }),
  makeEntry({
    id: 'duration',
    word: 'duration',
    usIpa: '/dʊˈreɪʃən/',
    ukIpa: '/djʊˈreɪʃən/',
    importance: 3,
    topics: ['travel-transit', 'work-school', 'health-emergency'],
    ko: '지속 시간; 기간',
    zh: '持续时间；时长',
    englishDefinition: 'the amount of time something continues',
    noteEn: 'Useful when the answer depends on how long something lasts.',
    noteKo: '무언가가 얼마나 오래 지속되는지가 정답인 문제에서 유용합니다.',
    noteZh: '当答案取决于事情持续多久时，这个词很有用。',
    exampleEn: 'The workshop duration has been shortened from three hours to two.',
    exampleKo: '워크숍 기간이 3시간에서 2시간으로 줄었습니다.',
    exampleZh: '该工作坊时长已从三小时缩短到两小时。',
    collocations: ['course duration', 'duration of the test', 'average duration'],
  }),
  makeEntry({
    id: 'efficiency',
    word: 'efficiency',
    usIpa: '/ɪˈfɪʃənsi/',
    ukIpa: '/ɪˈfɪʃənsi/',
    importance: 3,
    topics: ['work-school', 'technology-communication', 'news-opinion'],
    ko: '효율성',
    zh: '效率',
    englishDefinition: 'the ability to do something well without wasting time or resources',
    noteEn: 'Useful in reports, meetings, and process-improvement discussions.',
    noteKo: '보고서, 회의, 절차 개선 대화에서 유용합니다.',
    noteZh: '在报告、会议和流程优化讨论中很有用。',
    exampleEn: 'The software upgrade improved efficiency across the whole office.',
    exampleKo: '소프트웨어 업그레이드로 사무실 전체의 효율성이 향상되었습니다.',
    exampleZh: '软件升级提高了整个办公室的效率。',
    collocations: ['improve efficiency', 'energy efficiency', 'work efficiency'],
  }),
  makeEntry({
    id: 'emergency-exit',
    word: 'emergency exit',
    usIpa: '/ɪˈmɝːdʒənsi ˈeɡzɪt/',
    ukIpa: '/ɪˈmɜːdʒənsi ˈeɡzɪt/',
    importance: 3,
    topics: ['health-emergency', 'community-civic', 'travel-transit'],
    ko: '비상구',
    zh: '紧急出口',
    englishDefinition: 'a special door or path used to leave safely in a dangerous situation',
    noteEn: 'Very useful in public safety announcements and building instructions.',
    noteKo: '공공 안전 방송과 건물 안내에서 매우 유용합니다.',
    noteZh: '在公共安全广播和建筑说明中非常有用。',
    exampleEn: 'Please keep the emergency exit clear at all times.',
    exampleKo: '비상구는 항상 비워 두시기 바랍니다.',
    exampleZh: '请始终保持紧急出口畅通。',
    collocations: ['nearest emergency exit', 'block the exit', 'exit route'],
  }),
  makeEntry({
    id: 'employer',
    word: 'employer',
    usIpa: '/ɪmˈplɔɪər/',
    ukIpa: '/ɪmˈplɔɪə/',
    importance: 4,
    topics: ['work-school'],
    ko: '고용주',
    zh: '雇主',
    englishDefinition: 'a person or company that pays people to work',
    noteEn: 'Common in HR, benefits, and work-reference conversations.',
    noteKo: '인사, 복지, 경력 확인 대화에서 자주 나옵니다.',
    noteZh: '常见于人事、福利和工作证明对话中。',
    exampleEn: 'Your current employer must complete the reference section.',
    exampleKo: '현재 고용주가 추천서 부분을 작성해야 합니다.',
    exampleZh: '你当前的雇主必须填写推荐部分。',
    collocations: ['current employer', 'former employer', 'employer reference'],
  }),
  makeEntry({
    id: 'endorse',
    word: 'endorse',
    usIpa: '/ɪnˈdɔːrs/',
    ukIpa: '/ɪnˈdɔːs/',
    importance: 3,
    topics: ['work-school', 'news-opinion'],
    ko: '지지하다; 승인하다',
    zh: '支持；认可',
    englishDefinition: 'to publicly support or approve something',
    noteEn: 'Useful in opinion, policy, and recommendation contexts.',
    noteKo: '의견, 정책, 추천 문맥에서 유용합니다.',
    noteZh: '在观点、政策和推荐语境中很有用。',
    exampleEn: 'The board did not endorse the proposal in its current form.',
    exampleKo: '이사회는 현재 형태의 제안을 지지하지 않았습니다.',
    exampleZh: '董事会没有认可该提案目前的形式。',
    collocations: ['endorse a proposal', 'endorse a candidate', 'officially endorse'],
  }),
  makeEntry({
    id: 'entry',
    word: 'entry',
    usIpa: '/ˈentri/',
    ukIpa: '/ˈentri/',
    importance: 3,
    topics: ['travel-transit', 'community-civic', 'work-school'],
    ko: '입장; 입구; 항목',
    zh: '进入；入口；条目',
    englishDefinition: 'the act of entering, a way in, or a listed item',
    noteEn: 'Useful because its meaning changes with the context.',
    noteKo: '문맥에 따라 의미가 달라져 중요합니다.',
    noteZh: '因为它会随语境改变意思，所以很重要。',
    exampleEn: 'Late entry will not be allowed after the test begins.',
    exampleKo: '시험이 시작된 후에는 늦은 입장이 허용되지 않습니다.',
    exampleZh: '考试开始后将不允许迟到进入。',
    collocations: ['main entry', 'entry fee', 'late entry'],
  }),
  makeEntry({
    id: 'evacuation',
    word: 'evacuation',
    usIpa: '/ɪˌvækjuˈeɪʃən/',
    ukIpa: '/ɪˌvækjuˈeɪʃən/',
    importance: 3,
    topics: ['health-emergency', 'community-civic'],
    ko: '대피',
    zh: '疏散；撤离',
    englishDefinition: 'the act of moving people away from a dangerous place',
    noteEn: 'Appears in emergency drills, public warnings, and safety policies.',
    noteKo: '대피 훈련, 공공 경보, 안전 정책에서 보입니다.',
    noteZh: '会出现在疏散演练、公共警报和安全政策中。',
    exampleEn: 'Staff reviewed the evacuation plan before the event started.',
    exampleKo: '행사 시작 전에 직원들이 대피 계획을 검토했습니다.',
    exampleZh: '活动开始前，工作人员审查了疏散计划。',
    collocations: ['evacuation route', 'evacuation plan', 'order an evacuation'],
  }),
  makeEntry({
    id: 'exemption',
    word: 'exemption',
    usIpa: '/ɪɡˈzempʃən/',
    ukIpa: '/ɪɡˈzempʃən/',
    importance: 4,
    topics: ['community-civic', 'work-school', 'shopping-banking'],
    ko: '면제',
    zh: '豁免',
    englishDefinition: 'special permission not to follow a rule or pay a charge',
    noteEn: 'Useful for fees, deadlines, parking, and eligibility rules.',
    noteKo: '수수료, 마감일, 주차, 자격 규정에서 유용합니다.',
    noteZh: '在费用、截止日期、停车和资格规定中很有用。',
    exampleEn: 'Students with disabilities can apply for a parking-fee exemption.',
    exampleKo: '장애가 있는 학생은 주차비 면제를 신청할 수 있습니다.',
    exampleZh: '有残障的学生可以申请停车费豁免。',
    collocations: ['tax exemption', 'fee exemption', 'apply for exemption'],
  }),
  makeEntry({
    id: 'facilitator',
    word: 'facilitator',
    usIpa: '/fəˈsɪləˌteɪtər/',
    ukIpa: '/fəˈsɪlɪteɪtə/',
    importance: 3,
    topics: ['work-school', 'community-civic'],
    ko: '진행자; 촉진자',
    zh: '主持人；引导者',
    englishDefinition: 'a person who helps a group discussion or activity run smoothly',
    noteEn: 'Useful in workshops, training sessions, and group meetings.',
    noteKo: '워크숍, 교육 세션, 그룹 회의에서 유용합니다.',
    noteZh: '在工作坊、培训课程和小组会议中很有用。',
    exampleEn: 'The facilitator will divide the class into smaller discussion groups.',
    exampleKo: '진행자가 수업을 더 작은 토론 조로 나눌 것입니다.',
    exampleZh: '主持人会把班级分成更小的讨论组。',
    collocations: ['session facilitator', 'lead facilitator', 'facilitator notes'],
  }),
  makeEntry({
    id: 'faulty',
    word: 'faulty',
    usIpa: '/ˈfɔːlti/',
    ukIpa: '/ˈfɒlti/',
    importance: 4,
    topics: ['housing-services', 'technology-communication', 'shopping-banking'],
    ko: '결함이 있는; 고장 난',
    zh: '有故障的；有缺陷的',
    englishDefinition: 'not working correctly or having a problem',
    noteEn: 'Useful for warranty, complaint, and repair situations.',
    noteKo: '보증, 민원, 수리 상황에서 유용합니다.',
    noteZh: '在保修、投诉和维修场景中很有用。',
    exampleEn: 'The customer said the item was faulty when it arrived.',
    exampleKo: '고객은 물건이 도착했을 때부터 결함이 있었다고 말했습니다.',
    exampleZh: '顾客说商品送到时就有故障。',
    collocations: ['faulty equipment', 'faulty item', 'faulty wiring'],
  }),
  makeEntry({
    id: 'financial-aid',
    word: 'financial aid',
    usIpa: '/fəˌnænʃəl ˈeɪd/',
    ukIpa: '/faɪˌnænʃəl ˈeɪd/',
    importance: 4,
    topics: ['work-school', 'shopping-banking'],
    ko: '재정 지원; 학비 지원',
    zh: '经济资助；助学金',
    englishDefinition: 'money given to help someone pay for school or another need',
    noteEn: 'A common campus-services term in CELPIP school tasks.',
    noteKo: 'CELPIP 학업 문제에서 자주 나오는 캠퍼스 서비스 단어입니다.',
    noteZh: '这是 CELPIP 学校题中常见的校园服务词。',
    exampleEn: 'The deadline for financial aid applications is March fifteenth.',
    exampleKo: '재정 지원 신청 마감일은 3월 15일입니다.',
    exampleZh: '经济资助申请截止日期是3月15日。',
    collocations: ['financial aid office', 'financial aid package', 'apply for aid'],
  }),
  makeEntry({
    id: 'fire-drill',
    word: 'fire drill',
    usIpa: '/ˈfaɪər drɪl/',
    ukIpa: '/ˈfaɪə drɪl/',
    importance: 3,
    topics: ['community-civic', 'work-school', 'housing-services'],
    ko: '화재 대피 훈련',
    zh: '消防演习',
    englishDefinition: 'a practice activity for leaving a building safely in a fire',
    noteEn: 'Often appears in notices with times, exits, and behavior rules.',
    noteKo: '시간, 출구, 행동 규정이 함께 나오는 공지문에서 자주 보입니다.',
    noteZh: '常见于带有时间、出口和行为规定的通知中。',
    exampleEn: 'Tomorrow’s fire drill will begin shortly after noon.',
    exampleKo: '내일 화재 대피 훈련은 정오 직후 시작됩니다.',
    exampleZh: '明天的消防演习将在中午后不久开始。',
    collocations: ['annual fire drill', 'fire drill notice', 'take part in the drill'],
  }),
  makeEntry({
    id: 'forecast',
    word: 'forecast',
    usIpa: '/ˈfɔːrˌkæst/',
    ukIpa: '/ˈfɔːkɑːst/',
    importance: 3,
    topics: ['news-opinion', 'travel-transit'],
    ko: '예보; 전망',
    zh: '预报；预测',
    englishDefinition: 'a statement about what is expected in the future',
    noteEn: 'Useful in weather, finance, and trend-report questions.',
    noteKo: '날씨, 재정, 추세 리포트 문제에서 유용합니다.',
    noteZh: '在天气、金融和趋势报道题中很有用。',
    exampleEn: 'The forecast says roads may be icy by the evening commute.',
    exampleKo: '예보에 따르면 저녁 출퇴근 시간에는 도로가 얼 수 있다고 합니다.',
    exampleZh: '预报说到晚高峰时道路可能结冰。',
    collocations: ['weather forecast', 'sales forecast', 'forecast growth'],
  }),
  makeEntry({
    id: 'furnish',
    word: 'furnish',
    usIpa: '/ˈfɝːnɪʃ/',
    ukIpa: '/ˈfɜːnɪʃ/',
    importance: 3,
    topics: ['housing-services'],
    ko: '가구를 비치하다; 제공하다',
    zh: '配备家具；提供',
    englishDefinition: 'to supply furniture, equipment, or needed information',
    noteEn: 'Important because it can refer to furniture or official documents.',
    noteKo: '가구 제공도, 서류 제공도 뜻할 수 있어 중요합니다.',
    noteZh: '它既可表示配家具，也可表示提供文件，因此很重要。',
    exampleEn: 'The apartment is partially furnished but does not include a desk.',
    exampleKo: '그 아파트는 일부 가구가 비치되어 있지만 책상은 포함되지 않습니다.',
    exampleZh: '这套公寓部分带家具，但不包括书桌。',
    collocations: ['fully furnished', 'furnish a room', 'furnish proof'],
  }),
  makeEntry({
    id: 'gradually',
    word: 'gradually',
    usIpa: '/ˈɡrædʒuəli/',
    ukIpa: '/ˈɡrædʒuəli/',
    importance: 3,
    topics: ['news-opinion', 'health-emergency', 'work-school'],
    ko: '점차; 서서히',
    zh: '逐渐地',
    englishDefinition: 'slowly over a period of time',
    noteEn: 'A useful adverb in trends, recovery, and change questions.',
    noteKo: '추세, 회복, 변화 문제에서 유용한 부사입니다.',
    noteZh: '这是趋势、恢复和变化题中很有用的副词。',
    exampleEn: 'The system will gradually return to normal after the update.',
    exampleKo: '업데이트 후 시스템은 점차 정상으로 돌아올 것입니다.',
    exampleZh: '更新后系统将逐渐恢复正常。',
    collocations: ['gradually improve', 'gradually increase', 'gradually recover'],
  }),
  makeEntry({
    id: 'grievance',
    word: 'grievance',
    usIpa: '/ˈɡriːvəns/',
    ukIpa: '/ˈɡriːvəns/',
    importance: 3,
    topics: ['work-school', 'people-relationships', 'problem-solving'],
    ko: '고충; 불만 사항',
    zh: '申诉；不满',
    englishDefinition: 'a formal complaint about something unfair or wrong',
    noteEn: 'Useful in workplace policy and resident complaint situations.',
    noteKo: '직장 규정과 입주민 불만 상황에서 유용합니다.',
    noteZh: '在职场政策和住户投诉场景中很有用。',
    exampleEn: 'Employees can file a grievance if the issue is not resolved informally.',
    exampleKo: '문제가 비공식적으로 해결되지 않으면 직원은 고충을 제기할 수 있습니다.',
    exampleZh: '如果问题未能非正式解决，员工可以提出申诉。',
    collocations: ['file a grievance', 'formal grievance', 'grievance procedure'],
  }),
  makeEntry({
    id: 'guarantee',
    word: 'guarantee',
    usIpa: '/ˌɡerənˈtiː/',
    ukIpa: '/ˌɡærənˈtiː/',
    importance: 4,
    topics: ['shopping-banking', 'housing-services'],
    ko: '보장하다; 보증',
    zh: '保证；担保',
    englishDefinition: 'a promise that something will happen or work as expected',
    noteEn: 'Closely related to service promises, refunds, and warranties.',
    noteKo: '서비스 약속, 환불, 보증과 밀접한 단어입니다.',
    noteZh: '与服务承诺、退款和保修密切相关。',
    exampleEn: 'This plan does not guarantee same-day technical support.',
    exampleKo: '이 플랜은 당일 기술 지원을 보장하지 않습니다.',
    exampleZh: '该方案不保证当天提供技术支持。',
    collocations: ['money-back guarantee', 'guarantee results', 'under guarantee'],
  }),
  makeEntry({
    id: 'hardship',
    word: 'hardship',
    usIpa: '/ˈhɑːrdʃɪp/',
    ukIpa: '/ˈhɑːdʃɪp/',
    importance: 4,
    topics: ['shopping-banking', 'work-school', 'people-relationships'],
    ko: '어려움; 고충',
    zh: '困难；艰辛',
    englishDefinition: 'a difficult situation, especially involving money or life problems',
    noteEn: 'Useful in fee-waiver, deadline-extension, and support contexts.',
    noteKo: '수수료 면제, 기한 연장, 지원 문맥에서 유용합니다.',
    noteZh: '在费用减免、延期和援助语境中很有用。',
    exampleEn: 'Students facing financial hardship can request a payment plan.',
    exampleKo: '재정적 어려움을 겪는 학생은 분할 납부 계획을 요청할 수 있습니다.',
    exampleZh: '面临经济困难的学生可以申请分期付款计划。',
    collocations: ['financial hardship', 'hardship case', 'hardship request'],
  }),
  makeEntry({
    id: 'hazard',
    word: 'hazard',
    usIpa: '/ˈhæzərd/',
    ukIpa: '/ˈhæzəd/',
    importance: 4,
    topics: ['health-emergency', 'community-civic', 'housing-services'],
    ko: '위험 요소',
    zh: '危险；隐患',
    englishDefinition: 'something that could cause harm or danger',
    noteEn: 'A strong safety word for notices, inspections, and incident reports.',
    noteKo: '공지, 점검, 사고 보고에서 중요한 안전 단어입니다.',
    noteZh: '这是通知、检查和事故报告中的重要安全词。',
    exampleEn: 'Wet floors can be a serious hazard for visitors.',
    exampleKo: '젖은 바닥은 방문객에게 심각한 위험 요소가 될 수 있습니다.',
    exampleZh: '潮湿地面可能对访客造成严重危险。',
    collocations: ['safety hazard', 'fire hazard', 'hazard warning'],
  }),
  makeEntry({
    id: 'heating',
    word: 'heating',
    usIpa: '/ˈhiːtɪŋ/',
    ukIpa: '/ˈhiːtɪŋ/',
    importance: 4,
    topics: ['housing-services'],
    ko: '난방',
    zh: '供暖',
    englishDefinition: 'the system that provides warmth in a building',
    noteEn: 'Common in apartment complaints and seasonal service notices.',
    noteKo: '아파트 민원과 계절성 공지에서 자주 보입니다.',
    noteZh: '常见于公寓投诉和季节性服务通知中。',
    exampleEn: 'Heating will be turned off temporarily for maintenance.',
    exampleKo: '유지 보수를 위해 난방이 일시적으로 중단될 예정입니다.',
    exampleZh: '供暖将因维护而暂时关闭。',
    collocations: ['central heating', 'heating system', 'heating bill'],
  }),
  makeEntry({
    id: 'hesitate',
    word: 'hesitate',
    usIpa: '/ˈhezɪˌteɪt/',
    ukIpa: '/ˈhezɪteɪt/',
    importance: 3,
    topics: ['people-relationships', 'problem-solving'],
    ko: '주저하다; 망설이다',
    zh: '犹豫；迟疑',
    englishDefinition: 'to pause before doing or saying something because you are unsure',
    noteEn: 'Useful for tone, politeness, and support-based speaking/listening tasks.',
    noteKo: '태도, 공손함, 지원 맥락의 말하기·듣기에서 유용합니다.',
    noteZh: '在语气、礼貌和支持类口语听力中很有用。',
    exampleEn: 'Please do not hesitate to contact us if you need more information.',
    exampleKo: '더 많은 정보가 필요하면 주저하지 말고 연락해 주세요.',
    exampleZh: '如果你需要更多信息，请不要犹豫与我们联系。',
    collocations: ['hesitate to ask', 'do not hesitate', 'hesitate before replying'],
  }),
  makeEntry({
    id: 'identity',
    word: 'identity',
    usIpa: '/aɪˈdentəti/',
    ukIpa: '/aɪˈdentəti/',
    importance: 4,
    topics: ['shopping-banking', 'community-civic', 'technology-communication'],
    ko: '신원; 정체성',
    zh: '身份；身份信息',
    englishDefinition: 'who a person is, especially for official proof purposes',
    noteEn: 'Important in banking, security, and application tasks.',
    noteKo: '은행, 보안, 신청서 문제에서 중요합니다.',
    noteZh: '在银行、安全和申请任务中很重要。',
    exampleEn: 'You must verify your identity before the account can be reopened.',
    exampleKo: '계정을 다시 열기 전에 신원을 확인해야 합니다.',
    exampleZh: '在重新开启账户前，你必须验证身份。',
    collocations: ['proof of identity', 'identity verification', 'identity document'],
  }),
  makeEntry({
    id: 'incident',
    word: 'incident',
    usIpa: '/ˈɪnsɪdənt/',
    ukIpa: '/ˈɪnsɪdənt/',
    importance: 4,
    topics: ['community-civic', 'health-emergency', 'problem-solving'],
    ko: '사건; 사고',
    zh: '事件；事故',
    englishDefinition: 'an event, especially one that is unusual, unpleasant, or important',
    noteEn: 'Useful in public notices, workplace reports, and complaint situations.',
    noteKo: '공공 공지, 직장 보고, 민원 상황에서 유용합니다.',
    noteZh: '在公共通知、工作报告和投诉情境中很有用。',
    exampleEn: 'Please report any incident to security as soon as possible.',
    exampleKo: '어떤 사건이든 가능한 한 빨리 보안팀에 신고해 주세요.',
    exampleZh: '如有任何事件，请尽快向安保部门报告。',
    collocations: ['report an incident', 'security incident', 'incident report'],
  }),
  makeEntry({
    id: 'inconvenience',
    word: 'inconvenience',
    usIpa: '/ˌɪnkənˈviːniəns/',
    ukIpa: '/ˌɪnkənˈviːniəns/',
    importance: 5,
    topics: ['housing-services', 'travel-transit', 'problem-solving'],
    ko: '불편',
    zh: '不便',
    englishDefinition: 'trouble or difficulty caused by a situation',
    noteEn: 'A must-know service word in apology, delay, and complaint messages.',
    noteKo: '사과, 지연, 민원 메시지에서 꼭 알아야 할 서비스 단어입니다.',
    noteZh: '这是在道歉、延误和投诉信息中必须掌握的服务词。',
    exampleEn: 'We apologize for any inconvenience this outage may cause.',
    exampleKo: '이번 정전으로 불편을 끼쳐 드려 죄송합니다.',
    exampleZh: '对于此次停电可能带来的不便，我们深表歉意。',
    collocations: ['cause inconvenience', 'minor inconvenience', 'for any inconvenience'],
  }),
  makeEntry({
    id: 'indicate',
    word: 'indicate',
    usIpa: '/ˈɪndəˌkeɪt/',
    ukIpa: '/ˈɪndɪkeɪt/',
    importance: 4,
    topics: ['news-opinion', 'work-school', 'community-civic'],
    ko: '나타내다; 표시하다',
    zh: '表明；显示',
    englishDefinition: 'to show, point to, or make something clear',
    noteEn: 'Very useful in reports and forms where details signal the answer.',
    noteKo: '세부 정보가 정답을 알려 주는 보고서와 양식에서 매우 유용합니다.',
    noteZh: '在报告和表格中细节指向答案时非常有用。',
    exampleEn: 'Please indicate whether you need parking or transit support.',
    exampleKo: '주차 또는 교통 지원이 필요한지 표시해 주세요.',
    exampleZh: '请注明你是否需要停车或交通支持。',
    collocations: ['indicate clearly', 'results indicate', 'indicate a preference'],
  }),
  makeEntry({
    id: 'installment',
    word: 'installment',
    usIpa: '/ɪnˈstɔːlmənt/',
    ukIpa: '/ɪnˈstɔːlmənt/',
    importance: 4,
    topics: ['shopping-banking', 'work-school'],
    ko: '할부금; 분할 납부',
    zh: '分期付款；分期金额',
    englishDefinition: 'one of several smaller payments made over time',
    noteEn: 'Useful for tuition, fees, and large-purchase conversations.',
    noteKo: '학비, 수수료, 고가 구매 대화에서 유용합니다.',
    noteZh: '在学费、费用和大额购买对话中很有用。',
    exampleEn: 'You can pay the balance in three monthly installments.',
    exampleKo: '잔액은 3개월 할부로 낼 수 있습니다.',
    exampleZh: '你可以把余额分三个月支付。',
    collocations: ['monthly installment', 'pay in installments', 'installment plan'],
  }),
  makeEntry({
    id: 'interruption',
    word: 'interruption',
    usIpa: '/ˌɪntəˈrʌpʃən/',
    ukIpa: '/ˌɪntəˈrʌpʃən/',
    importance: 3,
    topics: ['technology-communication', 'housing-services', 'work-school'],
    ko: '중단; 방해',
    zh: '中断；打扰',
    englishDefinition: 'a break in a service, process, or conversation',
    noteEn: 'Useful for power, internet, and meeting-related problems.',
    noteKo: '전기, 인터넷, 회의 관련 문제에서 유용합니다.',
    noteZh: '在电力、网络和会议问题中很有用。',
    exampleEn: 'There may be a brief water interruption during the repair.',
    exampleKo: '수리 중에는 잠시 단수가 있을 수 있습니다.',
    exampleZh: '维修期间可能会有短暂的停水。',
    collocations: ['service interruption', 'brief interruption', 'without interruption'],
  }),
  makeEntry({
    id: 'interview',
    word: 'interview',
    usIpa: '/ˈɪntərˌvjuː/',
    ukIpa: '/ˈɪntəvjuː/',
    importance: 4,
    topics: ['work-school', 'news-opinion'],
    ko: '면접; 인터뷰',
    zh: '面试；采访',
    englishDefinition: 'a formal meeting to ask questions for a job, school place, or report',
    noteEn: 'Its meaning changes depending on whether the context is jobs or news.',
    noteKo: '직장 문맥인지 뉴스 문맥인지에 따라 의미가 달라집니다.',
    noteZh: '它会根据是求职还是新闻语境而改变意思。',
    exampleEn: 'Candidates should arrive fifteen minutes early for the interview.',
    exampleKo: '지원자는 면접 15분 전에 도착해야 합니다.',
    exampleZh: '候选人应提前十五分钟到达面试地点。',
    collocations: ['job interview', 'panel interview', 'interview process'],
  }),
  makeEntry({
    id: 'inventory',
    word: 'inventory',
    usIpa: '/ˈɪnvənˌtɔːri/',
    ukIpa: '/ˈɪnvəntəri/',
    importance: 3,
    topics: ['shopping-banking', 'work-school'],
    ko: '재고 목록; 재고',
    zh: '库存；清单',
    englishDefinition: 'the goods a company has available for sale or use',
    noteEn: 'Useful for supply delays, shortages, and ordering conversations.',
    noteKo: '공급 지연, 품절, 주문 대화에서 유용합니다.',
    noteZh: '在供货延迟、短缺和订货对话中很有用。',
    exampleEn: 'The store is checking inventory before promising a replacement.',
    exampleKo: '매장은 교환을 약속하기 전에 재고를 확인하고 있습니다.',
    exampleZh: '商店在承诺更换前正在检查库存。',
    collocations: ['check inventory', 'inventory shortage', 'inventory system'],
  }),
  makeEntry({
    id: 'invoice',
    word: 'invoice',
    usIpa: '/ˈɪnˌvɔɪs/',
    ukIpa: '/ˈɪnvɔɪs/',
    importance: 4,
    topics: ['shopping-banking', 'work-school'],
    ko: '송장; 청구서',
    zh: '发票；账单',
    englishDefinition: 'an official document that lists what must be paid',
    noteEn: 'Important in billing, reimbursement, and office purchasing tasks.',
    noteKo: '청구, 환급, 사무실 구매 문제에서 중요합니다.',
    noteZh: '在计费、报销和办公采购任务中很重要。',
    exampleEn: 'Please attach the invoice when you request reimbursement.',
    exampleKo: '환급을 요청할 때 송장을 첨부해 주세요.',
    exampleZh: '申请报销时请附上发票。',
    collocations: ['issue an invoice', 'invoice number', 'paid invoice'],
  }),
  makeEntry({
    id: 'itinerary',
    word: 'itinerary',
    usIpa: '/aɪˈtɪnəˌreri/',
    ukIpa: '/aɪˈtɪnərəri/',
    importance: 4,
    topics: ['travel-transit'],
    ko: '여행 일정표',
    zh: '行程单',
    englishDefinition: 'a detailed travel plan including times and places',
    noteEn: 'A common travel document word in listening and speaking tasks.',
    noteKo: '듣기와 말하기 문제에서 자주 보이는 여행 서류 단어입니다.',
    noteZh: '这是听力和口语题中常见的旅行文件词。',
    exampleEn: 'The updated itinerary includes a later train connection.',
    exampleKo: '수정된 일정표에는 더 늦은 기차 환승편이 포함되어 있습니다.',
    exampleZh: '更新后的行程单包含更晚的火车换乘安排。',
    collocations: ['travel itinerary', 'revised itinerary', 'share the itinerary'],
  }),
  makeEntry({
    id: 'landlord',
    word: 'landlord',
    usIpa: '/ˈlændˌlɔːrd/',
    ukIpa: '/ˈlændlɔːd/',
    importance: 5,
    topics: ['housing-services'],
    ko: '집주인; 임대인',
    zh: '房东',
    englishDefinition: 'the person who rents out a house or apartment',
    noteEn: 'A core CELPIP housing word. It is worth recognizing instantly.',
    noteKo: '셀핍 주거 영역 핵심 단어라 바로 알아들어야 합니다.',
    noteZh: '这是 CELPIP 住房板块的核心词，最好一听就懂。',
    exampleEn: 'The landlord agreed to send someone to fix the leak tomorrow.',
    exampleKo: '집주인은 내일 누수를 수리할 사람을 보내기로 했습니다.',
    exampleZh: '房东同意明天派人来修漏水问题。',
    collocations: ['contact the landlord', 'landlord approval', 'landlord notice'],
  }),
  makeEntry({
    id: 'laundry',
    word: 'laundry',
    usIpa: '/ˈlɔːndri/',
    ukIpa: '/ˈlɔːndri/',
    importance: 3,
    topics: ['housing-services'],
    ko: '세탁; 세탁실',
    zh: '洗衣；洗衣房',
    englishDefinition: 'clothes that need washing or the place where they are washed',
    noteEn: 'Useful in apartment rules, shared-space notices, and daily-life questions.',
    noteKo: '아파트 규정, 공용 공간 공지, 일상 문제에서 유용합니다.',
    noteZh: '在公寓规定、公共空间通知和日常题中很有用。',
    exampleEn: 'The laundry room will be closed for cleaning on Sunday morning.',
    exampleKo: '세탁실은 일요일 아침 청소로 인해 닫힐 예정입니다.',
    exampleZh: '洗衣房将于周日上午因清洁而关闭。',
    collocations: ['laundry room', 'do the laundry', 'shared laundry'],
  }),
  makeEntry({
    id: 'luggage',
    word: 'luggage',
    usIpa: '/ˈlʌɡɪdʒ/',
    ukIpa: '/ˈlʌɡɪdʒ/',
    importance: 4,
    topics: ['travel-transit'],
    ko: '짐; 여행 가방',
    zh: '行李',
    englishDefinition: 'the bags and suitcases someone takes on a trip',
    noteEn: 'Similar to baggage, but still worth knowing because both forms appear.',
    noteKo: 'baggage와 비슷하지만 둘 다 자주 나와서 알아둘 가치가 있습니다.',
    noteZh: '它和 baggage 类似，但两种说法都很常见，值得掌握。',
    exampleEn: 'Guests may leave their luggage at the hotel after checkout.',
    exampleKo: '고객은 체크아웃 후 호텔에 짐을 맡길 수 있습니다.',
    exampleZh: '客人退房后可以把行李寄存在酒店。',
    collocations: ['hand luggage', 'store luggage', 'luggage cart'],
  }),
  makeEntry({
    id: 'mandatory',
    word: 'mandatory',
    usIpa: '/ˈmændəˌtɔːri/',
    ukIpa: '/ˈmændətəri/',
    importance: 4,
    topics: ['work-school', 'community-civic', 'health-emergency'],
    ko: '의무적인',
    zh: '强制性的；必须的',
    englishDefinition: 'required by a rule, law, or policy',
    noteEn: 'Important in training, forms, safety, and legal-policy contexts.',
    noteKo: '교육, 양식, 안전, 법·정책 문맥에서 중요합니다.',
    noteZh: '在培训、表格、安全和法律政策语境中很重要。',
    exampleEn: 'Attendance at the first safety session is mandatory for all staff.',
    exampleKo: '첫 안전 교육 세션 참석은 모든 직원에게 의무입니다.',
    exampleZh: '首次安全培训对所有员工都是强制性的。',
    collocations: ['mandatory training', 'mandatory field', 'mandatory policy'],
  }),
  makeEntry({
    id: 'manual',
    word: 'manual',
    usIpa: '/ˈmænjuəl/',
    ukIpa: '/ˈmænjuəl/',
    importance: 3,
    topics: ['technology-communication', 'housing-services'],
    ko: '사용 설명서; 수동의',
    zh: '手册；手动的',
    englishDefinition: 'a book of instructions, or something operated by hand',
    noteEn: 'Useful because it can refer to a guide or a non-automatic system.',
    noteKo: '설명서도 뜻하고 자동이 아닌 장치도 뜻해 중요합니다.',
    noteZh: '它既指说明书，也指非自动的设备，所以很重要。',
    exampleEn: 'The manual explains how to reset the router safely.',
    exampleKo: '설명서는 라우터를 안전하게 재설정하는 방법을 설명합니다.',
    exampleZh: '手册说明了如何安全地重置路由器。',
    collocations: ['user manual', 'manual reset', 'manual entry'],
  }),
  makeEntry({
    id: 'merge',
    word: 'merge',
    usIpa: '/mɝːdʒ/',
    ukIpa: '/mɜːdʒ/',
    importance: 3,
    topics: ['travel-transit', 'work-school', 'news-opinion'],
    ko: '합치다; 병합하다',
    zh: '合并',
    englishDefinition: 'to combine things into one',
    noteEn: 'Useful in traffic, documents, departments, and company news.',
    noteKo: '교통, 문서, 부서, 기업 뉴스에서 유용합니다.',
    noteZh: '在交通、文档、部门和公司新闻中很有用。',
    exampleEn: 'Drivers must merge carefully before the lane ends.',
    exampleKo: '차선이 끝나기 전에 운전자는 조심해서 합류해야 합니다.',
    exampleZh: '车道结束前，驾驶员必须小心并道。',
    collocations: ['merge lanes', 'merge files', 'merge two teams'],
  }),
  makeEntry({
    id: 'meter',
    word: 'meter',
    usIpa: '/ˈmiːtər/',
    ukIpa: '/ˈmiːtə/',
    importance: 3,
    topics: ['housing-services', 'travel-transit'],
    ko: '계량기; 미터기',
    zh: '计量表；计价器',
    englishDefinition: 'a device that measures usage such as water, gas, electricity, or parking time',
    noteEn: 'Very useful in utilities, parking, and service-charge conversations.',
    noteKo: '공과금, 주차, 서비스 요금 대화에서 유용합니다.',
    noteZh: '在公用事业、停车和服务收费对话中很有用。',
    exampleEn: 'The parking meter only accepts coins and card payments.',
    exampleKo: '주차 미터기는 동전과 카드 결제만 받습니다.',
    exampleZh: '停车计时器只接受硬币和刷卡支付。',
    collocations: ['water meter', 'parking meter', 'meter reading'],
  }),
  makeEntry({
    id: 'misplace',
    word: 'misplace',
    usIpa: '/mɪsˈpleɪs/',
    ukIpa: '/mɪsˈpleɪs/',
    importance: 3,
    topics: ['problem-solving', 'travel-transit', 'work-school'],
    ko: '잘못 두다; 잃어버리다',
    zh: '放错地方；弄丢',
    englishDefinition: 'to put something in the wrong place so it cannot be found easily',
    noteEn: 'Useful in lost-item calls and office document problems.',
    noteKo: '분실물 문의와 사무실 서류 문제에서 유용합니다.',
    noteZh: '在失物咨询和办公室文件问题中很有用。',
    exampleEn: 'I think I misplaced my student card after the workshop.',
    exampleKo: '워크숍 후에 학생증을 잘못 두어 잃어버린 것 같습니다.',
    exampleZh: '我想我在工作坊后把学生卡放错地方了。',
    collocations: ['misplace a card', 'misplace a key', 'misplace a document'],
  }),
  makeEntry({
    id: 'monitor',
    word: 'monitor',
    usIpa: '/ˈmɑːnɪtər/',
    ukIpa: '/ˈmɒnɪtə/',
    importance: 3,
    topics: ['technology-communication', 'work-school', 'health-emergency'],
    ko: '모니터하다; 감시하다; 화면',
    zh: '监测；监控；显示器',
    englishDefinition: 'to watch carefully over time, or a screen used for viewing information',
    noteEn: 'Another context-flexible word that appears in tech and health tasks.',
    noteKo: '기술과 건강 문제에서 모두 나오는 문맥 유동 단어입니다.',
    noteZh: '这是一个在科技和健康题中都会出现的多义词。',
    exampleEn: 'The nurse will monitor your condition for the next hour.',
    exampleKo: '간호사가 다음 한 시간 동안 상태를 관찰할 것입니다.',
    exampleZh: '护士将在接下来的一小时内监测你的情况。',
    collocations: ['monitor progress', 'monitor symptoms', 'computer monitor'],
  }),
  makeEntry({
    id: 'negotiate',
    word: 'negotiate',
    usIpa: '/nɪˈɡoʊʃiˌeɪt/',
    ukIpa: '/nɪˈɡəʊʃieɪt/',
    importance: 4,
    topics: ['people-relationships', 'work-school', 'shopping-banking'],
    ko: '협상하다',
    zh: '协商；谈判',
    englishDefinition: 'to discuss in order to reach an agreement',
    noteEn: 'Useful in complaints, workplace decisions, and service problems.',
    noteKo: '민원, 직장 의사결정, 서비스 문제에서 유용합니다.',
    noteZh: '在投诉、职场决策和服务问题中很有用。',
    exampleEn: 'They were able to negotiate a lower monthly payment.',
    exampleKo: '그들은 더 낮은 월 납부액으로 협상할 수 있었습니다.',
    exampleZh: '他们成功协商出更低的月付款额。',
    collocations: ['negotiate a deal', 'negotiate terms', 'negotiate successfully'],
  }),
  makeEntry({
    id: 'network',
    word: 'network',
    usIpa: '/ˈnetˌwɝːk/',
    ukIpa: '/ˈnetwɜːk/',
    importance: 4,
    topics: ['technology-communication', 'work-school'],
    ko: '네트워크; 인맥',
    zh: '网络；人脉',
    englishDefinition: 'a connected system of computers, or a group of useful contacts',
    noteEn: 'Context tells you whether this is about internet service or professional contacts.',
    noteKo: '인터넷 서비스인지 인맥인지 문맥으로 구분해야 합니다.',
    noteZh: '要根据语境判断它指的是网络服务还是人脉。',
    exampleEn: 'The office network will be offline during the server upgrade.',
    exampleKo: '서버 업그레이드 동안 사무실 네트워크는 오프라인 상태가 됩니다.',
    exampleZh: '服务器升级期间，办公室网络将离线。',
    collocations: ['wireless network', 'build a network', 'network outage'],
  }),
  makeEntry({
    id: 'nominate',
    word: 'nominate',
    usIpa: '/ˈnɑːməˌneɪt/',
    ukIpa: '/ˈnɒmɪneɪt/',
    importance: 3,
    topics: ['community-civic', 'work-school'],
    ko: '지명하다; 추천하다',
    zh: '提名；推荐',
    englishDefinition: 'to formally suggest someone for a role, award, or duty',
    noteEn: 'Useful for volunteer groups, committees, and campus clubs.',
    noteKo: '봉사 단체, 위원회, 학교 동아리에서 유용합니다.',
    noteZh: '在志愿团体、委员会和校园社团中很有用。',
    exampleEn: 'Each team may nominate one member for the leadership award.',
    exampleKo: '각 팀은 리더십 상 후보로 한 명을 지명할 수 있습니다.',
    exampleZh: '每个团队可以提名一名成员竞争领导力奖。',
    collocations: ['nominate a candidate', 'nominate someone', 'award nomination'],
  }),
  makeEntry({
    id: 'occupancy',
    word: 'occupancy',
    usIpa: '/ˈɑːkjəpənsi/',
    ukIpa: '/ˈɒkjəpənsi/',
    importance: 3,
    topics: ['housing-services'],
    ko: '점유 상태; 입주율',
    zh: '入住率；占用情况',
    englishDefinition: 'the state of being occupied or used by people',
    noteEn: 'Useful for housing, hotel, and building-capacity contexts.',
    noteKo: '주거, 호텔, 건물 수용 인원 문맥에서 유용합니다.',
    noteZh: '在住房、酒店和建筑容量语境中很有用。',
    exampleEn: 'Maximum occupancy for the room is four people.',
    exampleKo: '그 방의 최대 수용 인원은 4명입니다.',
    exampleZh: '该房间的最大入住人数为四人。',
    collocations: ['maximum occupancy', 'room occupancy', 'occupancy limit'],
  }),
  makeEntry({
    id: 'occupant',
    word: 'occupant',
    usIpa: '/ˈɑːkjəpənt/',
    ukIpa: '/ˈɒkjʊpənt/',
    importance: 3,
    topics: ['housing-services', 'travel-transit'],
    ko: '거주자; 탑승자',
    zh: '住户；乘员',
    englishDefinition: 'a person who is inside or living in a place or vehicle',
    noteEn: 'Can refer to residents in housing notices or passengers in incident reports.',
    noteKo: '주거 공지에서는 거주자, 사고 보고에서는 탑승자를 뜻할 수 있습니다.',
    noteZh: '在住房通知里可指住户，在事故报告里可指乘员。',
    exampleEn: 'All occupants must leave the building when the alarm sounds.',
    exampleKo: '경보가 울리면 모든 거주자는 건물을 떠나야 합니다.',
    exampleZh: '警报响起时，所有在内人员都必须离开大楼。',
    collocations: ['building occupants', 'vehicle occupant', 'occupant safety'],
  }),
  makeEntry({
    id: 'operator',
    word: 'operator',
    usIpa: '/ˈɑːpəˌreɪtər/',
    ukIpa: '/ˈɒpəreɪtə/',
    importance: 3,
    topics: ['technology-communication', 'travel-transit', 'community-civic'],
    ko: '운영자; 교환원',
    zh: '操作员；接线员；运营方',
    englishDefinition: 'a person or company that runs a service, machine, or phone connection',
    noteEn: 'Meaning depends on whether the context is transport, telecom, or machines.',
    noteKo: '교통, 통신, 기계 문맥에 따라 의미가 달라집니다.',
    noteZh: '它在交通、电信和机器语境中的意思会不同。',
    exampleEn: 'The transit operator announced delays on the eastbound line.',
    exampleKo: '교통 운영사는 동쪽 방면 노선의 지연을 안내했습니다.',
    exampleZh: '交通运营方宣布东向线路出现延误。',
    collocations: ['system operator', 'transit operator', 'phone operator'],
  }),
  makeEntry({
    id: 'outstanding',
    word: 'outstanding',
    usIpa: '/aʊtˈstændɪŋ/',
    ukIpa: '/aʊtˈstændɪŋ/',
    importance: 4,
    topics: ['shopping-banking', 'work-school'],
    ko: '미결제의; 남아 있는; 뛰어난',
    zh: '未结清的；未完成的；杰出的',
    englishDefinition: 'still unpaid or unfinished, or extremely good depending on context',
    noteEn: 'A tricky multi-meaning word. In CELPIP it often means unpaid or remaining.',
    noteKo: '의미가 여러 개인 단어지만 CELPIP에서는 미결제·남아 있는 뜻이 자주 나옵니다.',
    noteZh: '这是多义词，但在 CELPIP 中常表示未结清或尚未完成。',
    exampleEn: 'You still have an outstanding balance of forty-two dollars.',
    exampleKo: '아직 42달러의 미결제 금액이 남아 있습니다.',
    exampleZh: '你仍有42美元的未结余额。',
    collocations: ['outstanding balance', 'outstanding issue', 'outstanding payment'],
  }),
  makeEntry({
    id: 'overlap',
    word: 'overlap',
    usIpa: '/ˌoʊvərˈlæp/',
    ukIpa: '/ˌəʊvəˈlæp/',
    importance: 3,
    topics: ['work-school', 'travel-transit'],
    ko: '겹치다; 중복되다',
    zh: '重叠；冲突',
    englishDefinition: 'to happen at the same time or cover the same area',
    noteEn: 'Very useful when schedules or duties conflict.',
    noteKo: '일정이나 업무가 겹칠 때 매우 유용합니다.',
    noteZh: '当时间安排或职责冲突时非常有用。',
    exampleEn: 'The two workshops overlap, so students can attend only one.',
    exampleKo: '두 워크숍 시간이 겹쳐서 학생들은 하나만 참석할 수 있습니다.',
    exampleZh: '两个工作坊时间重叠，所以学生只能参加一个。',
    collocations: ['time overlap', 'overlap slightly', 'schedules overlap'],
  }),
  makeEntry({
    id: 'participant',
    word: 'participant',
    usIpa: '/pɑːrˈtɪsəpənt/',
    ukIpa: '/pɑːˈtɪsɪpənt/',
    importance: 4,
    topics: ['work-school', 'community-civic'],
    ko: '참가자',
    zh: '参与者',
    englishDefinition: 'a person who takes part in an activity, event, or study',
    noteEn: 'Very common in workshop, program, and survey contexts.',
    noteKo: '워크숍, 프로그램, 설문 문맥에서 매우 자주 나옵니다.',
    noteZh: '在工作坊、项目和调查语境中非常常见。',
    exampleEn: 'All participants must sign in before entering the session.',
    exampleKo: '모든 참가자는 세션 입장 전에 출석 등록을 해야 합니다.',
    exampleZh: '所有参与者在进入活动前都必须签到。',
    collocations: ['program participant', 'survey participant', 'eligible participant'],
  }),
  makeEntry({
    id: 'pedestrian',
    word: 'pedestrian',
    usIpa: '/pəˈdestriən/',
    ukIpa: '/pəˈdestriən/',
    importance: 3,
    topics: ['travel-transit', 'community-civic'],
    ko: '보행자',
    zh: '行人',
    englishDefinition: 'a person who is walking, especially near roads or traffic',
    noteEn: 'Useful in road safety, directions, and city policy topics.',
    noteKo: '도로 안전, 길 안내, 도시 정책 주제에서 유용합니다.',
    noteZh: '在道路安全、路线说明和城市政策主题中很有用。',
    exampleEn: 'The city added more lighting to improve pedestrian safety.',
    exampleKo: '시는 보행자 안전을 높이기 위해 조명을 추가했습니다.',
    exampleZh: '城市增加了更多照明来提升行人安全。',
    collocations: ['pedestrian crossing', 'pedestrian safety', 'pedestrian area'],
  }),
  makeEntry({
    id: 'pharmacy',
    word: 'pharmacy',
    usIpa: '/ˈfɑːrməsi/',
    ukIpa: '/ˈfɑːməsi/',
    importance: 4,
    topics: ['health-emergency'],
    ko: '약국',
    zh: '药房；药店',
    englishDefinition: 'a place where medicine is prepared and sold',
    noteEn: 'A core health-services word for prescriptions and refill tasks.',
    noteKo: '처방전과 약 재구매 문제에 중요한 보건 서비스 단어입니다.',
    noteZh: '这是处方和续药任务中的核心医疗服务词。',
    exampleEn: 'The pharmacy closes at six, so pick up the medication early.',
    exampleKo: '약국은 6시에 닫으니 약을 일찍 받아 가세요.',
    exampleZh: '药房六点关门，所以请早点取药。',
    collocations: ['local pharmacy', 'pharmacy counter', 'pharmacy hours'],
  }),
  makeEntry({
    id: 'placement',
    word: 'placement',
    usIpa: '/ˈpleɪsmənt/',
    ukIpa: '/ˈpleɪsmənt/',
    importance: 3,
    topics: ['work-school'],
    ko: '배치; 배정; 실습 배정',
    zh: '安置；分配；实习安排',
    englishDefinition: 'the act of putting someone in a job, class, or position',
    noteEn: 'Useful for internships, class-level decisions, and staffing.',
    noteKo: '인턴십, 반 배정, 인력 배치 문맥에서 유용합니다.',
    noteZh: '在实习、分班和人员安排语境中很有用。',
    exampleEn: 'The placement test will help determine your class level.',
    exampleKo: '반 배정 시험이 당신의 수업 수준을 결정하는 데 도움이 됩니다.',
    exampleZh: '分级考试将帮助确定你的班级水平。',
    collocations: ['job placement', 'placement test', 'clinical placement'],
  }),
  makeEntry({
    id: 'portion',
    word: 'portion',
    usIpa: '/ˈpɔːrʃən/',
    ukIpa: '/ˈpɔːʃən/',
    importance: 3,
    topics: ['shopping-banking', 'health-emergency', 'work-school'],
    ko: '부분; 1인분',
    zh: '部分；份量',
    englishDefinition: 'a part of something, or an amount of food for one person',
    noteEn: 'Context matters: it can mean a section, a share, or a serving.',
    noteKo: '문맥에 따라 일부, 몫, 1인분을 뜻할 수 있습니다.',
    noteZh: '它在不同语境中可表示部分、份额或一份食物。',
    exampleEn: 'Only a small portion of the fee is refundable.',
    exampleKo: '수수료의 일부만 환불 가능합니다.',
    exampleZh: '只有一小部分费用可以退款。',
    collocations: ['small portion', 'a portion of the cost', 'portion size'],
  }),
  makeEntry({
    id: 'precaution',
    word: 'precaution',
    usIpa: '/prɪˈkɔːʃən/',
    ukIpa: '/prɪˈkɔːʃən/',
    importance: 4,
    topics: ['health-emergency', 'community-civic'],
    ko: '예방 조치; 주의 사항',
    zh: '预防措施；注意事项',
    englishDefinition: 'an action taken in advance to prevent danger or problems',
    noteEn: 'Useful for health notices, safety announcements, and procedures.',
    noteKo: '건강 공지, 안전 방송, 절차 안내에서 유용합니다.',
    noteZh: '在健康通知、安全广播和流程说明中很有用。',
    exampleEn: 'As a precaution, residents should boil the water before drinking it.',
    exampleKo: '예방 조치로 주민들은 물을 마시기 전에 끓여야 합니다.',
    exampleZh: '作为预防措施，居民在饮用前应先把水烧开。',
    collocations: ['take precautions', 'safety precaution', 'as a precaution'],
  }),
  makeEntry({
    id: 'process',
    word: 'process',
    usIpa: '/ˈprɑːses/',
    ukIpa: '/ˈprəʊses/',
    importance: 5,
    topics: ['work-school', 'community-civic', 'shopping-banking'],
    ko: '절차; 처리하다',
    zh: '流程；处理',
    englishDefinition: 'a series of steps taken to complete something, or the act of handling it',
    noteEn: 'A very high-frequency CELPIP word across nearly every section.',
    noteKo: '거의 모든 영역에서 자주 나오는 셀핍 핵심 단어입니다.',
    noteZh: '这是几乎所有板块都会出现的 CELPIP 高频核心词。',
    exampleEn: 'The refund process usually takes seven to ten business days.',
    exampleKo: '환불 절차는 보통 영업일 기준 7일에서 10일이 걸립니다.',
    exampleZh: '退款流程通常需要七到十个工作日。',
    collocations: ['application process', 'processing time', 'process a refund'],
  }),
  makeEntry({
    id: 'proficiency',
    word: 'proficiency',
    usIpa: '/prəˈfɪʃənsi/',
    ukIpa: '/prəˈfɪʃənsi/',
    importance: 3,
    topics: ['work-school'],
    ko: '숙련도; 능숙함',
    zh: '熟练程度',
    englishDefinition: 'a high level of skill or ability in something',
    noteEn: 'Common in language, software, and job-qualification contexts.',
    noteKo: '어학, 소프트웨어, 직무 자격 문맥에서 자주 보입니다.',
    noteZh: '常见于语言、软件和工作资格语境中。',
    exampleEn: 'Applicants must show proficiency in written and spoken English.',
    exampleKo: '지원자는 영어 읽기와 말하기 숙련도를 보여야 합니다.',
    exampleZh: '申请者必须证明自己具备英语书写和口语能力。',
    collocations: ['language proficiency', 'computer proficiency', 'demonstrate proficiency'],
  }),
  makeEntry({
    id: 'prohibit',
    word: 'prohibit',
    usIpa: '/prəˈhɪbɪt/',
    ukIpa: '/prəˈhɪbɪt/',
    importance: 4,
    topics: ['community-civic', 'housing-services'],
    ko: '금지하다',
    zh: '禁止',
    englishDefinition: 'to officially not allow something',
    noteEn: 'A strong rule word that often appears in signs and policies.',
    noteKo: '표지판과 정책에서 자주 나오는 강한 규정 단어입니다.',
    noteZh: '这是标志和政策中常见的强规则词。',
    exampleEn: 'The building rules prohibit leaving bikes in the hallway.',
    exampleKo: '건물 규정은 복도에 자전거를 두는 것을 금지합니다.',
    exampleZh: '大楼规定禁止把自行车放在走廊里。',
    collocations: ['strictly prohibit', 'prohibit smoking', 'prohibit visitors'],
  }),
  makeEntry({
    id: 'property-manager',
    word: 'property manager',
    usIpa: '/ˈprɑːpərti ˌmænɪdʒər/',
    ukIpa: '/ˈprɒpəti ˌmænɪdʒə/',
    importance: 4,
    topics: ['housing-services'],
    ko: '건물 관리자; 부동산 관리자',
    zh: '物业经理',
    englishDefinition: 'the person responsible for managing a building or rental property',
    noteEn: 'Useful in apartment complaints, repairs, and lease questions.',
    noteKo: '아파트 민원, 수리, 임대 계약 문제에서 유용합니다.',
    noteZh: '在公寓投诉、维修和租约问题中很有用。',
    exampleEn: 'The property manager asked residents to submit repair requests online.',
    exampleKo: '건물 관리자는 주민들에게 수리 요청을 온라인으로 제출하라고 했습니다.',
    exampleZh: '物业经理要求住户在线提交维修申请。',
    collocations: ['property manager office', 'contact the manager', 'property management'],
  }),
  makeEntry({
    id: 'protective',
    word: 'protective',
    usIpa: '/prəˈtektɪv/',
    ukIpa: '/prəˈtektɪv/',
    importance: 3,
    topics: ['health-emergency', 'work-school'],
    ko: '보호용의; 보호하는',
    zh: '防护的；保护性的',
    englishDefinition: 'used to keep someone safe from harm',
    noteEn: 'Useful in safety instructions and workplace training.',
    noteKo: '안전 지침과 직장 교육에서 유용합니다.',
    noteZh: '在安全说明和职场培训中很有用。',
    exampleEn: 'Lab staff must wear protective gloves at all times.',
    exampleKo: '실험실 직원은 항상 보호 장갑을 착용해야 합니다.',
    exampleZh: '实验室工作人员必须始终佩戴防护手套。',
    collocations: ['protective gear', 'protective gloves', 'protective layer'],
  }),
  makeEntry({
    id: 'punctual',
    word: 'punctual',
    usIpa: '/ˈpʌŋktʃuəl/',
    ukIpa: '/ˈpʌŋktʃuəl/',
    importance: 3,
    topics: ['work-school', 'travel-transit'],
    ko: '시간을 잘 지키는',
    zh: '守时的',
    englishDefinition: 'arriving or happening at the expected time',
    noteEn: 'Useful in work expectations and transport-performance topics.',
    noteKo: '직장 기대치와 교통 성능 주제에서 유용합니다.',
    noteZh: '在工作要求和交通表现主题中很有用。',
    exampleEn: 'The employer emphasized the need for punctual staff.',
    exampleKo: '고용주는 시간을 잘 지키는 직원의 필요성을 강조했습니다.',
    exampleZh: '雇主强调需要守时的员工。',
    collocations: ['be punctual', 'punctual service', 'punctual employee'],
  }),
  makeEntry({
    id: 'reassure',
    word: 'reassure',
    usIpa: '/ˌriːəˈʃʊr/',
    ukIpa: '/ˌriːəˈʃɔː/',
    importance: 3,
    topics: ['people-relationships', 'health-emergency', 'problem-solving'],
    ko: '안심시키다',
    zh: '使安心；安慰',
    englishDefinition: 'to make someone feel less worried',
    noteEn: 'Very useful in support-based speaking and daily-life listening tasks.',
    noteKo: '도움 주기 말하기와 일상 듣기에서 매우 유용합니다.',
    noteZh: '在支持类口语和日常听力中非常有用。',
    exampleEn: 'The nurse reassured the patient that the delay was not serious.',
    exampleKo: '간호사는 환자에게 그 지연이 심각한 문제는 아니라고 안심시켰습니다.',
    exampleZh: '护士安慰病人说，这次延误并不严重。',
    collocations: ['reassure someone', 'reassuring tone', 'offer reassurance'],
  }),
  makeEntry({
    id: 'reimbursement',
    word: 'reimbursement',
    usIpa: '/ˌriːɪmˈbɝːsmənt/',
    ukIpa: '/ˌriːɪmˈbɜːsmənt/',
    importance: 4,
    topics: ['shopping-banking', 'work-school'],
    ko: '환급; 상환',
    zh: '报销；补偿',
    englishDefinition: 'money paid back to someone for expenses they already paid',
    noteEn: 'Common in work expenses, insurance, and refund-related tasks.',
    noteKo: '업무 비용, 보험, 환급 문제에서 자주 나옵니다.',
    noteZh: '常见于工作费用、保险和退款任务中。',
    exampleEn: 'Reimbursement requests must include receipts and the original invoice.',
    exampleKo: '환급 요청에는 영수증과 원본 송장이 포함되어야 합니다.',
    exampleZh: '报销申请必须附上收据和原始发票。',
    collocations: ['travel reimbursement', 'request reimbursement', 'reimbursement form'],
  }),
  makeEntry({
    id: 'relocate',
    word: 'relocate',
    usIpa: '/ˌriːloʊˈkeɪt/',
    ukIpa: '/ˌriːləʊˈkeɪt/',
    importance: 4,
    topics: ['work-school', 'housing-services'],
    ko: '이전하다; 이사하다',
    zh: '搬迁；调动',
    englishDefinition: 'to move to a new place to live or work',
    noteEn: 'Useful in job, housing, and office-change contexts.',
    noteKo: '직장, 주거, 사무실 이전 문맥에서 유용합니다.',
    noteZh: '在工作、住房和办公室搬迁语境中很有用。',
    exampleEn: 'The company plans to relocate the office next spring.',
    exampleKo: '회사는 내년 봄에 사무실을 이전할 계획입니다.',
    exampleZh: '公司计划在明年春天搬迁办公室。',
    collocations: ['relocate the office', 'relocate staff', 'relocate to another city'],
  }),
  makeEntry({
    id: 'renewal',
    word: 'renewal',
    usIpa: '/rɪˈnuːəl/',
    ukIpa: '/rɪˈnjuːəl/',
    importance: 5,
    topics: ['housing-services', 'community-civic', 'shopping-banking'],
    ko: '갱신',
    zh: '续签；续期',
    englishDefinition: 'the act of continuing something for another period',
    noteEn: 'A high-frequency CELPIP word for permits, memberships, and leases.',
    noteKo: '허가증, 멤버십, 임대 계약 갱신에서 자주 나오는 셀핍 단어입니다.',
    noteZh: '这是许可证、会员资格和租约续期中的 CELPIP 高频词。',
    exampleEn: 'Permit renewal applications are due by the end of the month.',
    exampleKo: '허가증 갱신 신청은 이달 말까지 제출해야 합니다.',
    exampleZh: '许可证续期申请必须在本月底前提交。',
    collocations: ['renewal notice', 'lease renewal', 'membership renewal'],
  }),
  makeEntry({
    id: 'representative',
    word: 'representative',
    usIpa: '/ˌreprɪˈzentətɪv/',
    ukIpa: '/ˌreprɪˈzentətɪv/',
    importance: 4,
    topics: ['shopping-banking', 'technology-communication', 'community-civic'],
    ko: '대표; 상담원',
    zh: '代表；客服人员',
    englishDefinition: 'a person who speaks or acts for a company, group, or office',
    noteEn: 'Often appears in customer-service calls and public office communication.',
    noteKo: '고객 서비스 전화와 공공 기관 소통에서 자주 나옵니다.',
    noteZh: '常见于客服通话和公共机构沟通中。',
    exampleEn: 'A representative will call you back within one business day.',
    exampleKo: '상담원이 영업일 기준 하루 안에 다시 연락드릴 것입니다.',
    exampleZh: '一位代表将在一个工作日内回电给你。',
    collocations: ['customer-service representative', 'union representative', 'speak to a representative'],
  }),
  makeEntry({
    id: 'residence',
    word: 'residence',
    usIpa: '/ˈrezɪdəns/',
    ukIpa: '/ˈrezɪdəns/',
    importance: 4,
    topics: ['housing-services', 'work-school'],
    ko: '거주지; 기숙사',
    zh: '住所；宿舍',
    englishDefinition: 'the place where someone lives, or a student housing building',
    noteEn: 'Useful for address proof, dorm notices, and campus living tasks.',
    noteKo: '주소 증빙, 기숙사 공지, 캠퍼스 생활 문제에서 유용합니다.',
    noteZh: '在地址证明、宿舍通知和校园生活任务中很有用。',
    exampleEn: 'Students in residence must register their guests in advance.',
    exampleKo: '기숙사에 사는 학생들은 방문객을 미리 등록해야 합니다.',
    exampleZh: '住在宿舍的学生必须提前登记访客。',
    collocations: ['place of residence', 'student residence', 'proof of residence'],
  }),
  makeEntry({
    id: 'revised',
    word: 'revised',
    usIpa: '/rɪˈvaɪzd/',
    ukIpa: '/rɪˈvaɪzd/',
    importance: 3,
    topics: ['work-school', 'travel-transit', 'community-civic'],
    ko: '수정된; 개정된',
    zh: '修订后的；更新后的',
    englishDefinition: 'changed or corrected to improve or update something',
    noteEn: 'Useful in schedules, forms, and policy updates.',
    noteKo: '일정, 양식, 정책 업데이트에서 유용합니다.',
    noteZh: '在时间表、表格和政策更新中很有用。',
    exampleEn: 'Please read the revised schedule before planning your visit.',
    exampleKo: '방문 계획 전에 수정된 일정을 읽어 주세요.',
    exampleZh: '请在安排行程前阅读更新后的时间表。',
    collocations: ['revised version', 'revised policy', 'revised schedule'],
  }),
  makeEntry({
    id: 'route',
    word: 'route',
    usIpa: '/ruːt/',
    ukIpa: '/ruːt/',
    importance: 4,
    topics: ['travel-transit', 'community-civic'],
    ko: '노선; 경로',
    zh: '路线；线路',
    englishDefinition: 'the path or line taken to travel from one place to another',
    noteEn: 'A key transit word in direction and service-change questions.',
    noteKo: '길 안내와 서비스 변경 문제의 핵심 교통 단어입니다.',
    noteZh: '这是路线说明和服务变更题中的关键交通词。',
    exampleEn: 'Bus route 12 is being diverted because of road construction.',
    exampleKo: '도로 공사로 인해 12번 버스 노선이 우회 운행됩니다.',
    exampleZh: '由于道路施工，12路公交线路正在绕行。',
    collocations: ['bus route', 'alternate route', 'route map'],
  }),
  makeEntry({
    id: 'seating',
    word: 'seating',
    usIpa: '/ˈsiːtɪŋ/',
    ukIpa: '/ˈsiːtɪŋ/',
    importance: 3,
    topics: ['travel-transit', 'community-civic', 'work-school'],
    ko: '좌석 배치; 좌석',
    zh: '座位安排；座位',
    englishDefinition: 'the seats available or the arrangement of those seats',
    noteEn: 'Useful for events, classrooms, and transportation announcements.',
    noteKo: '행사, 교실, 교통 안내에서 유용합니다.',
    noteZh: '在活动、教室和交通通知中很有用。',
    exampleEn: 'Seating is limited, so please arrive a few minutes early.',
    exampleKo: '좌석이 한정되어 있으니 몇 분 일찍 도착해 주세요.',
    exampleZh: '座位有限，请提前几分钟到达。',
    collocations: ['assigned seating', 'limited seating', 'seating arrangement'],
  }),
  makeEntry({
    id: 'signature',
    word: 'signature',
    usIpa: '/ˈsɪɡnətʃər/',
    ukIpa: '/ˈsɪɡnətʃə/',
    importance: 4,
    topics: ['work-school', 'shopping-banking', 'community-civic'],
    ko: '서명',
    zh: '签名',
    englishDefinition: 'your written name used to approve or confirm something',
    noteEn: 'A must-know document word for applications, banking, and permits.',
    noteKo: '신청서, 은행, 허가증 문제에서 꼭 알아야 할 서류 단어입니다.',
    noteZh: '这是申请、银行和许可证题中必须掌握的文件词。',
    exampleEn: 'The form is invalid without your signature on the last page.',
    exampleKo: '마지막 페이지에 서명이 없으면 그 양식은 무효입니다.',
    exampleZh: '如果最后一页没有你的签名，这份表格就是无效的。',
    collocations: ['digital signature', 'signature line', 'require a signature'],
  }),
  makeEntry({
    id: 'stability',
    word: 'stability',
    usIpa: '/stəˈbɪləti/',
    ukIpa: '/stəˈbɪləti/',
    importance: 3,
    topics: ['news-opinion', 'shopping-banking', 'people-relationships'],
    ko: '안정성',
    zh: '稳定性',
    englishDefinition: 'the state of being steady, secure, or not changing suddenly',
    noteEn: 'Useful in finance, housing, and family decision questions.',
    noteKo: '재정, 주거, 가족 의사결정 문제에서 유용합니다.',
    noteZh: '在财务、住房和家庭决策题中很有用。',
    exampleEn: 'She chose the position because it offers more long-term stability.',
    exampleKo: '그녀는 장기적인 안정성이 더 높아서 그 자리를 선택했습니다.',
    exampleZh: '她选择这个职位是因为它能提供更长期的稳定性。',
    collocations: ['financial stability', 'job stability', 'network stability'],
  }),
  makeEntry({
    id: 'statement',
    word: 'statement',
    usIpa: '/ˈsteɪtmənt/',
    ukIpa: '/ˈsteɪtmənt/',
    importance: 4,
    topics: ['shopping-banking', 'news-opinion', 'community-civic'],
    ko: '진술; 명세서; 성명',
    zh: '陈述；对账单；声明',
    englishDefinition: 'something that is said or written officially, or a written record such as a bank statement',
    noteEn: 'Another context-dependent CELPIP word worth learning well.',
    noteKo: '문맥 의존도가 높은 셀핍 단어라 잘 익혀 두면 좋습니다.',
    noteZh: '这是一个高度依赖语境的 CELPIP 单词，值得重点掌握。',
    exampleEn: 'Please review the monthly statement for any unfamiliar charges.',
    exampleKo: '월별 명세서에서 익숙하지 않은 청구 내역이 없는지 확인해 주세요.',
    exampleZh: '请查看月度对账单，确认是否有不熟悉的收费。',
    collocations: ['bank statement', 'official statement', 'written statement'],
  }),
  makeEntry({
    id: 'storage',
    word: 'storage',
    usIpa: '/ˈstɔːrɪdʒ/',
    ukIpa: '/ˈstɔːrɪdʒ/',
    importance: 3,
    topics: ['housing-services', 'technology-communication', 'travel-transit'],
    ko: '보관; 저장 공간',
    zh: '存储；储物空间',
    englishDefinition: 'the space or method used to keep things safely for later use',
    noteEn: 'Useful for apartments, devices, and travel baggage situations.',
    noteKo: '아파트, 기기, 여행 짐 상황에서 유용합니다.',
    noteZh: '在公寓、设备和旅行行李情境中很有用。',
    exampleEn: 'Extra storage is available in the basement for an additional fee.',
    exampleKo: '추가 요금을 내면 지하실 추가 보관 공간을 이용할 수 있습니다.',
    exampleZh: '支付额外费用即可使用地下室的附加储物空间。',
    collocations: ['storage room', 'cloud storage', 'storage fee'],
  }),
  makeEntry({
    id: 'supervision',
    word: 'supervision',
    usIpa: '/ˌsuːpərˈvɪʒən/',
    ukIpa: '/ˌsuːpəˈvɪʒən/',
    importance: 3,
    topics: ['work-school', 'people-relationships'],
    ko: '감독; 관리',
    zh: '监督；监管',
    englishDefinition: 'the act of watching over people or activities to make sure things are done correctly',
    noteEn: 'Useful in childcare, training, and workplace safety contexts.',
    noteKo: '보육, 교육, 직장 안전 문맥에서 유용합니다.',
    noteZh: '在托儿、培训和职场安全语境中很有用。',
    exampleEn: 'Students must work under supervision in the science lab.',
    exampleKo: '학생들은 과학 실험실에서 감독하에 작업해야 합니다.',
    exampleZh: '学生必须在监督下在科学实验室工作。',
    collocations: ['under supervision', 'close supervision', 'adult supervision'],
  }),
  makeEntry({
    id: 'surcharge',
    word: 'surcharge',
    usIpa: '/ˈsɝːˌtʃɑːrdʒ/',
    ukIpa: '/ˈsɜːtʃɑːdʒ/',
    importance: 4,
    topics: ['shopping-banking', 'travel-transit'],
    ko: '추가 요금',
    zh: '附加费',
    englishDefinition: 'an extra amount charged on top of the usual cost',
    noteEn: 'Common in airline, booking, and payment processing situations.',
    noteKo: '항공, 예약, 결제 처리 상황에서 자주 나옵니다.',
    noteZh: '常见于航空、预订和付款处理情境中。',
    exampleEn: 'A weekend surcharge applies to all airport shuttle bookings.',
    exampleKo: '주말에는 모든 공항 셔틀 예약에 추가 요금이 적용됩니다.',
    exampleZh: '周末所有机场接驳车预订都要加收附加费。',
    collocations: ['service surcharge', 'fuel surcharge', 'extra surcharge'],
  }),
  makeEntry({
    id: 'temporary',
    word: 'temporary',
    usIpa: '/ˈtempəˌreri/',
    ukIpa: '/ˈtempərəri/',
    importance: 4,
    topics: ['housing-services', 'work-school', 'technology-communication'],
    ko: '임시의',
    zh: '临时的',
    englishDefinition: 'lasting for a short period and not permanent',
    noteEn: 'Useful in outages, closures, relocations, and staffing.',
    noteKo: '정전, 폐쇄, 이전, 인력 배치 문맥에서 유용합니다.',
    noteZh: '在停电、关闭、搬迁和人手安排语境中很有用。',
    exampleEn: 'The library entrance is temporarily closed for repairs.',
    exampleKo: '도서관 입구는 수리로 인해 임시 폐쇄되었습니다.',
    exampleZh: '图书馆入口因维修而暂时关闭。',
    collocations: ['temporary closure', 'temporary password', 'temporary location'],
  }),
  makeEntry({
    id: 'terminate',
    word: 'terminate',
    usIpa: '/ˈtɝːməˌneɪt/',
    ukIpa: '/ˈtɜːmɪneɪt/',
    importance: 4,
    topics: ['housing-services', 'technology-communication', 'work-school'],
    ko: '종료하다; 해지하다',
    zh: '终止；结束；解除',
    englishDefinition: 'to end something officially',
    noteEn: 'Useful for contracts, memberships, and account cancellations.',
    noteKo: '계약, 멤버십, 계정 해지 문맥에서 유용합니다.',
    noteZh: '在合同、会员资格和账户取消语境中很有用。',
    exampleEn: 'You must give written notice to terminate the agreement early.',
    exampleKo: '계약을 조기 해지하려면 서면 통지를 해야 합니다.',
    exampleZh: '若要提前终止协议，你必须提交书面通知。',
    collocations: ['terminate a contract', 'terminate service', 'early termination'],
  }),
  makeEntry({
    id: 'threshold',
    word: 'threshold',
    usIpa: '/ˈθreʃˌhoʊld/',
    ukIpa: '/ˈθreʃhəʊld/',
    importance: 3,
    topics: ['shopping-banking', 'news-opinion', 'community-civic'],
    ko: '기준점; 문턱',
    zh: '门槛；阈值',
    englishDefinition: 'the level or point at which something starts to happen',
    noteEn: 'Useful in benefits, taxes, income, and policy explanations.',
    noteKo: '복지, 세금, 소득, 정책 설명에서 유용합니다.',
    noteZh: '在福利、税务、收入和政策说明中很有用。',
    exampleEn: 'Households below the income threshold may qualify for assistance.',
    exampleKo: '소득 기준 이하 가구는 지원 자격이 있을 수 있습니다.',
    exampleZh: '收入低于门槛的家庭可能有资格获得援助。',
    collocations: ['income threshold', 'threshold level', 'meet the threshold'],
  }),
  makeEntry({
    id: 'ticket-counter',
    word: 'ticket counter',
    usIpa: '/ˈtɪkɪt ˌkaʊntər/',
    ukIpa: '/ˈtɪkɪt ˌkaʊntə/',
    importance: 3,
    topics: ['travel-transit'],
    ko: '매표소',
    zh: '售票柜台',
    englishDefinition: 'the desk where tickets are sold or travel problems are handled',
    noteEn: 'Useful in station and airport listening tasks.',
    noteKo: '역과 공항 듣기 문제에서 유용합니다.',
    noteZh: '在车站和机场听力题中很有用。',
    exampleEn: 'Please go to the ticket counter if your online booking failed.',
    exampleKo: '온라인 예약이 실패했으면 매표소로 가 주세요.',
    exampleZh: '如果你的线上预订失败，请前往售票柜台。',
    collocations: ['main ticket counter', 'ticket counter line', 'counter assistance'],
  }),
  makeEntry({
    id: 'timely',
    word: 'timely',
    usIpa: '/ˈtaɪmli/',
    ukIpa: '/ˈtaɪmli/',
    importance: 3,
    topics: ['work-school', 'problem-solving'],
    ko: '시기적절한; 제때의',
    zh: '及时的',
    englishDefinition: 'happening at the right time or without delay',
    noteEn: 'Useful when discussing responses, submissions, and service quality.',
    noteKo: '응답, 제출, 서비스 품질을 말할 때 유용합니다.',
    noteZh: '在谈到回复、提交和服务质量时很有用。',
    exampleEn: 'Timely communication could have prevented the misunderstanding.',
    exampleKo: '시기적절한 소통이 있었다면 오해를 막을 수 있었을 것입니다.',
    exampleZh: '及时沟通本可以避免这场误会。',
    collocations: ['timely response', 'timely submission', 'timely notice'],
  }),
  makeEntry({
    id: 'tolerance',
    word: 'tolerance',
    usIpa: '/ˈtɑːlərəns/',
    ukIpa: '/ˈtɒlərəns/',
    importance: 3,
    topics: ['health-emergency', 'people-relationships'],
    ko: '내성; 관용',
    zh: '耐受性；包容',
    englishDefinition: 'the ability to accept something or to handle it physically',
    noteEn: 'Context may be medicine, food, or attitude toward others.',
    noteKo: '약, 음식, 또는 타인에 대한 태도를 뜻할 수 있습니다.',
    noteZh: '它可指药物、食物耐受性，也可指对他人的包容。',
    exampleEn: 'Some patients have a low tolerance for this medication.',
    exampleKo: '일부 환자는 이 약에 대한 내성이 낮습니다.',
    exampleZh: '有些病人对这种药物的耐受性较低。',
    collocations: ['pain tolerance', 'low tolerance', 'build tolerance'],
  }),
  makeEntry({
    id: 'tuition',
    word: 'tuition',
    usIpa: '/tuˈɪʃən/',
    ukIpa: '/tjuˈɪʃən/',
    importance: 4,
    topics: ['work-school', 'shopping-banking'],
    ko: '수업료; 학비',
    zh: '学费',
    englishDefinition: 'the money paid for teaching or school classes',
    noteEn: 'Very common in college, payment-plan, and financial-aid tasks.',
    noteKo: '대학, 분할 납부, 재정 지원 문제에서 매우 자주 나옵니다.',
    noteZh: '在大学、分期付款和经济资助任务中非常常见。',
    exampleEn: 'Tuition must be paid before you can register for courses.',
    exampleKo: '과목 등록 전에 학비를 납부해야 합니다.',
    exampleZh: '你必须先缴学费，才能注册课程。',
    collocations: ['tuition fee', 'pay tuition', 'tuition deadline'],
  }),
  makeEntry({
    id: 'undergo',
    word: 'undergo',
    usIpa: '/ˌʌndərˈɡoʊ/',
    ukIpa: '/ˌʌndəˈɡəʊ/',
    importance: 3,
    topics: ['health-emergency', 'housing-services', 'technology-communication'],
    ko: '겪다; 받다',
    zh: '经历；接受',
    englishDefinition: 'to experience or go through a process, change, or treatment',
    noteEn: 'Useful in medical, repair, and improvement contexts.',
    noteKo: '의료, 수리, 개선 문맥에서 유용합니다.',
    noteZh: '在医疗、维修和改进语境中很有用。',
    exampleEn: 'The building will undergo major repairs during the summer.',
    exampleKo: '그 건물은 여름 동안 대규모 수리를 받게 됩니다.',
    exampleZh: '这栋楼将在夏季进行大规模维修。',
    collocations: ['undergo surgery', 'undergo repairs', 'undergo changes'],
  }),
  makeEntry({
    id: 'validate',
    word: 'validate',
    usIpa: '/ˈvæləˌdeɪt/',
    ukIpa: '/ˈvælɪdeɪt/',
    importance: 4,
    topics: ['technology-communication', 'travel-transit', 'shopping-banking'],
    ko: '확인하다; 인증하다; 유효화하다',
    zh: '验证；使有效',
    englishDefinition: 'to confirm that something is correct, official, or acceptable',
    noteEn: 'Useful for tickets, forms, payment cards, and account access.',
    noteKo: '티켓, 양식, 결제 카드, 계정 접근 문맥에서 유용합니다.',
    noteZh: '在票据、表格、支付卡和账户访问语境中很有用。',
    exampleEn: 'Passengers must validate their passes before boarding the train.',
    exampleKo: '승객은 기차에 탑승하기 전에 승차권을 인증해야 합니다.',
    exampleZh: '乘客在上车前必须验证车票。',
    collocations: ['validate a ticket', 'validate the form', 'validate payment'],
  }),
  makeEntry({
    id: 'variation',
    word: 'variation',
    usIpa: '/ˌveriˈeɪʃən/',
    ukIpa: '/ˌveəriˈeɪʃən/',
    importance: 3,
    topics: ['news-opinion', 'health-emergency', 'shopping-banking'],
    ko: '차이; 변동',
    zh: '变化；差异',
    englishDefinition: 'a difference or change from the usual amount, form, or level',
    noteEn: 'Useful in reports about prices, weather, and test performance.',
    noteKo: '가격, 날씨, 시험 성과 보고에서 유용합니다.',
    noteZh: '在价格、天气和考试表现报告中很有用。',
    exampleEn: 'There is a noticeable variation in prices across the city.',
    exampleKo: '도시 전역에서 가격 차이가 눈에 띄게 나타납니다.',
    exampleZh: '全市各地的价格差异很明显。',
    collocations: ['seasonal variation', 'variation in cost', 'slight variation'],
  }),
  makeEntry({
    id: 'verification',
    word: 'verification',
    usIpa: '/ˌverəfəˈkeɪʃən/',
    ukIpa: '/ˌverɪfɪˈkeɪʃən/',
    importance: 5,
    topics: ['shopping-banking', 'technology-communication', 'community-civic'],
    ko: '확인; 검증',
    zh: '验证；核实',
    englishDefinition: 'the process of checking that something is true or correct',
    noteEn: 'A very high-frequency process word in identity, address, and payment tasks.',
    noteKo: '신원, 주소, 결제 문제에 자주 나오는 절차 핵심 단어입니다.',
    noteZh: '这是身份、地址和支付任务中的高频流程词。',
    exampleEn: 'Address verification may take up to two business days.',
    exampleKo: '주소 확인에는 영업일 기준 최대 이틀이 걸릴 수 있습니다.',
    exampleZh: '地址验证可能需要最多两个工作日。',
    collocations: ['identity verification', 'verification email', 'manual verification'],
  }),
  makeEntry({
    id: 'waive',
    word: 'waive',
    usIpa: '/weɪv/',
    ukIpa: '/weɪv/',
    importance: 4,
    topics: ['shopping-banking', 'work-school', 'community-civic'],
    ko: '면제하다',
    zh: '免除；豁免',
    englishDefinition: 'to officially choose not to require a fee, rule, or right',
    noteEn: 'Important in fee-reduction, deadline, and hardship requests.',
    noteKo: '수수료 감면, 마감일, 곤란 사정 요청에서 중요합니다.',
    noteZh: '在费用减免、截止日期和困难申请中很重要。',
    exampleEn: 'The office may waive the late fee if you explain the situation.',
    exampleKo: '상황을 설명하면 사무실에서 연체료를 면제해 줄 수 있습니다.',
    exampleZh: '如果你解释情况，办公室可能会免除滞纳金。',
    collocations: ['waive a fee', 'waive the requirement', 'waive penalties'],
  }),
  makeEntry({
    id: 'waitlist',
    word: 'wait-list',
    usIpa: '/ˈweɪtˌlɪst/',
    ukIpa: '/ˈweɪtlɪst/',
    importance: 4,
    topics: ['work-school', 'housing-services', 'travel-transit'],
    ko: '대기자 명단',
    zh: '等候名单',
    englishDefinition: 'a list of people waiting for a place to become available',
    noteEn: 'Useful in course registration, housing, and reservation tasks.',
    noteKo: '수강 신청, 주거, 예약 문제에서 유용합니다.',
    noteZh: '在选课、住房和预订任务中很有用。',
    exampleEn: 'If the class is full, you can add your name to the wait-list.',
    exampleKo: '수업이 가득 찼으면 대기자 명단에 이름을 올릴 수 있습니다.',
    exampleZh: '如果课程已满，你可以把名字加入等候名单。',
    collocations: ['join the wait-list', 'wait-list position', 'wait-list spot'],
  }),
  makeEntry({
    id: 'welfare',
    word: 'welfare',
    usIpa: '/ˈwelfer/',
    ukIpa: '/ˈwelfeə/',
    importance: 3,
    topics: ['community-civic', 'people-relationships', 'news-opinion'],
    ko: '복지; 안녕',
    zh: '福利；福祉',
    englishDefinition: 'the health, safety, and well-being of a person or group',
    noteEn: 'Useful in social policy and care-related topics.',
    noteKo: '사회 정책과 돌봄 관련 주제에서 유용합니다.',
    noteZh: '在社会政策和照护相关主题中很有用。',
    exampleEn: 'The policy was introduced to improve child welfare in the region.',
    exampleKo: '그 정책은 지역 아동 복지를 향상시키기 위해 도입되었습니다.',
    exampleZh: '该政策的推出是为了改善该地区儿童福利。',
    collocations: ['public welfare', 'animal welfare', 'welfare program'],
  }),
  makeEntry({
    id: 'workspace',
    word: 'workspace',
    usIpa: '/ˈwɝːkˌspeɪs/',
    ukIpa: '/ˈwɜːkspeɪs/',
    importance: 3,
    topics: ['work-school', 'housing-services', 'technology-communication'],
    ko: '작업 공간',
    zh: '工作空间',
    englishDefinition: 'the area where someone works, physically or online',
    noteEn: 'Useful for office moves, remote work, and study-room arrangements.',
    noteKo: '사무실 이전, 재택근무, 학습 공간 배정에서 유용합니다.',
    noteZh: '在办公室搬迁、远程办公和学习空间安排中很有用。',
    exampleEn: 'Staff can reserve a quiet workspace for online meetings.',
    exampleKo: '직원은 온라인 회의를 위해 조용한 작업 공간을 예약할 수 있습니다.',
    exampleZh: '员工可以预订安静的工作空间来开线上会议。',
    collocations: ['shared workspace', 'workspace booking', 'quiet workspace'],
  }),
]
