import { CELPIP_VOCABULARY_EXTRA } from './celpipVocabularyExtraData.js'

export const CELPIP_VOCAB_TOPICS = [
  { id: 'housing-services', label: 'Housing & Services', shortLabel: 'Housing', emoji: '🏠', tone: 'Rent, repairs, bills, building rules' },
  { id: 'work-school', label: 'Work & School', shortLabel: 'Work', emoji: '💼', tone: 'Meetings, deadlines, tasks, learning' },
  { id: 'travel-transit', label: 'Travel & Transit', shortLabel: 'Travel', emoji: '🧳', tone: 'Directions, transport, booking, delays' },
  { id: 'health-emergency', label: 'Health & Emergency', shortLabel: 'Health', emoji: '🩺', tone: 'Symptoms, clinics, emergencies, care' },
  { id: 'shopping-banking', label: 'Shopping & Banking', shortLabel: 'Money', emoji: '💳', tone: 'Prices, refunds, fees, payments' },
  { id: 'technology-communication', label: 'Technology & Communication', shortLabel: 'Tech', emoji: '💻', tone: 'Devices, apps, internet, contact' },
  { id: 'community-civic', label: 'Community & Civic Life', shortLabel: 'Community', emoji: '🏛️', tone: 'Public services, events, rules, policies' },
  { id: 'news-opinion', label: 'News & Opinion', shortLabel: 'News', emoji: '🗞️', tone: 'Reports, trends, viewpoints, evidence' },
  { id: 'people-relationships', label: 'People & Relationships', shortLabel: 'People', emoji: '🤝', tone: 'Support, conflict, tone, social meaning' },
  { id: 'problem-solving', label: 'Problem Solving', shortLabel: 'Solutions', emoji: '🧩', tone: 'Complaints, options, fixes, next steps' },
]

const makeEntry = ({
  id,
  word,
  usIpa,
  ukIpa = usIpa,
  importance = 3,
  topics,
  ko,
  zh,
  englishDefinition,
  noteEn,
  noteKo,
  noteZh,
  exampleEn,
  exampleKo,
  exampleZh,
  collocations = [],
}) => ({
  id,
  word,
  usIpa,
  ukIpa,
  importance,
  topics,
  meaning: { en: englishDefinition, ko, zh },
  note: { en: noteEn, ko: noteKo, zh: noteZh },
  collocations,
  examples: [
    {
      en: exampleEn,
      ko: exampleKo,
      zh: exampleZh,
    },
  ],
})

export const CELPIP_VOCAB_IMPORTANCE_LABELS = {
  5: 'Essential',
  4: 'High-use',
  3: 'Useful',
}

const CELPIP_VOCABULARY_CORE = [
  makeEntry({
    id: 'accommodate',
    word: 'accommodate',
    usIpa: '/əˈkɑːməˌdeɪt/',
    ukIpa: '/əˈkɒmədeɪt/',
    importance: 4,
    topics: ['housing-services', 'community-civic'],
    ko: '수용하다; 편의를 제공하다',
    zh: '容纳；提供便利',
    englishDefinition: 'to provide enough space, help, or adjustment for someone or something',
    noteEn: 'Useful when talking about housing rules, accessibility, and service changes.',
    noteKo: '주거 규정, 접근성, 서비스 조정을 말할 때 자주 씁니다.',
    noteZh: '谈住房规定、无障碍或服务调整时很常用。',
    exampleEn: 'The building can accommodate residents who need wheelchair access.',
    exampleKo: '그 건물은 휠체어 접근이 필요한 입주민을 수용할 수 있습니다.',
    exampleZh: '这栋楼可以为需要轮椅通行的住户提供便利。',
    collocations: ['accommodate a request', 'accommodate residents', 'accommodate special needs'],
  }),
  makeEntry({
    id: 'appliance',
    word: 'appliance',
    usIpa: '/əˈplaɪəns/',
    ukIpa: '/əˈplaɪəns/',
    importance: 4,
    topics: ['housing-services'],
    ko: '가전제품',
    zh: '家用电器',
    englishDefinition: 'a machine used in the home, such as a fridge or stove',
    noteEn: 'A common listening keyword in landlord, repair, and move-in conversations.',
    noteKo: '집주인, 수리, 입주 관련 대화에서 자주 들리는 핵심 단어입니다.',
    noteZh: '在房东、维修、入住类对话里经常出现。',
    exampleEn: 'The landlord said the broken appliance would be replaced next week.',
    exampleKo: '집주인은 고장 난 가전제품을 다음 주에 교체하겠다고 했습니다.',
    exampleZh: '房东说坏掉的家电会在下周更换。',
    collocations: ['kitchen appliance', 'broken appliance', 'major appliance'],
  }),
  makeEntry({
    id: 'lease',
    word: 'lease',
    usIpa: '/liːs/',
    ukIpa: '/liːs/',
    importance: 5,
    topics: ['housing-services'],
    ko: '임대 계약; 임대하다',
    zh: '租约；租赁',
    englishDefinition: 'a rental contract, or the act of renting property for a period of time',
    noteEn: 'Extremely common in CELPIP housing, documents, and proof-of-address tasks.',
    noteKo: 'CELPIP 주거, 서류, 주소 증빙 문제에서 매우 자주 나옵니다.',
    noteZh: '在 CELPIP 住房、文件、地址证明题里非常常见。',
    exampleEn: 'You need a copy of your lease to update the parking permit.',
    exampleKo: '주차 허가증을 갱신하려면 임대 계약서 사본이 필요합니다.',
    exampleZh: '更新停车许可证需要你的租约复印件。',
    collocations: ['sign a lease', 'lease agreement', 'renew a lease'],
  }),
  makeEntry({
    id: 'maintenance',
    word: 'maintenance',
    usIpa: '/ˈmeɪntənəns/',
    ukIpa: '/ˈmeɪntənəns/',
    importance: 5,
    topics: ['housing-services', 'technology-communication'],
    ko: '유지 보수',
    zh: '维护；保养',
    englishDefinition: 'work that keeps a building, machine, or system in good condition',
    noteEn: 'Often signals schedules, delays, access restrictions, or service notices.',
    noteKo: '일정, 지연, 출입 제한, 서비스 공지와 함께 자주 등장합니다.',
    noteZh: '常和时间安排、延迟、出入限制、服务通知一起出现。',
    exampleEn: 'Elevator maintenance will begin at 9 a.m. on Thursday.',
    exampleKo: '엘리베이터 유지 보수는 목요일 오전 9시에 시작됩니다.',
    exampleZh: '电梯维护将在周四上午9点开始。',
    collocations: ['routine maintenance', 'maintenance notice', 'maintenance crew'],
  }),
  makeEntry({
    id: 'residential',
    word: 'residential',
    usIpa: '/ˌrezɪˈdenʃəl/',
    ukIpa: '/ˌrezɪˈdenʃəl/',
    importance: 4,
    topics: ['housing-services', 'community-civic'],
    ko: '주거용의',
    zh: '住宅的',
    englishDefinition: 'connected with homes or places where people live',
    noteEn: 'Useful for permits, parking, zoning, and address-related notices.',
    noteKo: '허가증, 주차, 구역, 주소 관련 공지에서 유용합니다.',
    noteZh: '在许可证、停车、分区、地址通知中很常见。',
    exampleEn: 'This permit is only valid in the residential parking area.',
    exampleKo: '이 허가증은 주거용 주차 구역에서만 유효합니다.',
    exampleZh: '该许可证仅在住宅停车区有效。',
    collocations: ['residential area', 'residential permit', 'residential building'],
  }),
  makeEntry({
    id: 'utility-bill',
    word: 'utility bill',
    usIpa: '/juːˈtɪləti bɪl/',
    ukIpa: '/juːˈtɪləti bɪl/',
    importance: 5,
    topics: ['housing-services', 'shopping-banking'],
    ko: '공과금 청구서',
    zh: '水电煤账单',
    englishDefinition: 'a bill for services such as electricity, gas, or water',
    noteEn: 'A classic document word in address verification and account setup tasks.',
    noteKo: '주소 확인과 계정 개설 문제에서 자주 나오는 대표 서류 단어입니다.',
    noteZh: '在地址验证和账户开通任务里是典型文件词。',
    exampleEn: 'Please upload a recent utility bill showing your new address.',
    exampleKo: '새 주소가 보이는 최근 공과금 청구서를 업로드해 주세요.',
    exampleZh: '请上传一份显示新地址的近期水电煤账单。',
    collocations: ['recent utility bill', 'pay a utility bill', 'utility provider'],
  }),
  makeEntry({
    id: 'renovation',
    word: 'renovation',
    usIpa: '/ˌrenəˈveɪʃən/',
    ukIpa: '/ˌrenəˈveɪʃən/',
    importance: 4,
    topics: ['housing-services'],
    ko: '보수 공사; 개조',
    zh: '翻修；装修',
    englishDefinition: 'work done to improve or repair a building',
    noteEn: 'Often appears with timelines, noise warnings, and temporary inconvenience.',
    noteKo: '공사 일정, 소음 경고, 일시적 불편과 함께 자주 나옵니다.',
    noteZh: '常和工程时间、噪音提醒、暂时不便一起出现。',
    exampleEn: 'The renovation will continue for three weeks, so some areas will be closed.',
    exampleKo: '보수 공사는 3주 동안 계속되므로 일부 구역이 폐쇄됩니다.',
    exampleZh: '翻修将持续三周，因此部分区域会关闭。',
    collocations: ['major renovation', 'renovation project', 'during renovation'],
  }),
  makeEntry({
    id: 'notice',
    word: 'notice',
    usIpa: '/ˈnoʊtɪs/',
    ukIpa: '/ˈnəʊtɪs/',
    importance: 5,
    topics: ['housing-services', 'community-civic', 'work-school'],
    ko: '공지; 알림',
    zh: '通知；告示',
    englishDefinition: 'an official message that gives information or instructions',
    noteEn: 'CELPIP reading and listening often hide the main action inside a notice.',
    noteKo: 'CELPIP 읽기와 듣기에서는 공지문 속 행동 지시를 잡는 것이 중요합니다.',
    noteZh: '在 CELPIP 阅读和听力里，很多关键行动都藏在通知里。',
    exampleEn: 'The notice explains when the water will be turned off.',
    exampleKo: '그 공지문은 언제 단수가 되는지 설명합니다.',
    exampleZh: '这份通知说明了何时会停水。',
    collocations: ['public notice', 'advance notice', 'written notice'],
  }),
  makeEntry({
    id: 'deadline',
    word: 'deadline',
    usIpa: '/ˈdedlaɪn/',
    ukIpa: '/ˈdedlaɪn/',
    importance: 5,
    topics: ['work-school', 'housing-services', 'community-civic'],
    ko: '마감일',
    zh: '截止日期',
    englishDefinition: 'the latest time or date by which something must be done',
    noteEn: 'A top CELPIP keyword because questions often ask what must be done next.',
    noteKo: '다음에 무엇을 해야 하는지 묻는 문제가 많아 CELPIP에서 매우 중요합니다.',
    noteZh: '因为常常考“下一步该做什么”，所以是 CELPIP 高频关键词。',
    exampleEn: 'If you miss the deadline, your request may not be processed.',
    exampleKo: '마감일을 놓치면 요청이 처리되지 않을 수 있습니다.',
    exampleZh: '如果错过截止日期，你的申请可能不会被处理。',
    collocations: ['meet a deadline', 'deadline extension', 'strict deadline'],
  }),
  makeEntry({
    id: 'postpone',
    word: 'postpone',
    usIpa: '/poʊstˈpoʊn/',
    ukIpa: '/pəʊstˈpəʊn/',
    importance: 4,
    topics: ['work-school', 'travel-transit', 'community-civic'],
    ko: '연기하다',
    zh: '推迟',
    englishDefinition: 'to move an event or plan to a later time',
    noteEn: 'Important for schedule-change questions in listening and email tasks.',
    noteKo: '듣기와 이메일 문제의 일정 변경에서 중요한 단어입니다.',
    noteZh: '在听力和邮件任务的日程变更中很重要。',
    exampleEn: 'The workshop was postponed because the speaker was ill.',
    exampleKo: '발표자가 아파서 워크숍이 연기되었습니다.',
    exampleZh: '由于讲者生病，研讨会被推迟了。',
    collocations: ['postpone a meeting', 'postpone a decision', 'postpone the trip'],
  }),
  makeEntry({
    id: 'assignment',
    word: 'assignment',
    usIpa: '/əˈsaɪnmənt/',
    ukIpa: '/əˈsaɪnmənt/',
    importance: 4,
    topics: ['work-school'],
    ko: '과제; 업무 배정',
    zh: '作业；任务分配',
    englishDefinition: 'a task or piece of work given to someone',
    noteEn: 'Can refer to school work or a task assigned at work.',
    noteKo: '학교 과제일 수도 있고 직장에서 배정된 일일 수도 있습니다.',
    noteZh: '既可以指学校作业，也可以指工作分配的任务。',
    exampleEn: 'She finished the assignment before the class discussion.',
    exampleKo: '그녀는 수업 토론 전에 과제를 끝냈습니다.',
    exampleZh: '她在课堂讨论前完成了作业。',
    collocations: ['submit an assignment', 'group assignment', 'work assignment'],
  }),
  makeEntry({
    id: 'supervisor',
    word: 'supervisor',
    usIpa: '/ˈsuːpərvaɪzər/',
    ukIpa: '/ˈsuːpəvaɪzə/',
    importance: 4,
    topics: ['work-school'],
    ko: '상사; 감독자',
    zh: '主管；监督人',
    englishDefinition: 'a person who is in charge of other workers or students',
    noteEn: 'A frequent role word in workplace listening situations.',
    noteKo: '직장 상황 듣기에서 자주 들리는 역할 단어입니다.',
    noteZh: '在职场场景听力中经常出现的角色词。',
    exampleEn: 'You should inform your supervisor before changing your shift.',
    exampleKo: '근무 시간을 바꾸기 전에 상사에게 알려야 합니다.',
    exampleZh: '更改班次前你应该先通知主管。',
    collocations: ['direct supervisor', 'report to a supervisor', 'supervisor approval'],
  }),
  makeEntry({
    id: 'collaborate',
    word: 'collaborate',
    usIpa: '/kəˈlæbəˌreɪt/',
    ukIpa: '/kəˈlæbəreɪt/',
    importance: 4,
    topics: ['work-school', 'technology-communication'],
    ko: '협업하다',
    zh: '合作',
    englishDefinition: 'to work together with others to achieve something',
    noteEn: 'Good for describing teamwork in speaking and writing.',
    noteKo: '말하기와 쓰기에서 팀워크를 설명할 때 쓰기 좋습니다.',
    noteZh: '在口语和写作里描述团队合作时很好用。',
    exampleEn: 'Students will collaborate on the final presentation.',
    exampleKo: '학생들은 기말 발표를 함께 준비할 것입니다.',
    exampleZh: '学生们将合作完成期末展示。',
    collocations: ['collaborate closely', 'collaborate on a project', 'collaborate with colleagues'],
  }),
  makeEntry({
    id: 'schedule',
    word: 'schedule',
    usIpa: '/ˈskedʒuːl/',
    ukIpa: '/ˈʃedjuːl/',
    importance: 5,
    topics: ['work-school', 'travel-transit', 'people-relationships'],
    ko: '일정; 일정을 잡다',
    zh: '日程；安排',
    englishDefinition: 'a plan of times or activities, or the act of arranging one',
    noteEn: 'One of the most common CELPIP everyday-life words.',
    noteKo: 'CELPIP 일상생활 문제에서 가장 자주 나오는 단어 중 하나입니다.',
    noteZh: '是 CELPIP 日常生活任务里最常见的词之一。',
    exampleEn: 'The manager adjusted the schedule to cover the busy weekend.',
    exampleKo: '매니저는 바쁜 주말을 대비해 일정을 조정했습니다.',
    exampleZh: '经理调整了日程以应对繁忙的周末。',
    collocations: ['change the schedule', 'tight schedule', 'class schedule'],
  }),
  makeEntry({
    id: 'submit',
    word: 'submit',
    usIpa: '/səbˈmɪt/',
    ukIpa: '/səbˈmɪt/',
    importance: 5,
    topics: ['work-school', 'community-civic', 'housing-services'],
    ko: '제출하다',
    zh: '提交',
    englishDefinition: 'to formally give a document, form, or piece of work',
    noteEn: 'A must-know verb for applications, forms, and assignments.',
    noteKo: '신청서, 양식, 과제와 함께 꼭 알아야 할 동사입니다.',
    noteZh: '在申请、表格、作业里必须掌握。',
    exampleEn: 'Please submit the form by Friday afternoon.',
    exampleKo: '금요일 오후까지 양식을 제출해 주세요.',
    exampleZh: '请在周五下午前提交表格。',
    collocations: ['submit a form', 'submit an application', 'submit on time'],
  }),
  makeEntry({
    id: 'attendance',
    word: 'attendance',
    usIpa: '/əˈtendəns/',
    ukIpa: '/əˈtendəns/',
    importance: 3,
    topics: ['work-school', 'community-civic'],
    ko: '출석; 참석',
    zh: '出勤；出席',
    englishDefinition: 'the fact of being present at an event, class, or workplace',
    noteEn: 'Useful when describing policy, participation, or requirements.',
    noteKo: '규정, 참여, 의무를 설명할 때 유용합니다.',
    noteZh: '在说明政策、参与或要求时很有用。',
    exampleEn: 'Attendance is mandatory for the orientation session.',
    exampleKo: '오리엔테이션 세션에는 반드시 참석해야 합니다.',
    exampleZh: '说明会必须出席。',
    collocations: ['attendance record', 'attendance policy', 'improve attendance'],
  }),
  makeEntry({
    id: 'reschedule',
    word: 'reschedule',
    usIpa: '/riːˈskedʒuːl/',
    ukIpa: '/ˌriːˈʃedjuːl/',
    importance: 4,
    topics: ['work-school', 'travel-transit', 'people-relationships'],
    ko: '일정을 다시 잡다',
    zh: '重新安排时间',
    englishDefinition: 'to change something to a new time or date',
    noteEn: 'Common in appointment, interview, and transit conversations.',
    noteKo: '약속, 면접, 교통 일정 관련 대화에서 자주 씁니다.',
    noteZh: '在预约、面试、交通安排里很常见。',
    exampleEn: 'She asked to reschedule the interview for next Tuesday.',
    exampleKo: '그녀는 면접을 다음 주 화요일로 다시 잡아 달라고 요청했습니다.',
    exampleZh: '她请求把面试改到下周二。',
    collocations: ['reschedule an interview', 'reschedule a flight', 'reschedule the meeting'],
  }),
  makeEntry({
    id: 'commute',
    word: 'commute',
    usIpa: '/kəˈmjuːt/',
    ukIpa: '/kəˈmjuːt/',
    importance: 4,
    topics: ['travel-transit', 'work-school'],
    ko: '통근하다',
    zh: '通勤',
    englishDefinition: 'to travel regularly between home and work or school',
    noteEn: 'High-frequency word for transport, timing, and convenience questions.',
    noteKo: '교통, 소요 시간, 편의성 문제에서 자주 나옵니다.',
    noteZh: '在交通、耗时、便利性问题里很常见。',
    exampleEn: 'He commutes by train because parking downtown is expensive.',
    exampleKo: '도심 주차비가 비싸서 그는 기차로 통근합니다.',
    exampleZh: '因为市中心停车很贵，他坐火车通勤。',
    collocations: ['daily commute', 'long commute', 'commute by bus'],
  }),
  makeEntry({
    id: 'detour',
    word: 'detour',
    usIpa: '/ˈdiːtʊr/',
    ukIpa: '/ˈdiːtʊə/',
    importance: 3,
    topics: ['travel-transit', 'community-civic'],
    ko: '우회로',
    zh: '绕行路线',
    englishDefinition: 'a different route taken to avoid a closed or busy road',
    noteEn: 'Often appears with roadwork, events, and traffic notices.',
    noteKo: '도로 공사, 행사, 교통 공지와 함께 자주 나옵니다.',
    noteZh: '常和道路施工、活动、交通通知一起出现。',
    exampleEn: 'Drivers must use the detour during bridge repairs.',
    exampleKo: '운전자들은 교량 보수 중 우회로를 이용해야 합니다.',
    exampleZh: '桥梁维修期间，司机必须走绕行路线。',
    collocations: ['follow the detour', 'detour sign', 'take a detour'],
  }),
  makeEntry({
    id: 'platform',
    word: 'platform',
    usIpa: '/ˈplætfɔːrm/',
    ukIpa: '/ˈplætfɔːm/',
    importance: 3,
    topics: ['travel-transit', 'technology-communication'],
    ko: '승강장; 플랫폼',
    zh: '站台；平台',
    englishDefinition: 'the place where passengers wait for a train, or a digital system or service',
    noteEn: 'Meaning depends on context, which makes it useful for CELPIP inference questions.',
    noteKo: '문맥에 따라 뜻이 달라져 추론형 문제에서 유용합니다.',
    noteZh: '意思会随语境变化，因此很适合推断题。',
    exampleEn: 'Passengers should move to platform 4 for the delayed train.',
    exampleKo: '승객들은 지연된 열차를 위해 4번 승강장으로 이동해야 합니다.',
    exampleZh: '乘客应前往4号站台搭乘晚点列车。',
    collocations: ['train platform', 'online platform', 'platform change'],
  }),
  makeEntry({
    id: 'connection',
    word: 'connection',
    usIpa: '/kəˈnekʃən/',
    ukIpa: '/kəˈnekʃən/',
    importance: 4,
    topics: ['travel-transit', 'technology-communication', 'people-relationships'],
    ko: '환승; 연결; 관계',
    zh: '换乘；连接；关系',
    englishDefinition: 'a link between things, or a transfer between forms of transport',
    noteEn: 'A classic multi-meaning word in transit and digital contexts.',
    noteKo: '교통과 디지털 상황에서 뜻이 달라지는 대표 단어입니다.',
    noteZh: '在交通和数字场景里是典型的多义词。',
    exampleEn: 'Because of the delay, she missed her bus connection.',
    exampleKo: '지연 때문에 그녀는 버스 환승편을 놓쳤습니다.',
    exampleZh: '因为延误，她错过了公交换乘。',
    collocations: ['make a connection', 'internet connection', 'close connection'],
  }),
  makeEntry({
    id: 'reservation',
    word: 'reservation',
    usIpa: '/ˌrezərˈveɪʃən/',
    ukIpa: '/ˌrezəˈveɪʃən/',
    importance: 4,
    topics: ['travel-transit', 'shopping-banking'],
    ko: '예약',
    zh: '预订',
    englishDefinition: 'an arrangement to keep something such as a seat or room for someone',
    noteEn: 'Shows up in hotels, restaurants, tickets, and customer-service tasks.',
    noteKo: '호텔, 식당, 티켓, 고객 서비스 문제에서 자주 등장합니다.',
    noteZh: '在酒店、餐厅、票务、客服任务里很常见。',
    exampleEn: 'Your reservation will be cancelled if you arrive after 8 p.m.',
    exampleKo: '오후 8시 이후 도착하면 예약이 취소됩니다.',
    exampleZh: '如果你晚上8点以后到达，预订将被取消。',
    collocations: ['make a reservation', 'reservation number', 'confirm a reservation'],
  }),
  makeEntry({
    id: 'fare',
    word: 'fare',
    usIpa: '/fer/',
    ukIpa: '/feə/',
    importance: 3,
    topics: ['travel-transit', 'shopping-banking'],
    ko: '요금',
    zh: '票价；车费',
    englishDefinition: 'the amount paid for a taxi, bus, train, or other trip',
    noteEn: 'Common when comparing options, discounts, and transport choices.',
    noteKo: '선택지 비교, 할인, 교통 수단 선택에서 자주 나옵니다.',
    noteZh: '常见于比较选项、折扣和交通方式选择。',
    exampleEn: 'The app shows a lower fare if you travel after rush hour.',
    exampleKo: '그 앱은 혼잡 시간이 지난 뒤 이동하면 더 저렴한 요금을 보여줍니다.',
    exampleZh: '如果你避开高峰出行，这个应用会显示更低的票价。',
    collocations: ['bus fare', 'reduced fare', 'fare increase'],
  }),
  makeEntry({
    id: 'symptom',
    word: 'symptom',
    usIpa: '/ˈsɪmptəm/',
    ukIpa: '/ˈsɪmptəm/',
    importance: 5,
    topics: ['health-emergency'],
    ko: '증상',
    zh: '症状',
    englishDefinition: 'a physical or mental sign that shows someone may be ill',
    noteEn: 'A must-know health word for clinics, calls, and urgent-care conversations.',
    noteKo: '병원, 상담 전화, 응급 진료 대화에서 꼭 알아야 하는 단어입니다.',
    noteZh: '在诊所、咨询电话、急诊场景里必须掌握。',
    exampleEn: 'If your symptoms get worse, go to the emergency room right away.',
    exampleKo: '증상이 악화되면 즉시 응급실로 가세요.',
    exampleZh: '如果症状加重，请立刻去急诊室。',
    collocations: ['mild symptoms', 'flu symptoms', 'symptoms worsen'],
  }),
  makeEntry({
    id: 'prescription',
    word: 'prescription',
    usIpa: '/prɪˈskrɪpʃən/',
    ukIpa: '/prɪˈskrɪpʃən/',
    importance: 4,
    topics: ['health-emergency', 'shopping-banking'],
    ko: '처방전',
    zh: '处方',
    englishDefinition: 'a doctor’s written order for medicine',
    noteEn: 'Often linked to renewals, pharmacies, and insurance questions.',
    noteKo: '갱신, 약국, 보험 질문과 자주 연결됩니다.',
    noteZh: '常和续方、药房、保险问题联系在一起。',
    exampleEn: 'The clinic can send the prescription directly to your pharmacy.',
    exampleKo: '병원은 처방전을 약국으로 바로 보낼 수 있습니다.',
    exampleZh: '诊所可以把处方直接发送到你的药房。',
    collocations: ['renew a prescription', 'prescription refill', 'valid prescription'],
  }),
  makeEntry({
    id: 'allergy',
    word: 'allergy',
    usIpa: '/ˈælərdʒi/',
    ukIpa: '/ˈælədʒi/',
    importance: 4,
    topics: ['health-emergency', 'shopping-banking'],
    ko: '알레르기',
    zh: '过敏',
    englishDefinition: 'a harmful reaction by the body to certain foods, materials, or medicines',
    noteEn: 'Important when listening for safety information and special requests.',
    noteKo: '안전 정보와 특별 요청을 들을 때 중요한 단어입니다.',
    noteZh: '在听安全说明和特殊要求时很重要。',
    exampleEn: 'Please let us know if you have any allergy to this medication.',
    exampleKo: '이 약에 알레르기가 있다면 알려 주세요.',
    exampleZh: '如果你对这种药过敏，请告诉我们。',
    collocations: ['food allergy', 'allergy warning', 'allergic reaction'],
  }),
  makeEntry({
    id: 'appointment',
    word: 'appointment',
    usIpa: '/əˈpɔɪntmənt/',
    ukIpa: '/əˈpɔɪntmənt/',
    importance: 5,
    topics: ['health-emergency', 'work-school', 'people-relationships'],
    ko: '예약; 약속',
    zh: '预约；约会',
    englishDefinition: 'an arranged time to meet someone, especially for a professional service',
    noteEn: 'Very common in clinic, school, and service calls.',
    noteKo: '병원, 학교, 서비스 전화에서 매우 자주 나옵니다.',
    noteZh: '在诊所、学校、服务电话里非常常见。',
    exampleEn: 'I need to change my appointment because of a family emergency.',
    exampleKo: '가족 응급 상황 때문에 예약을 변경해야 합니다.',
    exampleZh: '因为家庭紧急情况，我需要改预约。',
    collocations: ['book an appointment', 'medical appointment', 'appointment reminder'],
  }),
  makeEntry({
    id: 'recover',
    word: 'recover',
    usIpa: '/rɪˈkʌvər/',
    ukIpa: '/rɪˈkʌvə/',
    importance: 4,
    topics: ['health-emergency', 'news-opinion', 'shopping-banking'],
    ko: '회복하다',
    zh: '恢复',
    englishDefinition: 'to become healthy, normal, or successful again after difficulty',
    noteEn: 'Can describe health, finances, and service restoration.',
    noteKo: '건강, 재정, 서비스 복구 모두에 쓸 수 있습니다.',
    noteZh: '可用于健康、财务、服务恢复等语境。',
    exampleEn: 'It may take a few days to recover from the side effects.',
    exampleKo: '부작용에서 회복하는 데 며칠이 걸릴 수 있습니다.',
    exampleZh: '从副作用中恢复可能需要几天。',
    collocations: ['recover fully', 'recover quickly', 'economic recovery'],
  }),
  makeEntry({
    id: 'urgent',
    word: 'urgent',
    usIpa: '/ˈɜːrdʒənt/',
    ukIpa: '/ˈɜːdʒənt/',
    importance: 5,
    topics: ['health-emergency', 'community-civic', 'work-school'],
    ko: '긴급한',
    zh: '紧急的',
    englishDefinition: 'requiring immediate action or attention',
    noteEn: 'Strong clue word that often decides the correct CELPIP answer.',
    noteKo: 'CELPIP에서 정답을 가르는 강한 단서 단어입니다.',
    noteZh: '是常常决定正确答案的强提示词。',
    exampleEn: 'If the issue is urgent, call the after-hours number instead.',
    exampleKo: '문제가 긴급하면 야간 번호로 대신 전화하세요.',
    exampleZh: '如果问题紧急，请改打下班后的联系电话。',
    collocations: ['urgent care', 'urgent request', 'urgent matter'],
  }),
  makeEntry({
    id: 'coverage',
    word: 'coverage',
    usIpa: '/ˈkʌvərɪdʒ/',
    ukIpa: '/ˈkʌvərɪdʒ/',
    importance: 4,
    topics: ['health-emergency', 'shopping-banking', 'technology-communication'],
    ko: '보장 범위; 적용 범위',
    zh: '保障范围；覆盖范围',
    englishDefinition: 'the amount of protection or service included in a plan',
    noteEn: 'Common in insurance, benefits, and network-service contexts.',
    noteKo: '보험, 복지, 네트워크 서비스 맥락에서 자주 나옵니다.',
    noteZh: '常见于保险、福利和网络服务语境。',
    exampleEn: 'Dental coverage is not included in the basic plan.',
    exampleKo: '기본 플랜에는 치과 보장이 포함되어 있지 않습니다.',
    exampleZh: '基础计划不包含牙科保障。',
    collocations: ['insurance coverage', 'limited coverage', 'mobile coverage'],
  }),
  makeEntry({
    id: 'refund',
    word: 'refund',
    usIpa: '/ˈriːfʌnd/',
    ukIpa: '/ˈriːfʌnd/',
    importance: 5,
    topics: ['shopping-banking', 'travel-transit'],
    ko: '환불; 환불하다',
    zh: '退款；退还',
    englishDefinition: 'money returned to someone after a payment has been reversed',
    noteEn: 'A very common problem-solving word in customer-service listening.',
    noteKo: '고객 서비스 듣기에서 매우 자주 나오는 문제 해결 단어입니다.',
    noteZh: '在客服听力里是非常高频的问题解决词。',
    exampleEn: 'You can request a refund if the item arrives damaged.',
    exampleKo: '상품이 손상된 상태로 도착하면 환불을 요청할 수 있습니다.',
    exampleZh: '如果商品送达时已损坏，你可以申请退款。',
    collocations: ['full refund', 'refund request', 'issue a refund'],
  }),
  makeEntry({
    id: 'receipt',
    word: 'receipt',
    usIpa: '/rɪˈsiːt/',
    ukIpa: '/rɪˈsiːt/',
    importance: 5,
    topics: ['shopping-banking', 'community-civic'],
    ko: '영수증',
    zh: '收据',
    englishDefinition: 'a paper or digital record showing that something was paid for',
    noteEn: 'Frequently needed in return, reimbursement, and proof-of-payment situations.',
    noteKo: '반품, 비용 청구, 결제 증빙에서 자주 필요합니다.',
    noteZh: '在退货、报销、付款证明中经常需要。',
    exampleEn: 'Please keep the receipt in case you need to exchange the item.',
    exampleKo: '상품을 교환해야 할 수 있으니 영수증을 보관하세요.',
    exampleZh: '请保留收据，以防你需要换货。',
    collocations: ['original receipt', 'keep the receipt', 'receipt number'],
  }),
  makeEntry({
    id: 'discount',
    word: 'discount',
    usIpa: '/ˈdɪskaʊnt/',
    ukIpa: '/ˈdɪskaʊnt/',
    importance: 4,
    topics: ['shopping-banking', 'travel-transit'],
    ko: '할인',
    zh: '折扣',
    englishDefinition: 'a reduction in price',
    noteEn: 'Useful in price comparison and membership-benefit questions.',
    noteKo: '가격 비교와 회원 혜택 문제에서 유용합니다.',
    noteZh: '在价格比较和会员优惠问题里很有用。',
    exampleEn: 'Students can get a discount on monthly transit passes.',
    exampleKo: '학생들은 월간 교통 패스 할인을 받을 수 있습니다.',
    exampleZh: '学生可以享受月票折扣。',
    collocations: ['special discount', 'student discount', 'apply a discount'],
  }),
  makeEntry({
    id: 'withdraw',
    word: 'withdraw',
    usIpa: '/wɪðˈdrɔː/',
    ukIpa: '/wɪðˈdrɔː/',
    importance: 4,
    topics: ['shopping-banking'],
    ko: '인출하다; 철회하다',
    zh: '提取；撤回',
    englishDefinition: 'to take money out, or to remove something formally',
    noteEn: 'Meaning changes by context, so listen carefully for banking vs. application use.',
    noteKo: '은행 맥락과 신청 철회 맥락이 달라서 문맥을 잘 들어야 합니다.',
    noteZh: '在银行和撤回申请语境中意思不同，要注意上下文。',
    exampleEn: 'You can withdraw cash from any ATM in the network.',
    exampleKo: '네트워크 내 어떤 ATM에서든 현금을 인출할 수 있습니다.',
    exampleZh: '你可以在该网络内任何 ATM 提取现金。',
    collocations: ['withdraw cash', 'withdraw an application', 'withdraw funds'],
  }),
  makeEntry({
    id: 'balance',
    word: 'balance',
    usIpa: '/ˈbæləns/',
    ukIpa: '/ˈbæləns/',
    importance: 4,
    topics: ['shopping-banking', 'people-relationships'],
    ko: '잔액; 균형',
    zh: '余额；平衡',
    englishDefinition: 'the amount left in an account, or a stable state between things',
    noteEn: 'One word can appear in banking or work-life balance discussions.',
    noteKo: '은행 잔액 또는 일과 삶의 균형 모두에 쓰일 수 있습니다.',
    noteZh: '既可指账户余额，也可指工作与生活平衡。',
    exampleEn: 'Your balance will update after the payment is processed.',
    exampleKo: '결제가 처리된 후 잔액이 업데이트됩니다.',
    exampleZh: '付款处理后，你的余额会更新。',
    collocations: ['account balance', 'maintain balance', 'check the balance'],
  }),
  makeEntry({
    id: 'fee',
    word: 'fee',
    usIpa: '/fiː/',
    ukIpa: '/fiː/',
    importance: 4,
    topics: ['shopping-banking', 'community-civic', 'work-school'],
    ko: '수수료; 요금',
    zh: '费用；手续费',
    englishDefinition: 'an amount of money paid for a service or permission',
    noteEn: 'Often hidden in policy details and extra-cost questions.',
    noteKo: '정책 세부 정보와 추가 비용 문제에서 자주 나옵니다.',
    noteZh: '常藏在政策细节和额外费用问题里。',
    exampleEn: 'There is no late fee if you renew online before midnight.',
    exampleKo: '자정 전에 온라인으로 갱신하면 연체 수수료가 없습니다.',
    exampleZh: '如果你在午夜前在线续办，就没有滞纳金。',
    collocations: ['annual fee', 'service fee', 'late fee'],
  }),
  makeEntry({
    id: 'refund-policy',
    word: 'policy',
    usIpa: '/ˈpɑːləsi/',
    ukIpa: '/ˈpɒləsi/',
    importance: 5,
    topics: ['shopping-banking', 'community-civic', 'work-school'],
    ko: '정책; 방침',
    zh: '政策；规定',
    englishDefinition: 'an official rule or guideline about how something should be handled',
    noteEn: 'Crucial in CELPIP because correct answers often depend on policy exceptions.',
    noteKo: 'CELPIP에서는 정책의 예외 조항이 정답을 좌우하는 경우가 많습니다.',
    noteZh: '在 CELPIP 中，很多正确答案都取决于政策例外。',
    exampleEn: 'According to store policy, sale items cannot be exchanged.',
    exampleKo: '매장 방침에 따라 세일 상품은 교환할 수 없습니다.',
    exampleZh: '根据商店政策，特价商品不能换货。',
    collocations: ['store policy', 'company policy', 'policy change'],
  }),
  makeEntry({
    id: 'reliable',
    word: 'reliable',
    usIpa: '/rɪˈlaɪəbəl/',
    ukIpa: '/rɪˈlaɪəbəl/',
    importance: 4,
    topics: ['technology-communication', 'people-relationships', 'travel-transit'],
    ko: '신뢰할 수 있는',
    zh: '可靠的',
    englishDefinition: 'able to be trusted or depended on',
    noteEn: 'Useful for evaluating services, people, and transport options.',
    noteKo: '서비스, 사람, 교통 선택지를 평가할 때 유용합니다.',
    noteZh: '评价服务、人物、交通选项时很常用。',
    exampleEn: 'We need a reliable internet connection for the online workshop.',
    exampleKo: '온라인 워크숍을 위해 신뢰할 수 있는 인터넷 연결이 필요합니다.',
    exampleZh: '在线研讨会需要稳定可靠的网络连接。',
    collocations: ['reliable service', 'reliable source', 'reliable connection'],
  }),
  makeEntry({
    id: 'password',
    word: 'password',
    usIpa: '/ˈpæsˌwɜːrd/',
    ukIpa: '/ˈpɑːswɜːd/',
    importance: 4,
    topics: ['technology-communication'],
    ko: '비밀번호',
    zh: '密码',
    englishDefinition: 'a secret word or code used to gain access',
    noteEn: 'Appears in account recovery, login, and security tasks.',
    noteKo: '계정 복구, 로그인, 보안 문제에서 자주 등장합니다.',
    noteZh: '在账户恢复、登录、安全任务里常见。',
    exampleEn: 'If you forget your password, click the reset link.',
    exampleKo: '비밀번호를 잊었다면 재설정 링크를 클릭하세요.',
    exampleZh: '如果你忘记密码，请点击重置链接。',
    collocations: ['strong password', 'reset a password', 'temporary password'],
  }),
  makeEntry({
    id: 'update',
    word: 'update',
    usIpa: '/ˈʌpdeɪt/',
    ukIpa: '/ˈʌpdeɪt/',
    importance: 5,
    topics: ['technology-communication', 'work-school', 'community-civic'],
    ko: '업데이트; 갱신하다',
    zh: '更新；升级',
    englishDefinition: 'new information, or the act of making something current',
    noteEn: 'A highly practical word for apps, forms, status, and records.',
    noteKo: '앱, 양식, 상태, 기록 갱신에서 매우 실용적인 단어입니다.',
    noteZh: '在应用、表格、状态、记录更新中非常实用。',
    exampleEn: 'Please update your emergency contact information in the system.',
    exampleKo: '시스템에서 비상 연락처 정보를 갱신해 주세요.',
    exampleZh: '请在系统中更新紧急联系人信息。',
    collocations: ['status update', 'software update', 'update a record'],
  }),
  makeEntry({
    id: 'attachment',
    word: 'attachment',
    usIpa: '/əˈtætʃmənt/',
    ukIpa: '/əˈtætʃmənt/',
    importance: 4,
    topics: ['technology-communication', 'work-school'],
    ko: '첨부 파일',
    zh: '附件',
    englishDefinition: 'a file sent together with an email or message',
    noteEn: 'Frequently appears in email reading and task-completion questions.',
    noteKo: '이메일 읽기와 업무 완료 문제에서 자주 보입니다.',
    noteZh: '在邮件阅读和任务完成问题里很常见。',
    exampleEn: 'The attachment contains the revised budget document.',
    exampleKo: '첨부 파일에는 수정된 예산 문서가 들어 있습니다.',
    exampleZh: '附件里包含修订后的预算文件。',
    collocations: ['email attachment', 'open the attachment', 'missing attachment'],
  }),
  makeEntry({
    id: 'confirm',
    word: 'confirm',
    usIpa: '/kənˈfɜːrm/',
    ukIpa: '/kənˈfɜːm/',
    importance: 5,
    topics: ['technology-communication', 'travel-transit', 'people-relationships'],
    ko: '확인하다',
    zh: '确认',
    englishDefinition: 'to say or show that something is true, accepted, or settled',
    noteEn: 'A core verb for bookings, appointments, and instructions.',
    noteKo: '예약, 약속, 안내 확인에 핵심이 되는 동사입니다.',
    noteZh: '在预订、预约、确认说明中是核心动词。',
    exampleEn: 'Please confirm whether you can attend the meeting tomorrow.',
    exampleKo: '내일 회의에 참석할 수 있는지 확인해 주세요.',
    exampleZh: '请确认你明天是否能参加会议。',
    collocations: ['confirm a booking', 'confirm attendance', 'confirm by email'],
  }),
  makeEntry({
    id: 'access',
    word: 'access',
    usIpa: '/ˈækˌses/',
    ukIpa: '/ˈækˌses/',
    importance: 5,
    topics: ['technology-communication', 'housing-services', 'community-civic'],
    ko: '접근; 이용 권한',
    zh: '访问；使用权限',
    englishDefinition: 'the right or ability to enter, use, or obtain something',
    noteEn: 'Key in internet, building entry, and service eligibility tasks.',
    noteKo: '인터넷, 출입, 서비스 이용 자격 문제에서 핵심입니다.',
    noteZh: '在网络、出入权限、服务资格问题中很关键。',
    exampleEn: 'Residents will lose access to the gym during repairs.',
    exampleKo: '수리 기간 동안 입주민들은 체육관을 이용할 수 없습니다.',
    exampleZh: '维修期间住户将无法进入健身房。',
    collocations: ['full access', 'access card', 'wheelchair access'],
  }),
  makeEntry({
    id: 'glitch',
    word: 'glitch',
    usIpa: '/ɡlɪtʃ/',
    ukIpa: '/ɡlɪtʃ/',
    importance: 3,
    topics: ['technology-communication'],
    ko: '오류; 일시적 결함',
    zh: '故障；小问题',
    englishDefinition: 'a small temporary problem in a machine, system, or plan',
    noteEn: 'A useful informal word in help-desk and app-support conversations.',
    noteKo: '헬프데스크와 앱 지원 대화에서 유용한 비격식 단어입니다.',
    noteZh: '在技术支持和应用问题对话中很实用。',
    exampleEn: 'The website had a glitch, so some payments were delayed.',
    exampleKo: '웹사이트에 오류가 있어서 일부 결제가 지연되었습니다.',
    exampleZh: '网站出现了故障，所以部分付款被延迟了。',
    collocations: ['minor glitch', 'technical glitch', 'glitch in the system'],
  }),
  makeEntry({
    id: 'privacy',
    word: 'privacy',
    usIpa: '/ˈpraɪvəsi/',
    ukIpa: '/ˈprɪvəsi/',
    importance: 4,
    topics: ['technology-communication', 'community-civic'],
    ko: '개인정보 보호; 사생활',
    zh: '隐私',
    englishDefinition: 'the right to keep personal information or life private',
    noteEn: 'Useful for policy discussions and digital-service concerns.',
    noteKo: '정책 토론과 디지털 서비스 우려를 말할 때 유용합니다.',
    noteZh: '讨论政策和数字服务隐忧时很有用。',
    exampleEn: 'The app was updated to improve user privacy settings.',
    exampleKo: '그 앱은 사용자 개인정보 설정을 개선하도록 업데이트되었습니다.',
    exampleZh: '该应用已更新，以改进用户隐私设置。',
    collocations: ['privacy policy', 'privacy settings', 'protect privacy'],
  }),
  makeEntry({
    id: 'bylaw',
    word: 'bylaw',
    usIpa: '/ˈbaɪˌlɔː/',
    ukIpa: '/ˈbaɪˌlɔː/',
    importance: 3,
    topics: ['community-civic', 'housing-services'],
    ko: '조례',
    zh: '地方法规',
    englishDefinition: 'a local rule made by a city, town, or organization',
    noteEn: 'A classic civic word for pets, parking, noise, and property use.',
    noteKo: '반려동물, 주차, 소음, 건물 사용 규정에서 자주 나오는 단어입니다.',
    noteZh: '常用于宠物、停车、噪音、物业使用等本地规定。',
    exampleEn: 'The bylaw limits overnight parking on this street.',
    exampleKo: '그 조례는 이 거리의 야간 주차를 제한합니다.',
    exampleZh: '该地方法规限制这条街上的夜间停车。',
    collocations: ['city bylaw', 'bylaw officer', 'violate a bylaw'],
  }),
  makeEntry({
    id: 'permit',
    word: 'permit',
    usIpa: '/pərˈmɪt/',
    ukIpa: '/pəˈmɪt/',
    importance: 5,
    topics: ['community-civic', 'housing-services', 'travel-transit'],
    ko: '허가증; 허가하다',
    zh: '许可证；允许',
    englishDefinition: 'official permission, or a document that proves permission',
    noteEn: 'A high-frequency word for parking, events, renovations, and work authorization.',
    noteKo: '주차, 행사, 공사, 근무 허가와 관련해 자주 나옵니다.',
    noteZh: '在停车、活动、装修、工作许可中很常见。',
    exampleEn: 'You must display the permit on your dashboard at all times.',
    exampleKo: '허가증은 항상 차량 대시보드에 보여야 합니다.',
    exampleZh: '许可证必须始终放在仪表板上展示。',
    collocations: ['parking permit', 'temporary permit', 'permit application'],
  }),
  makeEntry({
    id: 'eligible',
    word: 'eligible',
    usIpa: '/ˈelɪdʒəbəl/',
    ukIpa: '/ˈelɪdʒəbəl/',
    importance: 4,
    topics: ['community-civic', 'shopping-banking', 'work-school'],
    ko: '자격이 있는',
    zh: '有资格的',
    englishDefinition: 'having the right or ability to be chosen or receive something',
    noteEn: 'Important in benefits, discounts, grants, and service-access questions.',
    noteKo: '혜택, 할인, 장학금, 서비스 이용 자격 문제에서 중요합니다.',
    noteZh: '在福利、折扣、补助、服务资格问题里很重要。',
    exampleEn: 'Only full-time students are eligible for the transit discount.',
    exampleKo: '정규 학생만 교통 할인 대상입니다.',
    exampleZh: '只有全日制学生才有资格享受交通折扣。',
    collocations: ['eligible for', 'eligible applicant', 'not eligible'],
  }),
  makeEntry({
    id: 'register',
    word: 'register',
    usIpa: '/ˈredʒɪstər/',
    ukIpa: '/ˈredʒɪstə/',
    importance: 5,
    topics: ['community-civic', 'work-school', 'technology-communication'],
    ko: '등록하다',
    zh: '注册；登记',
    englishDefinition: 'to record information officially or sign up for something',
    noteEn: 'Very common in courses, community programs, and online accounts.',
    noteKo: '수업, 지역 프로그램, 온라인 계정에서 매우 자주 쓰입니다.',
    noteZh: '在课程、社区项目、在线账户中非常常见。',
    exampleEn: 'Residents must register before using the community garden.',
    exampleKo: '입주민들은 공동 정원을 사용하기 전에 등록해야 합니다.',
    exampleZh: '住户在使用社区花园前必须先登记。',
    collocations: ['register online', 'register for a course', 'registration deadline'],
  }),
  makeEntry({
    id: 'survey',
    word: 'survey',
    usIpa: '/ˈsɜːrveɪ/',
    ukIpa: '/ˈsɜːveɪ/',
    importance: 4,
    topics: ['community-civic', 'news-opinion', 'work-school'],
    ko: '설문 조사',
    zh: '调查',
    englishDefinition: 'a set of questions used to collect opinions or information',
    noteEn: 'Helpful in news and opinion tasks because it often signals evidence.',
    noteKo: '뉴스와 의견 문제에서 근거를 나타내는 단서가 되곤 합니다.',
    noteZh: '在新闻和观点任务中常常提示“证据来源”。',
    exampleEn: 'The survey showed that most commuters prefer earlier buses.',
    exampleKo: '설문 조사 결과 대부분의 통근자들이 더 이른 버스를 선호했습니다.',
    exampleZh: '调查显示，大多数通勤者更喜欢更早的公交车。',
    collocations: ['online survey', 'survey results', 'conduct a survey'],
  }),
  makeEntry({
    id: 'evidence',
    word: 'evidence',
    usIpa: '/ˈevɪdəns/',
    ukIpa: '/ˈevɪdəns/',
    importance: 5,
    topics: ['news-opinion', 'community-civic', 'work-school'],
    ko: '증거; 근거',
    zh: '证据；依据',
    englishDefinition: 'facts or information that support a claim or conclusion',
    noteEn: 'One of the best words for CELPIP reading and viewpoint tasks.',
    noteKo: 'CELPIP 읽기와 의견형 문제에서 매우 중요한 단어입니다.',
    noteZh: '是 CELPIP 阅读和观点题中的高价值词。',
    exampleEn: 'The article provides evidence that housing costs are rising faster than wages.',
    exampleKo: '그 기사는 주거비가 임금보다 더 빨리 오르고 있다는 근거를 제공합니다.',
    exampleZh: '这篇文章提供了住房成本上涨快于工资的证据。',
    collocations: ['strong evidence', 'supporting evidence', 'evidence suggests'],
  }),
  makeEntry({
    id: 'trend',
    word: 'trend',
    usIpa: '/trend/',
    ukIpa: '/trend/',
    importance: 5,
    topics: ['news-opinion', 'shopping-banking', 'community-civic'],
    ko: '추세',
    zh: '趋势',
    englishDefinition: 'a general direction in which something is changing',
    noteEn: 'Very common in charts, reports, and news summaries.',
    noteKo: '차트, 보고서, 뉴스 요약에서 매우 자주 나옵니다.',
    noteZh: '在图表、报告、新闻总结中非常常见。',
    exampleEn: 'The report highlights a trend toward remote work.',
    exampleKo: '그 보고서는 원격 근무로 향하는 추세를 강조합니다.',
    exampleZh: '该报告强调了转向远程办公的趋势。',
    collocations: ['upward trend', 'growing trend', 'market trend'],
  }),
  makeEntry({
    id: 'issue',
    word: 'issue',
    usIpa: '/ˈɪʃuː/',
    ukIpa: '/ˈɪsjuː/',
    importance: 5,
    topics: ['news-opinion', 'people-relationships', 'technology-communication'],
    ko: '문제; 사안',
    zh: '问题；议题',
    englishDefinition: 'a problem or an important subject being discussed',
    noteEn: 'Meaning depends on context, so it is useful in many CELPIP sections.',
    noteKo: '문맥에 따라 뜻이 달라 여러 CELPIP 영역에서 유용합니다.',
    noteZh: '意思会因语境而变，在多个 CELPIP 板块都很实用。',
    exampleEn: 'Noise from construction has become a major issue in the neighborhood.',
    exampleKo: '공사 소음이 그 동네의 큰 문제가 되었습니다.',
    exampleZh: '施工噪音已成为该社区的一个主要问题。',
    collocations: ['major issue', 'raise an issue', 'technical issue'],
  }),
  makeEntry({
    id: 'significant',
    word: 'significant',
    usIpa: '/sɪɡˈnɪfɪkənt/',
    ukIpa: '/sɪɡˈnɪfɪkənt/',
    importance: 4,
    topics: ['news-opinion', 'work-school'],
    ko: '중요한; 상당한',
    zh: '重要的；显著的',
    englishDefinition: 'important enough to be noticed, or large enough to matter',
    noteEn: 'Very useful for summarizing effects and results in writing.',
    noteKo: '쓰기에서 영향과 결과를 요약할 때 매우 유용합니다.',
    noteZh: '在写作中总结影响和结果时很有用。',
    exampleEn: 'The delay caused a significant drop in attendance.',
    exampleKo: '그 지연은 참석률의 상당한 감소를 초래했습니다.',
    exampleZh: '这次延误导致出席人数明显下降。',
    collocations: ['significant change', 'significant effect', 'statistically significant'],
  }),
  makeEntry({
    id: 'consequence',
    word: 'consequence',
    usIpa: '/ˈkɑːnsəˌkwens/',
    ukIpa: '/ˈkɒnsɪkwəns/',
    importance: 4,
    topics: ['news-opinion', 'community-civic', 'people-relationships'],
    ko: '결과; 여파',
    zh: '后果',
    englishDefinition: 'the result of an action or situation, especially a negative one',
    noteEn: 'Good for cause-and-effect questions in reading and listening.',
    noteKo: '읽기와 듣기의 원인-결과 문제에서 좋습니다.',
    noteZh: '适合阅读和听力中的因果题。',
    exampleEn: 'One consequence of the policy change was longer wait times.',
    exampleKo: '그 정책 변화의 결과 중 하나는 대기 시간이 더 길어진 것이었습니다.',
    exampleZh: '该政策变化的一个后果是等待时间变长了。',
    collocations: ['serious consequence', 'as a consequence', 'unintended consequence'],
  }),
  makeEntry({
    id: 'perspective',
    word: 'perspective',
    usIpa: '/pərˈspektɪv/',
    ukIpa: '/pəˈspektɪv/',
    importance: 4,
    topics: ['news-opinion', 'people-relationships'],
    ko: '관점',
    zh: '观点；角度',
    englishDefinition: 'a particular way of thinking about or understanding something',
    noteEn: 'Useful for viewpoint tasks and balanced speaking answers.',
    noteKo: '관점형 문제와 균형 잡힌 말하기 답변에 유용합니다.',
    noteZh: '适用于观点题和更平衡的口语回答。',
    exampleEn: 'From a parent’s perspective, the later start time makes sense.',
    exampleKo: '학부모 관점에서 보면 늦은 시작 시간이 타당합니다.',
    exampleZh: '从家长的角度来看，晚一点开始是合理的。',
    collocations: ['different perspective', 'from my perspective', 'broaden perspective'],
  }),
  makeEntry({
    id: 'reliable-source',
    word: 'source',
    usIpa: '/sɔːrs/',
    ukIpa: '/sɔːs/',
    importance: 4,
    topics: ['news-opinion', 'technology-communication', 'work-school'],
    ko: '출처; 정보원',
    zh: '来源；消息源',
    englishDefinition: 'the place, person, or document from which information comes',
    noteEn: 'Important when judging trust, evidence, and research quality.',
    noteKo: '신뢰도, 근거, 조사 품질을 판단할 때 중요합니다.',
    noteZh: '判断可信度、证据和研究质量时很重要。',
    exampleEn: 'The speaker cited a government source during the discussion.',
    exampleKo: '발표자는 토론 중 정부 출처를 인용했습니다.',
    exampleZh: '发言者在讨论中引用了政府来源。',
    collocations: ['reliable source', 'official source', 'source of information'],
  }),
  makeEntry({
    id: 'supportive',
    word: 'supportive',
    usIpa: '/səˈpɔːrtɪv/',
    ukIpa: '/səˈpɔːtɪv/',
    importance: 3,
    topics: ['people-relationships', 'work-school'],
    ko: '지지해 주는',
    zh: '支持性的',
    englishDefinition: 'showing encouragement, help, or approval',
    noteEn: 'Great for describing tone and relationships in speaking.',
    noteKo: '말하기에서 분위기와 관계를 묘사할 때 좋습니다.',
    noteZh: '在口语中描述语气和关系时很好用。',
    exampleEn: 'Her supervisor was supportive when she asked for flexible hours.',
    exampleKo: '그녀가 유연 근무를 요청했을 때 상사는 지지적이었습니다.',
    exampleZh: '当她请求弹性工时的时候，主管很支持她。',
    collocations: ['supportive manager', 'supportive environment', 'supportive response'],
  }),
  makeEntry({
    id: 'frustrated',
    word: 'frustrated',
    usIpa: '/ˈfrʌstreɪtɪd/',
    ukIpa: '/frʌˈstreɪtɪd/',
    importance: 4,
    topics: ['people-relationships', 'technology-communication', 'shopping-banking'],
    ko: '답답한; 좌절한',
    zh: '沮丧的；烦躁的',
    englishDefinition: 'feeling upset because you cannot do or change something easily',
    noteEn: 'Very useful for describing customer emotions in listening and speaking.',
    noteKo: '듣기와 말하기에서 고객 감정을 설명할 때 유용합니다.',
    noteZh: '在听力和口语里描述顾客情绪时很实用。',
    exampleEn: 'The customer sounded frustrated because the app kept crashing.',
    exampleKo: '그 고객은 앱이 계속 꺼져서 답답해 보였습니다.',
    exampleZh: '顾客听起来很烦躁，因为应用一直崩溃。',
    collocations: ['feel frustrated', 'visibly frustrated', 'frustrated customer'],
  }),
  makeEntry({
    id: 'compromise',
    word: 'compromise',
    usIpa: '/ˈkɑːmprəˌmaɪz/',
    ukIpa: '/ˈkɒmprəmaɪz/',
    importance: 4,
    topics: ['people-relationships', 'work-school', 'community-civic'],
    ko: '타협; 타협하다',
    zh: '妥协；折中',
    englishDefinition: 'an agreement in which each side gives up part of what it wants',
    noteEn: 'Good for advice, negotiation, and problem-solving speaking tasks.',
    noteKo: '조언, 협상, 문제 해결 말하기에서 좋습니다.',
    noteZh: '适合建议、协商、问题解决类口语任务。',
    exampleEn: 'A compromise would let both roommates use the kitchen fairly.',
    exampleKo: '타협안을 찾으면 두 룸메이트 모두 공평하게 부엌을 사용할 수 있습니다.',
    exampleZh: '如果采取折中方案，两位室友都能公平使用厨房。',
    collocations: ['reach a compromise', 'reasonable compromise', 'compromise solution'],
  }),
  makeEntry({
    id: 'misunderstanding',
    word: 'misunderstanding',
    usIpa: '/ˌmɪsʌndərˈstændɪŋ/',
    ukIpa: '/ˌmɪsʌndəˈstændɪŋ/',
    importance: 3,
    topics: ['people-relationships', 'technology-communication'],
    ko: '오해',
    zh: '误会',
    englishDefinition: 'a failure to understand something correctly',
    noteEn: 'Common in advice and relationship tasks.',
    noteKo: '조언형과 인간관계 문제에서 자주 등장합니다.',
    noteZh: '在建议题和人际关系任务中常出现。',
    exampleEn: 'It was just a misunderstanding about who was covering the shift.',
    exampleKo: '누가 그 근무를 대신하기로 했는지에 대한 단순한 오해였습니다.',
    exampleZh: '这只是关于谁来顶班的一场误会。',
    collocations: ['clear up a misunderstanding', 'simple misunderstanding', 'cause a misunderstanding'],
  }),
  makeEntry({
    id: 'concern',
    word: 'concern',
    usIpa: '/kənˈsɜːrn/',
    ukIpa: '/kənˈsɜːn/',
    importance: 5,
    topics: ['people-relationships', 'news-opinion', 'health-emergency'],
    ko: '우려; 걱정; 관련되다',
    zh: '担忧；关切；涉及',
    englishDefinition: 'a worry, or a matter that is important to someone',
    noteEn: 'A high-frequency word in problem, service, and public-issue tasks.',
    noteKo: '문제, 서비스, 공공 이슈 문제에서 자주 나옵니다.',
    noteZh: '在问题、服务、公共议题任务中频繁出现。',
    exampleEn: 'Her main concern was whether the medication would affect her work.',
    exampleKo: '그녀의 가장 큰 걱정은 약이 업무에 영향을 줄지 여부였습니다.',
    exampleZh: '她最担心的是药物是否会影响工作。',
    collocations: ['raise a concern', 'main concern', 'public concern'],
  }),
  makeEntry({
    id: 'encourage',
    word: 'encourage',
    usIpa: '/ɪnˈkɜːrɪdʒ/',
    ukIpa: '/ɪnˈkʌrɪdʒ/',
    importance: 4,
    topics: ['people-relationships', 'work-school', 'community-civic'],
    ko: '격려하다; 장려하다',
    zh: '鼓励；提倡',
    englishDefinition: 'to give someone confidence or make something more likely to happen',
    noteEn: 'Helpful in advice tasks and program/policy descriptions.',
    noteKo: '조언 문제와 프로그램·정책 설명에서 유용합니다.',
    noteZh: '在建议题和项目/政策说明里很有帮助。',
    exampleEn: 'The campaign encourages residents to recycle more often.',
    exampleKo: '그 캠페인은 주민들이 더 자주 재활용하도록 장려합니다.',
    exampleZh: '该活动鼓励居民更频繁地进行回收。',
    collocations: ['encourage participation', 'encourage students', 'strongly encourage'],
  }),
  makeEntry({
    id: 'courteous',
    word: 'courteous',
    usIpa: '/ˈkɜːrtiəs/',
    ukIpa: '/ˈkɜːtiəs/',
    importance: 3,
    topics: ['people-relationships', 'community-civic'],
    ko: '예의 바른',
    zh: '有礼貌的',
    englishDefinition: 'polite and respectful in a formal or careful way',
    noteEn: 'Great for CELPIP speaking where tone matters as much as content.',
    noteKo: 'CELPIP 말하기에서는 내용만큼 말투도 중요해 유용합니다.',
    noteZh: '在 CELPIP 口语中，语气和内容一样重要。',
    exampleEn: 'Please remain courteous even if the service delay is frustrating.',
    exampleKo: '서비스 지연이 답답하더라도 예의를 지켜 주세요.',
    exampleZh: '即使服务延误让人烦躁，也请保持礼貌。',
    collocations: ['courteous reply', 'courteous tone', 'be courteous'],
  }),
  makeEntry({
    id: 'alternative',
    word: 'alternative',
    usIpa: '/ɔːlˈtɜːrnətɪv/',
    ukIpa: '/ɔːlˈtɜːnətɪv/',
    importance: 5,
    topics: ['travel-transit', 'shopping-banking', 'people-relationships', 'work-school'],
    ko: '대안',
    zh: '替代方案',
    englishDefinition: 'another option or choice that can be used instead',
    noteEn: 'Extremely useful in CELPIP advice, comparison, and problem-solving tasks.',
    noteKo: 'CELPIP 조언, 비교, 문제 해결 유형에서 매우 유용합니다.',
    noteZh: '在 CELPIP 建议、比较、解决问题类任务中非常常用。',
    exampleEn: 'If the first route is closed, the station will suggest an alternative.',
    exampleKo: '첫 번째 경로가 폐쇄되면 역에서 대안을 제시할 것입니다.',
    exampleZh: '如果第一条路线关闭，车站会提供替代方案。',
    collocations: ['alternative route', 'alternative option', 'consider an alternative'],
  }),
  makeEntry({
    id: 'priority',
    word: 'priority',
    usIpa: '/praɪˈɔːrəti/',
    ukIpa: '/praɪˈɒrɪti/',
    importance: 4,
    topics: ['work-school', 'people-relationships', 'news-opinion'],
    ko: '우선순위',
    zh: '优先事项',
    englishDefinition: 'something that is more important than other things and should be dealt with first',
    noteEn: 'Useful for task order, advice, and planning questions.',
    noteKo: '업무 순서, 조언, 계획 세우기 문제에서 유용합니다.',
    noteZh: '在任务顺序、建议、规划问题中很有用。',
    exampleEn: 'Our first priority is to make sure everyone is safe.',
    exampleKo: '우리의 첫 번째 우선순위는 모두의 안전을 확인하는 것입니다.',
    exampleZh: '我们的首要任务是确保每个人都安全。',
    collocations: ['top priority', 'set priorities', 'priority access'],
  }),
  makeEntry({
    id: 'request',
    word: 'request',
    usIpa: '/rɪˈkwest/',
    ukIpa: '/rɪˈkwest/',
    importance: 5,
    topics: ['work-school', 'housing-services', 'community-civic', 'people-relationships'],
    ko: '요청; 요청하다',
    zh: '请求；申请',
    englishDefinition: 'an act of asking for something politely or formally',
    noteEn: 'One of the most frequent CELPIP action words across all sections.',
    noteKo: '모든 영역에서 매우 자주 등장하는 CELPIP 핵심 행동 단어입니다.',
    noteZh: '是 CELPIP 各板块都极高频的动作词。',
    exampleEn: 'Your request will be reviewed within two business days.',
    exampleKo: '귀하의 요청은 영업일 기준 2일 이내에 검토됩니다.',
    exampleZh: '你的请求将在两个工作日内审查。',
    collocations: ['submit a request', 'special request', 'request approval'],
  }),
  makeEntry({
    id: 'resolve',
    word: 'resolve',
    usIpa: '/rɪˈzɑːlv/',
    ukIpa: '/rɪˈzɒlv/',
    importance: 5,
    topics: ['problem-solving', 'people-relationships', 'technology-communication'],
    ko: '해결하다',
    zh: '解决',
    englishDefinition: 'to find a way to deal successfully with a problem',
    noteEn: 'Perfect for CELPIP complaint, issue, and customer-service tasks.',
    noteKo: '불만, 문제, 고객 서비스 문제에서 핵심 동사입니다.',
    noteZh: '在投诉、问题、客服任务中是核心动词。',
    exampleEn: 'The agent promised to resolve the billing issue by tomorrow.',
    exampleKo: '상담원은 청구 문제를 내일까지 해결하겠다고 약속했습니다.',
    exampleZh: '客服承诺会在明天之前解决账单问题。',
    collocations: ['resolve an issue', 'resolve quickly', 'resolve a conflict'],
  }),
  makeEntry({
    id: 'arrangement',
    word: 'arrangement',
    usIpa: '/əˈreɪndʒmənt/',
    ukIpa: '/əˈreɪndʒmənt/',
    importance: 3,
    topics: ['problem-solving', 'people-relationships', 'travel-transit'],
    ko: '조정; 준비; 합의',
    zh: '安排；协议',
    englishDefinition: 'a plan, agreement, or way in which something is organized',
    noteEn: 'Useful when solutions involve compromise or a temporary plan.',
    noteKo: '타협안이나 임시 계획을 설명할 때 좋습니다.',
    noteZh: '在说明折中方案或临时安排时很好用。',
    exampleEn: 'They made a temporary arrangement until the manager returned.',
    exampleKo: '그들은 매니저가 돌아올 때까지 임시 조정을 했습니다.',
    exampleZh: '他们做了一个临时安排，直到经理回来。',
    collocations: ['temporary arrangement', 'travel arrangement', 'make arrangements'],
  }),
  makeEntry({
    id: 'compensation',
    word: 'compensation',
    usIpa: '/ˌkɑːmpənˈseɪʃən/',
    ukIpa: '/ˌkɒmpənˈseɪʃən/',
    importance: 3,
    topics: ['problem-solving', 'shopping-banking', 'travel-transit'],
    ko: '보상',
    zh: '赔偿；补偿',
    englishDefinition: 'money or another form of payment given because of loss, damage, or inconvenience',
    noteEn: 'Helpful when a service failure leads to a follow-up action.',
    noteKo: '서비스 실패 뒤에 후속 조치가 나오는 상황에서 유용합니다.',
    noteZh: '在服务失误后给出后续处理时很有用。',
    exampleEn: 'Passengers may receive compensation for the cancelled flight.',
    exampleKo: '승객들은 취소된 항공편에 대해 보상을 받을 수 있습니다.',
    exampleZh: '乘客可能会因航班取消而获得赔偿。',
    collocations: ['financial compensation', 'seek compensation', 'offer compensation'],
  }),
  makeEntry({
    id: 'clarify',
    word: 'clarify',
    usIpa: '/ˈklerəˌfaɪ/',
    ukIpa: '/ˈklærɪfaɪ/',
    importance: 4,
    topics: ['problem-solving', 'work-school', 'technology-communication'],
    ko: '명확히 하다',
    zh: '澄清',
    englishDefinition: 'to make something easier to understand',
    noteEn: 'A strong verb for speaking politely while fixing confusion.',
    noteKo: '정중하게 오해를 바로잡을 때 좋은 동사입니다.',
    noteZh: '在礼貌澄清误会时是很好用的动词。',
    exampleEn: 'Could you clarify whether the discount applies to seniors as well?',
    exampleKo: '그 할인이 노인에게도 적용되는지 명확히 해 주시겠어요?',
    exampleZh: '你能澄清一下这个折扣是否也适用于老年人吗？',
    collocations: ['clarify a point', 'clarify instructions', 'clarify the policy'],
  }),
  makeEntry({
    id: 'available',
    word: 'available',
    usIpa: '/əˈveɪləbəl/',
    ukIpa: '/əˈveɪləbəl/',
    importance: 5,
    topics: ['problem-solving', 'work-school', 'travel-transit', 'housing-services'],
    ko: '이용 가능한; 가능한',
    zh: '可用的；有空的',
    englishDefinition: 'ready for use, ready to be obtained, or free to do something',
    noteEn: 'A frequent key word in choosing the best option.',
    noteKo: '최적의 선택지를 고를 때 자주 나오는 핵심 단어입니다.',
    noteZh: '在选择最佳方案时经常出现。',
    exampleEn: 'The earliest available appointment is next Wednesday.',
    exampleKo: '가장 빠른 예약 가능 시간은 다음 주 수요일입니다.',
    exampleZh: '最早可预约的时间是下周三。',
    collocations: ['available slot', 'available online', 'space available'],
  }),
  makeEntry({
    id: 'suitable',
    word: 'suitable',
    usIpa: '/ˈsuːtəbəl/',
    ukIpa: '/ˈsuːtəbəl/',
    importance: 4,
    topics: ['problem-solving', 'travel-transit', 'people-relationships'],
    ko: '적합한',
    zh: '合适的',
    englishDefinition: 'right or acceptable for a particular purpose or person',
    noteEn: 'Often appears when the speaker compares several options.',
    noteKo: '화자가 여러 선택지를 비교할 때 자주 등장합니다.',
    noteZh: '在说话人比较多个选项时经常出现。',
    exampleEn: 'This route is more suitable for families with young children.',
    exampleKo: '이 경로는 어린 자녀가 있는 가족에게 더 적합합니다.',
    exampleZh: '这条路线更适合有年幼孩子的家庭。',
    collocations: ['suitable option', 'suitable for', 'most suitable'],
  }),
  makeEntry({
    id: 'applicant',
    word: 'applicant',
    usIpa: '/ˈæplɪkənt/',
    ukIpa: '/ˈæplɪkənt/',
    importance: 4,
    topics: ['community-civic', 'work-school'],
    ko: '신청자',
    zh: '申请人',
    englishDefinition: 'a person who formally applies for something',
    noteEn: 'Very common in permits, jobs, scholarships, and program applications.',
    noteKo: '허가, 취업, 장학금, 프로그램 신청에서 매우 자주 나옵니다.',
    noteZh: '在许可、求职、奖学金和项目申请中很常见。',
    exampleEn: 'Each applicant must provide one photo ID and proof of address.',
    exampleKo: '각 신청자는 사진이 있는 신분증 1개와 주소 증빙을 제출해야 합니다.',
    exampleZh: '每位申请人都必须提供一份带照片的身份证件和住址证明。',
    collocations: ['qualified applicant', 'successful applicant', 'applicant information'],
  }),
  makeEntry({
    id: 'authorize',
    word: 'authorize',
    usIpa: '/ˈɔːθəˌraɪz/',
    ukIpa: '/ˈɔːθəraɪz/',
    importance: 4,
    topics: ['shopping-banking', 'community-civic', 'technology-communication'],
    ko: '승인하다; 권한을 부여하다',
    zh: '授权；批准',
    englishDefinition: 'to give official permission for something',
    noteEn: 'Useful when talking about payments, access, or official approval.',
    noteKo: '결제, 접근 권한, 공식 승인 상황에서 유용합니다.',
    noteZh: '谈支付、访问权限或官方批准时很有用。',
    exampleEn: 'Only the manager can authorize a refund of that size.',
    exampleKo: '그 정도 금액의 환불은 매니저만 승인할 수 있습니다.',
    exampleZh: '只有经理才能批准那么大金额的退款。',
    collocations: ['authorize payment', 'authorize access', 'authorize a refund'],
  }),
  makeEntry({
    id: 'brochure',
    word: 'brochure',
    usIpa: '/broʊˈʃʊr/',
    ukIpa: '/ˈbrəʊʃə/',
    importance: 3,
    topics: ['travel-transit', 'community-civic'],
    ko: '안내 책자; 브로슈어',
    zh: '宣传册；手册',
    englishDefinition: 'a small booklet with information about a service, place, or event',
    noteEn: 'Appears in information texts and questions about where details can be found.',
    noteKo: '안내문, 정보문에서 세부 정보를 어디서 찾는지 묻는 문제에 자주 나옵니다.',
    noteZh: '常出现在信息文或询问细节在哪里能找到的问题中。',
    exampleEn: 'The brochure lists the museum hours and guided tour times.',
    exampleKo: '그 안내 책자에는 박물관 운영 시간과 가이드 투어 시간이 나와 있습니다.',
    exampleZh: '宣传册上列出了博物馆开放时间和导览时间。',
    collocations: ['travel brochure', 'brochure rack', 'information brochure'],
  }),
  makeEntry({
    id: 'capacity',
    word: 'capacity',
    usIpa: '/kəˈpæsəti/',
    ukIpa: '/kəˈpæsɪti/',
    importance: 4,
    topics: ['community-civic', 'travel-transit', 'health-emergency'],
    ko: '수용 인원; 용량',
    zh: '容量；容纳人数',
    englishDefinition: 'the amount that something can hold or the number of people it can contain',
    noteEn: 'Important for events, rooms, transit, and emergency planning.',
    noteKo: '행사, 공간, 교통, 비상 계획에서 중요한 단어입니다.',
    noteZh: '在活动、场地、交通和应急安排中很重要。',
    exampleEn: 'The hall reached full capacity before noon.',
    exampleKo: '그 강당은 정오 전에 수용 인원을 모두 채웠습니다.',
    exampleZh: '那个礼堂在中午前就满员了。',
    collocations: ['full capacity', 'seating capacity', 'at capacity'],
  }),
  makeEntry({
    id: 'complaint',
    word: 'complaint',
    usIpa: '/kəmˈpleɪnt/',
    ukIpa: '/kəmˈpleɪnt/',
    importance: 5,
    topics: ['problem-solving', 'shopping-banking', 'housing-services'],
    ko: '불만; 민원',
    zh: '投诉；抱怨',
    englishDefinition: 'a statement that something is wrong or not satisfactory',
    noteEn: 'CELPIP often turns a complaint into a problem-solving conversation.',
    noteKo: 'CELPIP에서는 불만 상황이 문제 해결 대화로 이어지는 경우가 많습니다.',
    noteZh: '在 CELPIP 里，投诉情境常常会转成问题解决对话。',
    exampleEn: 'The customer filed a complaint about the delayed shipment.',
    exampleKo: '그 고객은 배송 지연에 대해 불만을 제기했습니다.',
    exampleZh: '那位顾客就延迟发货提出了投诉。',
    collocations: ['file a complaint', 'noise complaint', 'formal complaint'],
  }),
  makeEntry({
    id: 'congestion',
    word: 'congestion',
    usIpa: '/kənˈdʒestʃən/',
    ukIpa: '/kənˈdʒestʃən/',
    importance: 3,
    topics: ['travel-transit', 'health-emergency'],
    ko: '혼잡; 코막힘',
    zh: '拥堵；鼻塞',
    englishDefinition: 'heavy crowding in traffic, or blockage in the body such as the nose',
    noteEn: 'Context matters because it can refer to traffic or health symptoms.',
    noteKo: '교통 혼잡인지 건강 증상인지 문맥을 잘 봐야 합니다.',
    noteZh: '要看语境，因为它既可以指交通拥堵，也可以指身体症状。',
    exampleEn: 'Morning congestion on the highway added thirty minutes to the trip.',
    exampleKo: '고속도로의 아침 혼잡 때문에 이동 시간이 30분 더 걸렸습니다.',
    exampleZh: '高速公路早高峰拥堵让行程多花了三十分钟。',
    collocations: ['traffic congestion', 'nasal congestion', 'reduce congestion'],
  }),
  makeEntry({
    id: 'consult',
    word: 'consult',
    usIpa: '/kənˈsʌlt/',
    ukIpa: '/kənˈsʌlt/',
    importance: 4,
    topics: ['health-emergency', 'work-school', 'community-civic'],
    ko: '상담하다; 상의하다',
    zh: '咨询；商量',
    englishDefinition: 'to seek advice or information from a person or source',
    noteEn: 'Useful for doctor visits, expert advice, and official guidance.',
    noteKo: '의사 방문, 전문가 조언, 공식 안내 상황에 자주 쓰입니다.',
    noteZh: '常用于就医、专家建议和官方指导情境。',
    exampleEn: 'You should consult a pharmacist before taking both medicines together.',
    exampleKo: '두 약을 함께 복용하기 전에 약사와 상담해야 합니다.',
    exampleZh: '在同时服用这两种药之前，你应该先咨询药剂师。',
    collocations: ['consult a doctor', 'consult the manual', 'consult with staff'],
  }),
  makeEntry({
    id: 'consumption',
    word: 'consumption',
    usIpa: '/kənˈsʌmpʃən/',
    ukIpa: '/kənˈsʌmpʃən/',
    importance: 3,
    topics: ['news-opinion', 'shopping-banking', 'community-civic'],
    ko: '소비; 사용량',
    zh: '消费；消耗量',
    englishDefinition: 'the act of using, eating, or buying something',
    noteEn: 'Helpful in charts, news reports, and public policy discussions.',
    noteKo: '도표, 뉴스 리포트, 공공 정책 설명에서 자주 보입니다.',
    noteZh: '在图表、新闻报道和公共政策讨论中常见。',
    exampleEn: 'Electricity consumption rises sharply during the winter.',
    exampleKo: '겨울에는 전기 사용량이 급격히 증가합니다.',
    exampleZh: '冬季电力消耗会显著上升。',
    collocations: ['energy consumption', 'consumer consumption', 'water consumption'],
  }),
  makeEntry({
    id: 'contribution',
    word: 'contribution',
    usIpa: '/ˌkɑːntrəˈbjuːʃən/',
    ukIpa: '/ˌkɒntrɪˈbjuːʃən/',
    importance: 3,
    topics: ['work-school', 'community-civic', 'people-relationships'],
    ko: '기여; 기부',
    zh: '贡献；捐款',
    englishDefinition: 'something given or done to help produce a result',
    noteEn: 'Can refer to teamwork, volunteer support, or money donated.',
    noteKo: '팀 기여, 자원봉사, 기부금 모두를 가리킬 수 있습니다.',
    noteZh: '既可指团队贡献，也可指志愿支持或捐款。',
    exampleEn: 'Her contribution to the group project was the final presentation.',
    exampleKo: '그녀의 조별 과제 기여는 최종 발표였습니다.',
    exampleZh: '她对小组项目的贡献是最终展示部分。',
    collocations: ['make a contribution', 'financial contribution', 'major contribution'],
  }),
  makeEntry({
    id: 'convenient',
    word: 'convenient',
    usIpa: '/kənˈviːniənt/',
    ukIpa: '/kənˈviːniənt/',
    importance: 4,
    topics: ['travel-transit', 'technology-communication', 'problem-solving'],
    ko: '편리한',
    zh: '方便的',
    englishDefinition: 'easy to use, reach, or do at a suitable time',
    noteEn: 'A common comparison word when speakers evaluate options.',
    noteKo: '선택지를 비교 평가할 때 자주 등장하는 단어입니다.',
    noteZh: '是比较多个选项时常见的评价词。',
    exampleEn: 'Online check-in is more convenient for passengers with carry-on bags.',
    exampleKo: '온라인 체크인은 기내 반입 수하물이 있는 승객에게 더 편리합니다.',
    exampleZh: '在线值机对只有随身行李的乘客更方便。',
    collocations: ['convenient location', 'more convenient', 'at your convenience'],
  }),
  makeEntry({
    id: 'courtesy',
    word: 'courtesy',
    usIpa: '/ˈkɝːtəsi/',
    ukIpa: '/ˈkɜːtəsi/',
    importance: 3,
    topics: ['people-relationships', 'problem-solving', 'shopping-banking'],
    ko: '예의; 호의로 제공되는',
    zh: '礼貌；免费提供的',
    englishDefinition: 'polite behavior, or something given for free as a polite service',
    noteEn: 'Sometimes means politeness and sometimes means a complimentary service.',
    noteKo: '예의를 뜻할 수도 있고 무료 서비스라는 뜻일 수도 있어 문맥이 중요합니다.',
    noteZh: '有时表示礼貌，有时表示免费服务，所以要看语境。',
    exampleEn: 'The hotel offered a courtesy shuttle to the airport.',
    exampleKo: '그 호텔은 공항까지 무료 셔틀을 제공했습니다.',
    exampleZh: '那家酒店提供前往机场的免费班车服务。',
    collocations: ['courtesy call', 'courtesy shuttle', 'professional courtesy'],
  }),
  makeEntry({
    id: 'defective',
    word: 'defective',
    usIpa: '/dɪˈfektɪv/',
    ukIpa: '/dɪˈfektɪv/',
    importance: 4,
    topics: ['shopping-banking', 'housing-services', 'technology-communication'],
    ko: '결함이 있는; 불량의',
    zh: '有缺陷的；有问题的',
    englishDefinition: 'not working properly because of a fault or damage',
    noteEn: 'Very useful in refund, warranty, and complaint tasks.',
    noteKo: '환불, 보증, 불만 처리 문제에서 매우 유용합니다.',
    noteZh: '在退款、保修和投诉任务中非常有用。',
    exampleEn: 'Customers can return defective items within thirty days.',
    exampleKo: '고객은 30일 이내에 불량 상품을 반품할 수 있습니다.',
    exampleZh: '顾客可以在三十天内退回有缺陷的商品。',
    collocations: ['defective item', 'defective product', 'defective part'],
  }),
  makeEntry({
    id: 'deposit',
    word: 'deposit',
    usIpa: '/dɪˈpɑːzɪt/',
    ukIpa: '/dɪˈpɒzɪt/',
    importance: 5,
    topics: ['shopping-banking', 'housing-services', 'travel-transit'],
    ko: '보증금; 입금하다',
    zh: '押金；存款；存入',
    englishDefinition: 'money paid in advance or money placed into a bank account',
    noteEn: 'A classic CELPIP word because it changes meaning by context.',
    noteKo: '문맥에 따라 의미가 달라져 CELPIP에서 자주 나오는 대표 단어입니다.',
    noteZh: '因为会随语境改变含义，所以是 CELPIP 常考词。',
    exampleEn: 'The landlord will return the deposit after the final inspection.',
    exampleKo: '집주인은 최종 점검 후 보증금을 돌려줄 것입니다.',
    exampleZh: '房东会在最终检查后退还押金。',
    collocations: ['security deposit', 'deposit money', 'deposit slip'],
  }),
  makeEntry({
    id: 'disruption',
    word: 'disruption',
    usIpa: '/dɪsˈrʌpʃən/',
    ukIpa: '/dɪsˈrʌpʃən/',
    importance: 4,
    topics: ['travel-transit', 'technology-communication', 'community-civic'],
    ko: '차질; 혼란',
    zh: '中断；扰乱',
    englishDefinition: 'a problem that interrupts normal activity or service',
    noteEn: 'Signals delays, cancellations, service changes, or inconvenience.',
    noteKo: '지연, 취소, 서비스 변경, 불편을 나타낼 때 자주 쓰입니다.',
    noteZh: '常用于表示延误、取消、服务变化或不便。',
    exampleEn: 'Storm-related disruptions affected several commuter trains.',
    exampleKo: '폭풍으로 인한 차질이 여러 통근 열차에 영향을 미쳤습니다.',
    exampleZh: '与暴风雨有关的中断影响了多趟通勤列车。',
    collocations: ['service disruption', 'major disruption', 'traffic disruption'],
  }),
  makeEntry({
    id: 'enroll',
    word: 'enroll',
    usIpa: '/ɪnˈroʊl/',
    ukIpa: '/ɪnˈrəʊl/',
    importance: 4,
    topics: ['work-school', 'health-emergency', 'community-civic'],
    ko: '등록하다',
    zh: '注册；报名',
    englishDefinition: 'to officially join a course, plan, or program',
    noteEn: 'Common in classes, insurance plans, and community programs.',
    noteKo: '수업, 보험, 지역 프로그램 등록에서 자주 나옵니다.',
    noteZh: '在课程、保险计划和社区项目报名中常见。',
    exampleEn: 'Students must enroll online before the orientation session.',
    exampleKo: '학생들은 오리엔테이션 전에 온라인으로 등록해야 합니다.',
    exampleZh: '学生必须在迎新活动前在线报名。',
    collocations: ['enroll in a course', 'enroll online', 'newly enrolled'],
  }),
  makeEntry({
    id: 'exception',
    word: 'exception',
    usIpa: '/ɪkˈsepʃən/',
    ukIpa: '/ɪkˈsepʃən/',
    importance: 4,
    topics: ['community-civic', 'housing-services', 'problem-solving'],
    ko: '예외',
    zh: '例外',
    englishDefinition: 'a case that does not follow the usual rule',
    noteEn: 'Important in policy, notice, and rule-based reading questions.',
    noteKo: '정책, 공지, 규정 관련 읽기 문제에서 중요합니다.',
    noteZh: '在政策、通知和规则类阅读题里很重要。',
    exampleEn: 'Pets are not allowed, with the exception of service animals.',
    exampleKo: '도우미 동물을 제외하고는 반려동물을 허용하지 않습니다.',
    exampleZh: '除服务类动物外，不允许携带宠物。',
    collocations: ['an exception to the rule', 'special exception', 'without exception'],
  }),
  makeEntry({
    id: 'expire',
    word: 'expire',
    usIpa: '/ɪkˈspaɪr/',
    ukIpa: '/ɪkˈspaɪə/',
    importance: 5,
    topics: ['community-civic', 'shopping-banking', 'health-emergency'],
    ko: '만료되다',
    zh: '到期；失效',
    englishDefinition: 'to come to an end after a fixed period of time',
    noteEn: 'A key word for permits, cards, prescriptions, and offers.',
    noteKo: '허가증, 카드, 처방전, 프로모션에서 매우 중요한 단어입니다.',
    noteZh: '是许可证、卡片、处方和优惠活动里的高频词。',
    exampleEn: 'Your membership card will expire at the end of the month.',
    exampleKo: '회원 카드는 이달 말에 만료됩니다.',
    exampleZh: '你的会员卡将在本月底到期。',
    collocations: ['expire soon', 'expired card', 'expire next month'],
  }),
  makeEntry({
    id: 'extension',
    word: 'extension',
    usIpa: '/ɪkˈstenʃən/',
    ukIpa: '/ɪkˈstenʃən/',
    importance: 4,
    topics: ['work-school', 'community-civic', 'problem-solving'],
    ko: '연장; 내선 번호',
    zh: '延期；分机号',
    englishDefinition: 'extra time given for something, or an added phone line number',
    noteEn: 'Usually means extra time in CELPIP, but phone context can change it.',
    noteKo: 'CELPIP에서는 보통 연장 기간이지만 전화 문맥에서는 내선 번호일 수 있습니다.',
    noteZh: '在 CELPIP 中通常指延期，但电话语境里也可能指分机号。',
    exampleEn: 'She asked for an extension because the assignment instructions changed late.',
    exampleKo: '그녀는 과제 지시가 늦게 바뀌어서 연장을 요청했습니다.',
    exampleZh: '由于作业要求临时更改，她申请了延期。',
    collocations: ['deadline extension', 'grant an extension', 'phone extension'],
  }),
  makeEntry({
    id: 'flexible',
    word: 'flexible',
    usIpa: '/ˈfleksəbəl/',
    ukIpa: '/ˈfleksɪbəl/',
    importance: 3,
    topics: ['work-school', 'travel-transit', 'people-relationships'],
    ko: '유연한',
    zh: '灵活的',
    englishDefinition: 'able to change or adapt easily',
    noteEn: 'Useful for schedule, policy, and teamwork conversations.',
    noteKo: '일정, 정책, 팀워크 대화에서 자주 쓰입니다.',
    noteZh: '在日程、政策和团队合作对话里很实用。',
    exampleEn: 'The employer offers flexible work hours during the summer.',
    exampleKo: '그 고용주는 여름 동안 유연 근무 시간을 제공합니다.',
    exampleZh: '这家雇主在夏季提供弹性工作时间。',
    collocations: ['flexible schedule', 'flexible option', 'be flexible'],
  }),
  makeEntry({
    id: 'guideline',
    word: 'guideline',
    usIpa: '/ˈɡaɪdˌlaɪn/',
    ukIpa: '/ˈɡaɪdlaɪn/',
    importance: 4,
    topics: ['community-civic', 'health-emergency', 'work-school'],
    ko: '지침',
    zh: '指导原则；指引',
    englishDefinition: 'an official rule or recommendation about how to do something',
    noteEn: 'Frequently appears in public notices and workplace instructions.',
    noteKo: '공공 공지와 직장 지침에서 자주 등장합니다.',
    noteZh: '常出现在公共通知和工作说明中。',
    exampleEn: 'Please review the updated safety guidelines before entering the lab.',
    exampleKo: '실험실에 들어가기 전에 업데이트된 안전 지침을 검토해 주세요.',
    exampleZh: '进入实验室前请先查看更新后的安全指南。',
    collocations: ['safety guideline', 'follow guidelines', 'official guideline'],
  }),
  makeEntry({
    id: 'inquire',
    word: 'inquire',
    usIpa: '/ɪnˈkwaɪr/',
    ukIpa: '/ɪnˈkwaɪə/',
    importance: 3,
    topics: ['technology-communication', 'travel-transit', 'community-civic'],
    ko: '문의하다',
    zh: '询问',
    englishDefinition: 'to ask for information in a formal or polite way',
    noteEn: 'A formal alternative to ask, often seen in emails and notices.',
    noteKo: 'ask보다 격식 있는 표현으로, 이메일과 공지에서 자주 보입니다.',
    noteZh: '比 ask 更正式，常见于邮件和公告。',
    exampleEn: 'Passengers can inquire at the service desk about luggage rules.',
    exampleKo: '승객들은 서비스 데스크에서 수하물 규정을 문의할 수 있습니다.',
    exampleZh: '乘客可以在服务台询问行李规定。',
    collocations: ['inquire about', 'inquire whether', 'further inquiries'],
  }),
  makeEntry({
    id: 'inspection',
    word: 'inspection',
    usIpa: '/ɪnˈspekʃən/',
    ukIpa: '/ɪnˈspekʃən/',
    importance: 4,
    topics: ['housing-services', 'community-civic', 'travel-transit'],
    ko: '점검; 검사',
    zh: '检查；检验',
    englishDefinition: 'an official examination to see whether something is acceptable or safe',
    noteEn: 'Common in housing, permits, maintenance, and customs contexts.',
    noteKo: '주거, 허가, 유지 보수, 세관 문맥에서 자주 나옵니다.',
    noteZh: '在住房、许可、维护和海关语境中经常出现。',
    exampleEn: 'The unit passed the final inspection after the repairs were completed.',
    exampleKo: '수리가 끝난 후 그 세대는 최종 점검을 통과했습니다.',
    exampleZh: '维修完成后，该房间通过了最终检查。',
    collocations: ['final inspection', 'safety inspection', 'inspection report'],
  }),
  makeEntry({
    id: 'install',
    word: 'install',
    usIpa: '/ɪnˈstɔːl/',
    ukIpa: '/ɪnˈstɔːl/',
    importance: 3,
    topics: ['technology-communication', 'housing-services'],
    ko: '설치하다',
    zh: '安装',
    englishDefinition: 'to put equipment or software in place so it can be used',
    noteEn: 'Appears in software help, internet service, and appliance conversations.',
    noteKo: '소프트웨어 도움말, 인터넷 서비스, 가전제품 대화에 자주 등장합니다.',
    noteZh: '常出现在软件帮助、网络服务和家电对话中。',
    exampleEn: 'A technician will install the modem on Friday morning.',
    exampleKo: '기술자가 금요일 아침에 모뎀을 설치할 예정입니다.',
    exampleZh: '技术人员将在周五上午安装调制解调器。',
    collocations: ['install software', 'install equipment', 'installation fee'],
  }),
  makeEntry({
    id: 'liability',
    word: 'liability',
    usIpa: '/ˌlaɪəˈbɪləti/',
    ukIpa: '/ˌlaɪəˈbɪləti/',
    importance: 3,
    topics: ['shopping-banking', 'community-civic', 'work-school'],
    ko: '법적 책임; 채무',
    zh: '责任；负债',
    englishDefinition: 'legal responsibility, or a financial amount owed',
    noteEn: 'Often shows up in insurance, contracts, and risk explanations.',
    noteKo: '보험, 계약, 위험 설명에서 자주 나옵니다.',
    noteZh: '常见于保险、合同和风险说明。',
    exampleEn: 'The company is not liable for items left unattended in the lobby.',
    exampleKo: '회사는 로비에 방치된 물품에 대해 책임을 지지 않습니다.',
    exampleZh: '公司对留在大厅无人看管的物品不承担责任。',
    collocations: ['legal liability', 'limit liability', 'accept liability'],
  }),
  makeEntry({
    id: 'medication',
    word: 'medication',
    usIpa: '/ˌmedɪˈkeɪʃən/',
    ukIpa: '/ˌmedɪˈkeɪʃən/',
    importance: 4,
    topics: ['health-emergency'],
    ko: '약; 약물',
    zh: '药物；药品',
    englishDefinition: 'medicine used to treat an illness or condition',
    noteEn: 'Important in appointment, pharmacy, and symptom-related tasks.',
    noteKo: '예약, 약국, 증상 관련 과제에서 중요한 단어입니다.',
    noteZh: '在预约、药房和症状相关任务中很重要。',
    exampleEn: 'Take the medication with food unless the label says otherwise.',
    exampleKo: '라벨에 다른 지시가 없으면 약을 음식과 함께 복용하세요.',
    exampleZh: '除非标签另有说明，否则请随餐服药。',
    collocations: ['take medication', 'prescribed medication', 'daily medication'],
  }),
  makeEntry({
    id: 'membership',
    word: 'membership',
    usIpa: '/ˈmembərʃɪp/',
    ukIpa: '/ˈmembəʃɪp/',
    importance: 3,
    topics: ['shopping-banking', 'community-civic', 'health-emergency'],
    ko: '회원 자격; 멤버십',
    zh: '会员资格；会员卡',
    englishDefinition: 'the state of belonging to a club, plan, or organization',
    noteEn: 'Useful for gym, library, loyalty, and service plan conversations.',
    noteKo: '헬스장, 도서관, 포인트, 서비스 플랜 대화에서 유용합니다.',
    noteZh: '在健身房、图书馆、会员积分和服务计划对话里很常见。',
    exampleEn: 'Your membership includes free access to weekend workshops.',
    exampleKo: '회원 자격에는 주말 워크숍 무료 이용이 포함됩니다.',
    exampleZh: '你的会员资格包含周末讲座的免费参加权。',
    collocations: ['annual membership', 'membership fee', 'membership card'],
  }),
  makeEntry({
    id: 'outage',
    word: 'outage',
    usIpa: '/ˈaʊtɪdʒ/',
    ukIpa: '/ˈaʊtɪdʒ/',
    importance: 4,
    topics: ['technology-communication', 'housing-services', 'community-civic'],
    ko: '정전; 서비스 중단',
    zh: '停电；服务中断',
    englishDefinition: 'a period when power, internet, or another service is unavailable',
    noteEn: 'A key notice word in apartment, internet, and city service updates.',
    noteKo: '아파트, 인터넷, 도시 서비스 공지에서 중요한 단어입니다.',
    noteZh: '在公寓、网络和城市服务通知中是高频词。',
    exampleEn: 'The internet outage affected all offices on the second floor.',
    exampleKo: '인터넷 중단은 2층의 모든 사무실에 영향을 미쳤습니다.',
    exampleZh: '网络中断影响了二楼的所有办公室。',
    collocations: ['power outage', 'service outage', 'planned outage'],
  }),
  makeEntry({
    id: 'orientation',
    word: 'orientation',
    usIpa: '/ˌɔːriənˈteɪʃən/',
    ukIpa: '/ˌɔːrienˈteɪʃən/',
    importance: 3,
    topics: ['work-school', 'community-civic'],
    ko: '오리엔테이션; 적응 안내',
    zh: '迎新说明会；入门培训',
    englishDefinition: 'an introductory meeting or session that helps people understand a place or program',
    noteEn: 'Useful for campus, job, volunteer, and training schedules.',
    noteKo: '학교, 직장, 봉사, 교육 일정에서 자주 보입니다.',
    noteZh: '常见于校园、工作、志愿服务和培训日程。',
    exampleEn: 'New volunteers must attend orientation before starting their shifts.',
    exampleKo: '새 자원봉사자는 근무를 시작하기 전에 오리엔테이션에 참석해야 합니다.',
    exampleZh: '新志愿者必须在开始值班前参加迎新说明会。',
    collocations: ['orientation session', 'new student orientation', 'staff orientation'],
  }),
  makeEntry({
    id: 'overcharge',
    word: 'overcharge',
    usIpa: '/ˌoʊvərˈtʃɑːrdʒ/',
    ukIpa: '/ˌəʊvəˈtʃɑːdʒ/',
    importance: 4,
    topics: ['shopping-banking', 'travel-transit', 'problem-solving'],
    ko: '과다 청구하다; 바가지요금을 받다',
    zh: '多收费；乱收费',
    englishDefinition: 'to charge someone more money than the correct amount',
    noteEn: 'A strong word for billing mistakes and customer complaints.',
    noteKo: '청구 오류와 고객 불만 상황에서 매우 유용한 단어입니다.',
    noteZh: '在账单错误和顾客投诉情境中非常有用。',
    exampleEn: 'The passenger said the taxi driver had overcharged her.',
    exampleKo: '그 승객은 택시 기사가 자신에게 바가지를 씌웠다고 말했습니다.',
    exampleZh: '那名乘客说出租车司机向她多收了钱。',
    collocations: ['overcharge a customer', 'credit card overcharge', 'accidentally overcharge'],
  }),
  makeEntry({
    id: 'penalty',
    word: 'penalty',
    usIpa: '/ˈpenəlti/',
    ukIpa: '/ˈpenəlti/',
    importance: 4,
    topics: ['community-civic', 'travel-transit', 'shopping-banking'],
    ko: '벌금; 불이익',
    zh: '罚款；处罚',
    englishDefinition: 'a punishment, fee, or disadvantage for breaking a rule or ending something early',
    noteEn: 'Important for contracts, permits, cancellations, and public rules.',
    noteKo: '계약, 허가증, 취소, 공공 규정에서 중요한 단어입니다.',
    noteZh: '在合同、许可证、取消和公共规定中很重要。',
    exampleEn: 'There is no penalty if you cancel at least twenty-four hours early.',
    exampleKo: '24시간 전에 취소하면 불이익이 없습니다.',
    exampleZh: '如果至少提前二十四小时取消，就不会有罚金。',
    collocations: ['late penalty', 'financial penalty', 'penalty fee'],
  }),
  makeEntry({
    id: 'preference',
    word: 'preference',
    usIpa: '/ˈpref(ə)rəns/',
    ukIpa: '/ˈpref(ə)rəns/',
    importance: 3,
    topics: ['people-relationships', 'travel-transit', 'problem-solving'],
    ko: '선호; 선호도',
    zh: '偏好；喜好',
    englishDefinition: 'a greater liking for one choice than another',
    noteEn: 'Useful when comparing options or explaining why someone chose one plan.',
    noteKo: '여러 선택지를 비교하거나 선택 이유를 설명할 때 유용합니다.',
    noteZh: '在比较选项或解释选择原因时很有用。',
    exampleEn: 'Please tell us your seating preference when you book the ticket.',
    exampleKo: '티켓을 예약할 때 좌석 선호를 알려 주세요.',
    exampleZh: '订票时请告诉我们你的座位偏好。',
    collocations: ['personal preference', 'customer preference', 'state a preference'],
  }),
  makeEntry({
    id: 'qualify',
    word: 'qualify',
    usIpa: '/ˈkwɑːləˌfaɪ/',
    ukIpa: '/ˈkwɒlɪfaɪ/',
    importance: 4,
    topics: ['community-civic', 'shopping-banking', 'work-school'],
    ko: '자격이 되다',
    zh: '符合资格',
    englishDefinition: 'to meet the conditions needed for something',
    noteEn: 'Often decides the correct answer in benefit, discount, and admission tasks.',
    noteKo: '혜택, 할인, 입학 문제에서 정답을 가르는 핵심 단어입니다.',
    noteZh: '在福利、折扣和录取任务中常是决定答案的关键词。',
    exampleEn: 'Low-income families may qualify for additional support.',
    exampleKo: '저소득 가정은 추가 지원 대상이 될 수 있습니다.',
    exampleZh: '低收入家庭可能符合额外补助资格。',
    collocations: ['qualify for', 'qualify as', 'fully qualified'],
  }),
  makeEntry({
    id: 'quota',
    word: 'quota',
    usIpa: '/ˈkwoʊtə/',
    ukIpa: '/ˈkwəʊtə/',
    importance: 3,
    topics: ['community-civic', 'work-school', 'news-opinion'],
    ko: '할당량; 정원',
    zh: '配额；限额',
    englishDefinition: 'a fixed number or amount that is allowed or required',
    noteEn: 'Helpful for program limits, registration caps, and allocation questions.',
    noteKo: '프로그램 정원, 등록 제한, 배정량을 말할 때 유용합니다.',
    noteZh: '在项目名额、注册上限和分配量问题中很有用。',
    exampleEn: 'The summer class reached its quota in less than two days.',
    exampleKo: '여름 수업은 이틀도 안 되어 정원을 채웠습니다.',
    exampleZh: '暑期课程不到两天就达到名额上限了。',
    collocations: ['meet a quota', 'quota system', 'admission quota'],
  }),
  makeEntry({
    id: 'rebate',
    word: 'rebate',
    usIpa: '/ˈriːbeɪt/',
    ukIpa: '/ˈriːbeɪt/',
    importance: 3,
    topics: ['shopping-banking', 'community-civic'],
    ko: '환급금; 리베이트',
    zh: '返现；回扣',
    englishDefinition: 'money paid back after someone buys something or pays too much',
    noteEn: 'Different from a refund because it often comes later after a claim or form.',
    noteKo: '즉시 환불이 아니라 신청 후 나중에 돌려받는 경우가 많아 refund와 다릅니다.',
    noteZh: '和 refund 不同，它通常是提交申请后稍后返还。',
    exampleEn: 'Customers can apply for a rebate after buying the energy-efficient appliance.',
    exampleKo: '고객은 에너지 효율이 높은 가전제품을 구매한 뒤 환급금을 신청할 수 있습니다.',
    exampleZh: '顾客购买节能家电后可以申请返现。',
    collocations: ['tax rebate', 'mail-in rebate', 'rebate form'],
  }),
  makeEntry({
    id: 'replacement',
    word: 'replacement',
    usIpa: '/rɪˈpleɪsmənt/',
    ukIpa: '/rɪˈpleɪsmənt/',
    importance: 4,
    topics: ['shopping-banking', 'housing-services', 'technology-communication'],
    ko: '교체; 대체품',
    zh: '更换；替代品',
    englishDefinition: 'something that takes the place of another thing, or the act of changing it',
    noteEn: 'Common in repair, product return, and equipment service tasks.',
    noteKo: '수리, 반품, 장비 서비스 문제에서 자주 나옵니다.',
    noteZh: '常见于维修、退货和设备服务情境。',
    exampleEn: 'A replacement card will arrive within five business days.',
    exampleKo: '교체 카드는 영업일 기준 5일 이내에 도착할 것입니다.',
    exampleZh: '补发的新卡会在五个工作日内寄到。',
    collocations: ['replacement card', 'replacement part', 'free replacement'],
  }),
  makeEntry({
    id: 'requirement',
    word: 'requirement',
    usIpa: '/rɪˈkwaɪərmənt/',
    ukIpa: '/rɪˈkwaɪəmənt/',
    importance: 5,
    topics: ['community-civic', 'work-school', 'travel-transit'],
    ko: '요건; 요구 사항',
    zh: '要求；条件',
    englishDefinition: 'something that is needed or must be done',
    noteEn: 'One of the most important CELPIP reading words because questions often test conditions.',
    noteKo: '조건과 필수 사항을 묻는 문제가 많아 CELPIP 읽기에서 매우 중요합니다.',
    noteZh: '因为常考条件和必须事项，所以是 CELPIP 阅读高频词。',
    exampleEn: 'A passport is a basic requirement for international travel.',
    exampleKo: '여권은 해외여행의 기본 요건입니다.',
    exampleZh: '护照是国际旅行的基本要求。',
    collocations: ['minimum requirement', 'meet the requirement', 'entry requirement'],
  }),
  makeEntry({
    id: 'restore',
    word: 'restore',
    usIpa: '/rɪˈstɔːr/',
    ukIpa: '/rɪˈstɔː/',
    importance: 3,
    topics: ['technology-communication', 'housing-services', 'health-emergency'],
    ko: '복구하다; 회복시키다',
    zh: '恢复；修复',
    englishDefinition: 'to bring something back to its earlier working or healthy state',
    noteEn: 'Useful for internet, power, account, and health recovery contexts.',
    noteKo: '인터넷, 전기, 계정, 건강 회복 문맥에서 유용합니다.',
    noteZh: '在网络、电力、账户和健康恢复语境里很实用。',
    exampleEn: 'Technicians worked overnight to restore power to the area.',
    exampleKo: '기술자들은 그 지역의 전기를 복구하기 위해 밤새 작업했습니다.',
    exampleZh: '技术人员连夜工作以恢复该地区的供电。',
    collocations: ['restore service', 'restore power', 'restore access'],
  }),
  makeEntry({
    id: 'shipment',
    word: 'shipment',
    usIpa: '/ˈʃɪpmənt/',
    ukIpa: '/ˈʃɪpmənt/',
    importance: 3,
    topics: ['shopping-banking', 'technology-communication'],
    ko: '배송물; 선적',
    zh: '货运；发货批次',
    englishDefinition: 'a load of goods that is sent somewhere',
    noteEn: 'Useful in delivery complaints, tracking emails, and ordering problems.',
    noteKo: '배송 불만, 추적 이메일, 주문 문제에서 자주 씁니다.',
    noteZh: '在配送投诉、物流追踪邮件和订单问题中很常用。',
    exampleEn: 'The shipment was delayed because of customs clearance.',
    exampleKo: '통관 때문에 배송물이 지연되었습니다.',
    exampleZh: '由于清关原因，这批货物延迟了。',
    collocations: ['late shipment', 'shipment tracking', 'international shipment'],
  }),
  makeEntry({
    id: 'shortage',
    word: 'shortage',
    usIpa: '/ˈʃɔːrtɪdʒ/',
    ukIpa: '/ˈʃɔːtɪdʒ/',
    importance: 4,
    topics: ['news-opinion', 'housing-services', 'health-emergency'],
    ko: '부족; 공급난',
    zh: '短缺',
    englishDefinition: 'a situation in which there is not enough of something',
    noteEn: 'Common in news reports, housing discussions, and supply issues.',
    noteKo: '뉴스 리포트, 주거 문제, 공급 부족 상황에서 자주 나옵니다.',
    noteZh: '常见于新闻报道、住房问题和供应短缺情境。',
    exampleEn: 'The clinic faced a temporary shortage of flu vaccines.',
    exampleKo: '그 병원은 독감 백신이 일시적으로 부족했습니다.',
    exampleZh: '那家诊所暂时出现了流感疫苗短缺。',
    collocations: ['housing shortage', 'staff shortage', 'shortage of supplies'],
  }),
  makeEntry({
    id: 'subsidy',
    word: 'subsidy',
    usIpa: '/ˈsʌbsədi/',
    ukIpa: '/ˈsʌbsɪdi/',
    importance: 3,
    topics: ['community-civic', 'news-opinion', 'shopping-banking'],
    ko: '보조금',
    zh: '补贴',
    englishDefinition: 'money given by a government or organization to help reduce costs',
    noteEn: 'Good for public policy, transit, energy, and family-support topics.',
    noteKo: '공공 정책, 교통, 에너지, 가정 지원 주제에서 유용합니다.',
    noteZh: '在公共政策、交通、能源和家庭补助话题里很实用。',
    exampleEn: 'The city offers a subsidy for low-income transit users.',
    exampleKo: '시는 저소득 교통 이용자에게 보조금을 제공합니다.',
    exampleZh: '市政府为低收入公共交通使用者提供补贴。',
    collocations: ['government subsidy', 'housing subsidy', 'subsidy program'],
  }),
  makeEntry({
    id: 'suspend',
    word: 'suspend',
    usIpa: '/səˈspend/',
    ukIpa: '/səˈspend/',
    importance: 4,
    topics: ['community-civic', 'technology-communication', 'work-school'],
    ko: '중단하다; 정지시키다',
    zh: '暂停；停用',
    englishDefinition: 'to stop something temporarily from continuing or being used',
    noteEn: 'Often appears in account, service, class, and permit situations.',
    noteKo: '계정, 서비스, 수업, 허가 중지 상황에서 자주 보입니다.',
    noteZh: '常出现在账户、服务、课程和许可证暂停情境中。',
    exampleEn: 'The account may be suspended if payment is not received by Friday.',
    exampleKo: '금요일까지 결제가 확인되지 않으면 계정이 정지될 수 있습니다.',
    exampleZh: '如果周五前未收到付款，账户可能会被暂停。',
    collocations: ['temporarily suspend', 'service suspended', 'suspend an account'],
  }),
  makeEntry({
    id: 'transfer',
    word: 'transfer',
    usIpa: '/trænsˈfɝː/',
    ukIpa: '/trænsˈfɜː/',
    importance: 4,
    topics: ['shopping-banking', 'travel-transit', 'work-school'],
    ko: '이체하다; 옮기다; 환승',
    zh: '转账；转移；换乘',
    englishDefinition: 'to move money, people, or things from one place to another',
    noteEn: 'Another context-dependent word that is frequent in CELPIP tasks.',
    noteKo: '문맥에 따라 의미가 달라지는, CELPIP 빈출 단어입니다.',
    noteZh: '又一个会随语境变化的 CELPIP 高频词。',
    exampleEn: 'You can transfer the balance to another account online.',
    exampleKo: '잔액을 온라인으로 다른 계좌에 이체할 수 있습니다.',
    exampleZh: '你可以在线把余额转到另一个账户。',
    collocations: ['bank transfer', 'transfer station', 'transfer credits'],
  }),
  makeEntry({
    id: 'upgrade',
    word: 'upgrade',
    usIpa: '/ʌpˈɡreɪd/',
    ukIpa: '/ʌpˈɡreɪd/',
    importance: 3,
    topics: ['technology-communication', 'travel-transit', 'housing-services'],
    ko: '업그레이드하다; 업그레이드',
    zh: '升级；升级版',
    englishDefinition: 'to improve something to a better version or level',
    noteEn: 'Useful for software, travel seats, and service plans.',
    noteKo: '소프트웨어, 좌석, 서비스 플랜 업그레이드에서 자주 씁니다.',
    noteZh: '常用于软件、座位和服务方案升级。',
    exampleEn: 'Guests can upgrade to a larger room for an extra fee.',
    exampleKo: '고객은 추가 요금을 내고 더 큰 방으로 업그레이드할 수 있습니다.',
    exampleZh: '客人可以支付额外费用升级到更大的房间。',
    collocations: ['system upgrade', 'free upgrade', 'upgrade fee'],
  }),
  makeEntry({
    id: 'violate',
    word: 'violate',
    usIpa: '/ˈvaɪəˌleɪt/',
    ukIpa: '/ˈvaɪəleɪt/',
    importance: 4,
    topics: ['community-civic', 'housing-services', 'people-relationships'],
    ko: '위반하다',
    zh: '违反',
    englishDefinition: 'to break a rule, law, or agreement',
    noteEn: 'A strong rule-based word in notices and complaint cases.',
    noteKo: '공지문과 민원 상황에서 규정 위반을 나타낼 때 중요한 단어입니다.',
    noteZh: '在通知和投诉情境中表示违反规定时很重要。',
    exampleEn: 'Residents who violate the parking rules may lose their permits.',
    exampleKo: '주차 규정을 위반한 주민은 허가증을 잃을 수 있습니다.',
    exampleZh: '违反停车规定的住户可能会失去许可证。',
    collocations: ['violate a rule', 'violate the policy', 'violate privacy'],
  }),
  makeEntry({
    id: 'warranty',
    word: 'warranty',
    usIpa: '/ˈwɔːrənti/',
    ukIpa: '/ˈwɒrənti/',
    importance: 4,
    topics: ['shopping-banking', 'technology-communication', 'housing-services'],
    ko: '보증; 품질 보증서',
    zh: '保修；保修单',
    englishDefinition: 'a written promise to repair or replace a product if it has problems',
    noteEn: 'Very useful for product, appliance, and repair conversations.',
    noteKo: '제품, 가전, 수리 대화에서 매우 유용한 단어입니다.',
    noteZh: '在产品、家电和维修对话中非常有用。',
    exampleEn: 'The printer is still under warranty, so the repair should be free.',
    exampleKo: '그 프린터는 아직 보증 기간 안이라 수리가 무료여야 합니다.',
    exampleZh: '那台打印机仍在保修期内，所以维修应该是免费的。',
    collocations: ['under warranty', 'warranty period', 'extended warranty'],
  }),
  makeEntry({
    id: 'witness',
    word: 'witness',
    usIpa: '/ˈwɪtnəs/',
    ukIpa: '/ˈwɪtnəs/',
    importance: 3,
    topics: ['community-civic', 'news-opinion', 'people-relationships'],
    ko: '목격자; 목격하다',
    zh: '目击者；目睹',
    englishDefinition: 'a person who sees an event happen, or the act of seeing it happen',
    noteEn: 'Useful in reports, public safety notices, and incident descriptions.',
    noteKo: '리포트, 공공 안전 공지, 사건 설명에서 유용합니다.',
    noteZh: '在报道、公共安全通知和事件描述中很实用。',
    exampleEn: 'Police asked any witness to contact the local station.',
    exampleKo: '경찰은 목격자가 있으면 지역 경찰서에 연락해 달라고 요청했습니다.',
    exampleZh: '警方请求任何目击者与当地警局联系。',
    collocations: ['eyewitness account', 'witness statement', 'key witness'],
  }),
  makeEntry({
    id: 'workshop',
    word: 'workshop',
    usIpa: '/ˈwɝːkˌʃɑːp/',
    ukIpa: '/ˈwɜːkʃɒp/',
    importance: 3,
    topics: ['work-school', 'community-civic'],
    ko: '워크숍; 실습 세션',
    zh: '研讨会；工作坊',
    englishDefinition: 'a session where people practice or learn a skill together',
    noteEn: 'Shows up in campus, library, volunteer, and staff-training schedules.',
    noteKo: '학교, 도서관, 봉사, 직원 교육 일정에서 자주 보입니다.',
    noteZh: '常见于校园、图书馆、志愿者和员工培训日程。',
    exampleEn: 'The writing workshop is open to both new and returning students.',
    exampleKo: '그 글쓰기 워크숍은 신입생과 재학생 모두에게 열려 있습니다.',
    exampleZh: '写作工作坊对新生和老生都开放。',
    collocations: ['attend a workshop', 'skills workshop', 'weekend workshop'],
  }),
]

const CELPIP_VOCABULARY_ADDED = [
  makeEntry({
    id: 'reimburse',
    word: 'reimburse',
    usIpa: '/ˌriːɪmˈbɜːrs/',
    ukIpa: '/ˌriːɪmˈbɜːs/',
    importance: 4,
    topics: ['shopping-banking', 'work-school'],
    ko: '(비용을) 환급하다; 상환하다',
    zh: '报销；偿还',
    englishDefinition: 'to pay someone back money they have spent',
    noteEn: 'Common in emails about refunds, expenses, and workplace claims.',
    noteKo: '환불, 경비, 직장 비용 청구 관련 이메일에서 자주 나옵니다.',
    noteZh: '常见于关于退款、费用和职场报销的邮件中。',
    exampleEn: 'The company will reimburse you for travel expenses.',
    exampleKo: '회사가 출장 경비를 환급해 줄 것입니다.',
    exampleZh: '公司将为你报销差旅费。',
    collocations: ['reimburse expenses', 'reimburse the cost', 'fully reimburse'],
  }),
  makeEntry({
    id: 'tenant',
    word: 'tenant',
    usIpa: '/ˈtenənt/',
    ukIpa: '/ˈtenənt/',
    importance: 4,
    topics: ['housing-services', 'community-civic'],
    ko: '세입자; 임차인',
    zh: '租客；承租人',
    englishDefinition: 'a person who rents and lives in a property',
    noteEn: 'Frequent in housing tasks about rent, repairs, and lease rules.',
    noteKo: '임대료, 수리, 임대 규칙 관련 주거 문제에서 자주 나옵니다.',
    noteZh: '常见于关于租金、维修和租约规定的住房任务中。',
    exampleEn: 'The tenant reported a leaking pipe to the building manager.',
    exampleKo: '세입자는 건물 관리인에게 파이프 누수를 신고했습니다.',
    exampleZh: '租客向物业经理报告了管道漏水。',
    collocations: ['a new tenant', 'tenant rights', 'long-term tenant'],
  }),
  makeEntry({
    id: 'utilities',
    word: 'utilities',
    usIpa: '/juːˈtɪlətiz/',
    ukIpa: '/juːˈtɪlətiz/',
    importance: 4,
    topics: ['housing-services', 'shopping-banking'],
    ko: '공과금; 공공요금(전기·수도·가스)',
    zh: '公用事业费（水电煤）',
    englishDefinition: 'basic services such as electricity, water, and gas, or their bills',
    noteEn: 'Common in housing, budgeting, and rental-listing contexts.',
    noteKo: '주거, 예산, 임대 공고 맥락에서 자주 나옵니다.',
    noteZh: '常见于住房、预算和租房广告语境中。',
    exampleEn: 'Rent for this apartment does not include utilities.',
    exampleKo: '이 아파트의 임대료에는 공과금이 포함되어 있지 않습니다.',
    exampleZh: '这套公寓的房租不包含水电煤费用。',
    collocations: ['pay utilities', 'utility bills', 'include utilities'],
  }),
  makeEntry({
    id: 'renovate',
    word: 'renovate',
    usIpa: '/ˈrenəveɪt/',
    ukIpa: '/ˈrenəveɪt/',
    importance: 3,
    topics: ['housing-services', 'community-civic'],
    ko: '개조하다; 보수하다',
    zh: '翻新；装修',
    englishDefinition: 'to repair and improve a building or room',
    noteEn: 'Appears in housing, community projects, and repair discussions.',
    noteKo: '주거, 지역 프로젝트, 수리 논의에서 나옵니다.',
    noteZh: '出现在住房、社区项目和维修讨论中。',
    exampleEn: 'They plan to renovate the community center next spring.',
    exampleKo: '그들은 내년 봄에 커뮤니티 센터를 개조할 계획입니다.',
    exampleZh: '他们计划明年春天翻新社区中心。',
    collocations: ['renovate a home', 'fully renovated', 'renovate the kitchen'],
  }),
  makeEntry({
    id: 'overdue',
    word: 'overdue',
    usIpa: '/ˌoʊvərˈduː/',
    ukIpa: '/ˌəʊvəˈdjuː/',
    importance: 3,
    topics: ['shopping-banking', 'work-school'],
    ko: '기한이 지난; 연체된',
    zh: '逾期的；过期未还的',
    englishDefinition: 'not done or paid by the expected time',
    noteEn: 'Common in reminders about payments, returns, and deadlines.',
    noteKo: '결제, 반납, 마감 관련 알림에서 자주 나옵니다.',
    noteZh: '常见于关于付款、归还和截止日期的提醒中。',
    exampleEn: 'Please return the overdue library books to avoid a fine.',
    exampleKo: '벌금을 피하려면 연체된 도서관 책을 반납해 주세요.',
    exampleZh: '请归还逾期的图书馆书籍以免罚款。',
    collocations: ['overdue payment', 'long overdue', 'overdue books'],
  }),
  makeEntry({
    id: 'notify',
    word: 'notify',
    usIpa: '/ˈnoʊtɪfaɪ/',
    ukIpa: '/ˈnəʊtɪfaɪ/',
    importance: 4,
    topics: ['work-school', 'technology-communication'],
    ko: '알리다; 통지하다',
    zh: '通知；告知',
    englishDefinition: 'to formally tell someone about something',
    noteEn: 'Frequent in formal notices, emails, and service messages.',
    noteKo: '공식 공지, 이메일, 서비스 메시지에서 자주 나옵니다.',
    noteZh: '常见于正式通知、邮件和服务信息中。',
    exampleEn: 'Please notify the office if your contact details change.',
    exampleKo: '연락처가 변경되면 사무실에 알려 주세요.',
    exampleZh: '如果你的联系方式变更，请通知办公室。',
    collocations: ['notify in advance', 'notify the office', 'notify customers'],
  }),
  makeEntry({
    id: 'voucher',
    word: 'voucher',
    usIpa: '/ˈvaʊtʃər/',
    ukIpa: '/ˈvaʊtʃə/',
    importance: 3,
    topics: ['shopping-banking', 'travel-transit'],
    ko: '상품권; 쿠폰; 교환권',
    zh: '代金券；优惠券',
    englishDefinition: 'a printed or digital ticket exchanged for goods or a discount',
    noteEn: 'Common in shopping, refunds, and promotion contexts.',
    noteKo: '쇼핑, 환불, 프로모션 맥락에서 자주 나옵니다.',
    noteZh: '常见于购物、退款和促销语境中。',
    exampleEn: 'You can use this voucher for a free coffee at any branch.',
    exampleKo: '이 교환권으로 어느 지점에서나 무료 커피를 받을 수 있습니다.',
    exampleZh: '你可以在任何分店用这张代金券兑换一杯免费咖啡。',
    collocations: ['gift voucher', 'use a voucher', 'discount voucher'],
  }),
  makeEntry({
    id: 'inquiry',
    word: 'inquiry',
    usIpa: '/ˈɪnkwəri/',
    ukIpa: '/ɪnˈkwaɪəri/',
    importance: 3,
    topics: ['technology-communication', 'community-civic'],
    ko: '문의; 조회',
    zh: '咨询；询问',
    englishDefinition: 'a request for information',
    noteEn: 'Common in customer service, emails, and public notices.',
    noteKo: '고객 서비스, 이메일, 공공 공지에서 자주 나옵니다.',
    noteZh: '常见于客户服务、邮件和公共通知中。',
    exampleEn: 'We received several inquiries about the new schedule.',
    exampleKo: '우리는 새 일정에 대한 여러 문의를 받았습니다.',
    exampleZh: '我们收到了几条关于新时间表的咨询。',
    collocations: ['make an inquiry', 'general inquiries', 'respond to an inquiry'],
  }),
  makeEntry({
    id: 'referral',
    word: 'referral',
    usIpa: '/rɪˈfɜːrəl/',
    ukIpa: '/rɪˈfɜːrəl/',
    importance: 3,
    topics: ['health-emergency', 'community-civic'],
    ko: '(전문가·기관으로의) 의뢰; 소개',
    zh: '转诊；推荐',
    englishDefinition: 'the act of sending someone to another person or place for help',
    noteEn: 'Frequent in health, clinic, and service-navigation tasks.',
    noteKo: '건강, 진료, 서비스 안내 과제에서 자주 나옵니다.',
    noteZh: '常见于健康、诊所和服务引导任务中。',
    exampleEn: 'The doctor gave her a referral to a specialist.',
    exampleKo: '의사는 그녀에게 전문의 의뢰서를 주었습니다.',
    exampleZh: '医生给她开了转诊到专科医生的介绍。',
    collocations: ['a referral to a specialist', 'referral letter', 'make a referral'],
  }),
  makeEntry({
    id: 'insurance',
    word: 'insurance',
    usIpa: '/ɪnˈʃʊrəns/',
    ukIpa: '/ɪnˈʃʊərəns/',
    importance: 4,
    topics: ['health-emergency', 'shopping-banking'],
    ko: '보험',
    zh: '保险',
    englishDefinition: 'an arrangement where you pay a company to cover possible loss or damage',
    noteEn: 'Common in health, travel, banking, and emergency contexts.',
    noteKo: '건강, 여행, 은행, 응급 맥락에서 자주 나옵니다.',
    noteZh: '常见于健康、旅行、银行和紧急语境中。',
    exampleEn: 'Make sure your travel insurance covers medical costs.',
    exampleKo: '여행자 보험이 의료비를 보장하는지 확인하세요.',
    exampleZh: '确保你的旅行保险涵盖医疗费用。',
    collocations: ['health insurance', 'insurance policy', 'insurance coverage'],
  }),
  makeEntry({
    id: 'subscription',
    word: 'subscription',
    usIpa: '/səbˈskrɪpʃən/',
    ukIpa: '/səbˈskrɪpʃən/',
    importance: 3,
    topics: ['technology-communication', 'shopping-banking'],
    ko: '구독; 정기 결제',
    zh: '订阅；订购',
    englishDefinition: 'a payment to receive a service or product regularly',
    noteEn: 'Common in apps, media, and recurring-payment messages.',
    noteKo: '앱, 미디어, 정기 결제 메시지에서 자주 나옵니다.',
    noteZh: '常见于应用、媒体和定期付款信息中。',
    exampleEn: 'You can cancel your subscription at any time.',
    exampleKo: '언제든지 구독을 취소할 수 있습니다.',
    exampleZh: '你可以随时取消订阅。',
    collocations: ['monthly subscription', 'cancel a subscription', 'subscription fee'],
  }),
  makeEntry({
    id: 'mortgage',
    word: 'mortgage',
    usIpa: '/ˈmɔːrɡɪdʒ/',
    ukIpa: '/ˈmɔːɡɪdʒ/',
    importance: 3,
    topics: ['housing-services', 'shopping-banking'],
    ko: '주택 담보 대출; 모기지',
    zh: '按揭；抵押贷款',
    englishDefinition: 'a loan used to buy property, paid back over many years',
    noteEn: 'Appears in banking, housing, and long-term finance topics.',
    noteKo: '은행, 주거, 장기 금융 주제에서 나옵니다.',
    noteZh: '出现在银行、住房和长期金融话题中。',
    exampleEn: 'They took out a mortgage to buy their first home.',
    exampleKo: '그들은 첫 집을 사기 위해 주택 담보 대출을 받았습니다.',
    exampleZh: '他们办理了按揭贷款来买第一套房。',
    collocations: ['take out a mortgage', 'mortgage payment', 'mortgage rate'],
  }),
]

const CELPIP_VOCABULARY_BASE = [
  ...CELPIP_VOCABULARY_CORE,
  ...CELPIP_VOCABULARY_EXTRA,
  ...CELPIP_VOCABULARY_ADDED,
]

export const CELPIP_VOCABULARY = [...CELPIP_VOCABULARY_BASE]
