export const PTE_VOCAB_TOPICS = [
  { id: 'speaking-listening', label: 'Speaking & Listening', shortLabel: 'Speaking', emoji: '🎤', tone: 'Pronunciation, paraphrase, lecture listening, oral flow' },
  { id: 'academic-reading', label: 'Academic Reading', shortLabel: 'Reading', emoji: '📖', tone: 'Inference, structure, research-style passages' },
  { id: 'writing-structure', label: 'Writing & Structure', shortLabel: 'Writing', emoji: '✍️', tone: 'Summaries, arguments, cohesion, essay control' },
  { id: 'campus-life', label: 'Campus & Study Life', shortLabel: 'Campus', emoji: '🎓', tone: 'Lectures, assignments, orientation, fees, study plans' },
  { id: 'work-professional', label: 'Work & Professional English', shortLabel: 'Work', emoji: '💼', tone: 'Projects, meetings, priorities, workplace communication' },
  { id: 'charts-data', label: 'Charts & Data Language', shortLabel: 'Data', emoji: '📊', tone: 'Graphs, trends, ratios, changes, comparisons' },
  { id: 'technology-science', label: 'Technology & Science', shortLabel: 'Tech', emoji: '🧪', tone: 'Innovation, devices, simulation, digital contexts' },
  { id: 'health-society', label: 'Health & Society', shortLabel: 'Health', emoji: '🩺', tone: 'Healthcare, resilience, social support, wellbeing' },
  { id: 'environment-policy', label: 'Environment & Policy', shortLabel: 'Policy', emoji: '🌿', tone: 'Regulation, sustainability, resources, public policy' },
  { id: 'opinion-argument', label: 'Opinion & Argument', shortLabel: 'Argument', emoji: '🗣️', tone: 'Claims, evidence, perspective, justification' },
]

const PTE_TOPIC_NOTES = {
  'speaking-listening': {
    en: 'Useful for Repeat Sentence, Describe Image, Retell Lecture, and Summarize Spoken Text.',
    ko: 'Repeat Sentence, Describe Image, Retell Lecture, Summarize Spoken Text에서 유용합니다.',
    zh: '适用于 Repeat Sentence、Describe Image、Retell Lecture 和 Summarize Spoken Text。',
  },
  'academic-reading': {
    en: 'High-value for reading passages, reorder paragraphs, and multiple-choice inference.',
    ko: '리딩 지문, 문단 재배열, 추론형 객관식에서 가치가 높습니다.',
    zh: '对阅读文章、段落重组和推断题非常重要。',
  },
  'writing-structure': {
    en: 'Helpful when you need clearer summaries, stronger links, and better academic tone.',
    ko: '더 명확한 요약, 강한 연결, 학문적 톤이 필요할 때 도움이 됩니다.',
    zh: '在需要更清晰总结、更强衔接和更学术语气时很有帮助。',
  },
  'campus-life': {
    en: 'Common in university notices, lectures, student emails, and study planning tasks.',
    ko: '대학 공지, 강의, 학생 이메일, 학습 계획 과제에서 자주 나옵니다.',
    zh: '常见于大学通知、讲座、学生邮件和学习计划任务中。',
  },
  'work-professional': {
    en: 'Useful for project updates, teamwork language, scheduling, and formal workplace responses.',
    ko: '프로젝트 업데이트, 협업 표현, 일정 조정, 직장 공식 응답에 유용합니다.',
    zh: '适用于项目更新、团队协作、时间安排和正式职场表达。',
  },
  'charts-data': {
    en: 'Important for describing graphs, comparing figures, and reporting changes accurately.',
    ko: '그래프 설명, 수치 비교, 변화 정확 보고에 중요합니다.',
    zh: '对描述图表、比较数据和准确报告变化很重要。',
  },
  'technology-science': {
    en: 'Appears often in modern lecture topics, science passages, and innovation discussions.',
    ko: '현대 강의 주제, 과학 지문, 혁신 토론에서 자주 등장합니다.',
    zh: '常出现在现代讲座主题、科学文章和创新讨论中。',
  },
  'health-society': {
    en: 'Useful for lectures and articles about care, wellbeing, psychology, and public life.',
    ko: '돌봄, 웰빙, 심리, 공공생활 관련 강의와 기사에서 유용합니다.',
    zh: '适用于护理、健康、心理和公共生活相关讲座与文章。',
  },
  'environment-policy': {
    en: 'High-frequency in sustainability, climate, regulation, and policy-based reading tasks.',
    ko: '지속 가능성, 기후, 규제, 정책 중심 리딩 문제에서 자주 나옵니다.',
    zh: '在可持续发展、气候、监管和政策类阅读中频率很高。',
  },
  'opinion-argument': {
    en: 'Useful when you must explain a claim, support an opinion, or compare viewpoints.',
    ko: '주장을 설명하거나 의견을 뒷받침하고 관점을 비교할 때 유용합니다.',
    zh: '在解释观点、支持意见或比较立场时很有用。',
  },
}

const makeEntry = ({
  id,
  word,
  usIpa,
  ukIpa = usIpa,
  importance = 3,
  topics,
  ko,
  zh,
  englishDefinition,
  exampleEn,
  exampleKo,
  exampleZh,
  collocations = [],
}) => {
  const topicNote = PTE_TOPIC_NOTES[topics?.[0]] || PTE_TOPIC_NOTES['academic-reading']
  return {
    id,
    word,
    usIpa,
    ukIpa,
    importance,
    topics,
    meaning: { en: englishDefinition, ko, zh },
    note: topicNote,
    collocations,
    examples: [
      {
        en: exampleEn,
        ko: exampleKo,
        zh: exampleZh,
      },
    ],
  }
}

export const PTE_VOCAB_IMPORTANCE_LABELS = {
  5: 'Core',
  4: 'High-use',
  3: 'Useful',
}

const PTE_VOCABULARY_BASE = [
  makeEntry({
    id: 'articulate',
    word: 'articulate',
    usIpa: '/ɑrˈtɪkjəleɪt/',
    ukIpa: '/ɑːˈtɪkjəleɪt/',
    importance: 5,
    topics: ['speaking-listening', 'opinion-argument'],
    ko: '명확히 표현하다; 또렷한',
    zh: '清楚表达；口齿清晰的',
    englishDefinition: 'to express an idea clearly and effectively',
    exampleEn: 'A strong speaker can articulate the main idea without repeating every phrase.',
    exampleKo: '강한 화자는 모든 표현을 반복하지 않고도 핵심 생각을 명확히 표현할 수 있습니다.',
    exampleZh: '优秀的说话者无需重复每个短语，也能清楚表达核心观点。',
    collocations: ['articulate clearly', 'articulate a point', 'articulate response'],
  }),
  makeEntry({
    id: 'paraphrase',
    word: 'paraphrase',
    usIpa: '/ˈpærəˌfreɪz/',
    ukIpa: '/ˈpærəfreɪz/',
    importance: 5,
    topics: ['speaking-listening', 'writing-structure'],
    ko: '바꾸어 표현하다; 의역하다',
    zh: '改述；意译',
    englishDefinition: 'to express the same meaning using different words',
    exampleEn: 'In PTE, you often need to paraphrase a sentence instead of copying it word for word.',
    exampleKo: 'PTE에서는 문장을 그대로 베끼기보다 바꾸어 표현해야 하는 경우가 많습니다.',
    exampleZh: '在 PTE 中，你常常需要改述句子，而不是逐字照搬。',
    collocations: ['paraphrase accurately', 'paraphrase a sentence', 'paraphrase the source'],
  }),
  makeEntry({
    id: 'infer',
    word: 'infer',
    usIpa: '/ɪnˈfɜr/',
    ukIpa: '/ɪnˈfɜː/',
    importance: 5,
    topics: ['speaking-listening', 'academic-reading'],
    ko: '추론하다',
    zh: '推断',
    englishDefinition: 'to form a conclusion from evidence rather than from a direct statement',
    exampleEn: 'Readers must infer the writer’s attitude from the tone of the paragraph.',
    exampleKo: '독자는 문단의 어조를 통해 필자의 태도를 추론해야 합니다.',
    exampleZh: '读者必须根据段落的语气来推断作者的态度。',
    collocations: ['infer meaning', 'infer from context', 'infer the result'],
  }),
  makeEntry({
    id: 'fluency',
    word: 'fluency',
    usIpa: '/ˈfluənsi/',
    ukIpa: '/ˈfluːənsi/',
    importance: 4,
    topics: ['speaking-listening'],
    ko: '유창성',
    zh: '流利度',
    englishDefinition: 'the ability to speak or write smoothly and naturally',
    exampleEn: 'Fluency improves when you connect ideas smoothly instead of pausing after each word.',
    exampleKo: '단어마다 멈추지 않고 생각을 자연스럽게 연결하면 유창성이 향상됩니다.',
    exampleZh: '如果你能自然连接想法，而不是每个词后都停顿，流利度就会提高。',
    collocations: ['oral fluency', 'improve fluency', 'fluency score'],
  }),
  makeEntry({
    id: 'hesitation',
    word: 'hesitation',
    usIpa: '/ˌhezəˈteɪʃən/',
    ukIpa: '/ˌhezɪˈteɪʃən/',
    importance: 4,
    topics: ['speaking-listening'],
    ko: '망설임; 주저',
    zh: '犹豫；停顿',
    englishDefinition: 'a pause caused by uncertainty or lack of readiness',
    exampleEn: 'Too much hesitation can reduce the natural flow of your response.',
    exampleKo: '지나친 망설임은 답변의 자연스러운 흐름을 떨어뜨릴 수 있습니다.',
    exampleZh: '过多的犹豫会降低回答的自然流畅度。',
    collocations: ['brief hesitation', 'without hesitation', 'hesitation marker'],
  }),
  makeEntry({
    id: 'analyze',
    word: 'analyze',
    usIpa: '/ˈænəˌlaɪz/',
    ukIpa: '/ˈænəlaɪz/',
    importance: 5,
    topics: ['academic-reading', 'opinion-argument'],
    ko: '분석하다',
    zh: '分析',
    englishDefinition: 'to examine something carefully in order to understand it',
    exampleEn: 'The article asks students to analyze the causes of rapid urban growth.',
    exampleKo: '그 글은 학생들에게 급속한 도시 성장의 원인을 분석하라고 요구합니다.',
    exampleZh: '这篇文章要求学生分析城市快速增长的原因。',
    collocations: ['analyze data', 'analyze results', 'analyze the issue'],
  }),
  makeEntry({
    id: 'contrast',
    word: 'contrast',
    usIpa: '/ˈkɑnˌtræst/',
    ukIpa: '/ˈkɒntrɑːst/',
    importance: 4,
    topics: ['academic-reading', 'charts-data'],
    ko: '대조하다; 대비',
    zh: '对比；形成反差',
    englishDefinition: 'a clear difference between two things, or the act of comparing them',
    exampleEn: 'The lecturer contrasts public transport in large cities with that in rural towns.',
    exampleKo: '그 강사는 대도시의 대중교통과 농촌 지역의 교통을 대조합니다.',
    exampleZh: '讲者把大城市的公共交通与乡镇地区的交通进行了对比。',
    collocations: ['in contrast', 'contrast sharply', 'contrast two views'],
  }),
  makeEntry({
    id: 'derive',
    word: 'derive',
    usIpa: '/dɪˈraɪv/',
    ukIpa: '/dɪˈraɪv/',
    importance: 4,
    topics: ['academic-reading', 'technology-science'],
    ko: '얻다; 유래하다',
    zh: '获得；源自',
    englishDefinition: 'to obtain something from a source or origin',
    exampleEn: 'The researcher derives the final conclusion from several smaller observations.',
    exampleKo: '그 연구자는 여러 작은 관찰 결과로부터 최종 결론을 도출합니다.',
    exampleZh: '研究者从多个较小的观察结果中得出最终结论。',
    collocations: ['derive from', 'derive meaning', 'derive benefit'],
  }),
  makeEntry({
    id: 'relevant',
    word: 'relevant',
    usIpa: '/ˈreləvənt/',
    ukIpa: '/ˈreləvənt/',
    importance: 5,
    topics: ['academic-reading', 'writing-structure'],
    ko: '관련 있는',
    zh: '相关的',
    englishDefinition: 'closely connected with the subject being discussed',
    exampleEn: 'Only include details that are relevant to the question prompt.',
    exampleKo: '질문 프롬프트와 관련 있는 세부 내용만 포함하세요.',
    exampleZh: '只要加入与题目提示相关的细节。',
    collocations: ['relevant detail', 'relevant evidence', 'highly relevant'],
  }),
  makeEntry({
    id: 'synthesize',
    word: 'synthesize',
    usIpa: '/ˈsɪnθəˌsaɪz/',
    ukIpa: '/ˈsɪnθɪsaɪz/',
    importance: 5,
    topics: ['academic-reading', 'writing-structure'],
    ko: '종합하다',
    zh: '综合',
    englishDefinition: 'to combine separate ideas into a connected whole',
    exampleEn: 'A strong summary should synthesize the main points instead of listing random details.',
    exampleKo: '좋은 요약은 무작위 세부 사항을 나열하기보다 핵심 내용을 종합해야 합니다.',
    exampleZh: '优秀的总结应该综合主要观点，而不是随意罗列细节。',
    collocations: ['synthesize ideas', 'synthesize information', 'synthesize findings'],
  }),
  makeEntry({
    id: 'coherent',
    word: 'coherent',
    usIpa: '/koʊˈhɪrənt/',
    ukIpa: '/kəʊˈhɪərənt/',
    importance: 5,
    topics: ['writing-structure', 'opinion-argument'],
    ko: '일관성 있는; 조리 있는',
    zh: '连贯的；条理清晰的',
    englishDefinition: 'logical, connected, and easy to follow',
    exampleEn: 'Your essay should be coherent from the introduction to the conclusion.',
    exampleKo: '에세이는 도입부터 결론까지 일관성 있게 이어져야 합니다.',
    exampleZh: '你的文章从开头到结尾都应该连贯清晰。',
    collocations: ['coherent argument', 'coherent paragraph', 'coherent response'],
  }),
  makeEntry({
    id: 'concise',
    word: 'concise',
    usIpa: '/kənˈsaɪs/',
    ukIpa: '/kənˈsaɪs/',
    importance: 4,
    topics: ['writing-structure'],
    ko: '간결한',
    zh: '简洁的',
    englishDefinition: 'expressing much in a small number of words',
    exampleEn: 'A concise summary often scores better than a long sentence full of repetition.',
    exampleKo: '반복이 많은 긴 문장보다 간결한 요약이 더 높은 점수를 받는 경우가 많습니다.',
    exampleZh: '与充满重复的长句相比，简洁的总结往往得分更高。',
    collocations: ['concise writing', 'be concise', 'concise summary'],
  }),
  makeEntry({
    id: 'elaborate',
    word: 'elaborate',
    usIpa: '/ɪˈlæbəˌreɪt/',
    ukIpa: '/ɪˈlæbəreɪt/',
    importance: 4,
    topics: ['writing-structure', 'speaking-listening'],
    ko: '자세히 설명하다',
    zh: '详细说明',
    englishDefinition: 'to add more detail in order to explain something better',
    exampleEn: 'When a point is unclear, the speaker may elaborate with a short example.',
    exampleKo: '요점이 불분명할 때 화자는 짧은 예시로 더 자세히 설명할 수 있습니다.',
    exampleZh: '当观点不够清楚时，讲者可能会用简短例子进一步说明。',
    collocations: ['elaborate on', 'elaborate further', 'elaborate explanation'],
  }),
  makeEntry({
    id: 'summarize',
    word: 'summarize',
    usIpa: '/ˈsʌməˌraɪz/',
    ukIpa: '/ˈsʌməraɪz/',
    importance: 5,
    topics: ['writing-structure', 'speaking-listening'],
    ko: '요약하다',
    zh: '总结',
    englishDefinition: 'to state the main points in a short form',
    exampleEn: 'The final sentence should summarize the central message of the passage.',
    exampleKo: '마지막 문장은 지문의 핵심 메시지를 요약해야 합니다.',
    exampleZh: '最后一句应该总结文章的核心信息。',
    collocations: ['summarize briefly', 'summarize the lecture', 'summary sentence'],
  }),
  makeEntry({
    id: 'transition',
    word: 'transition',
    usIpa: '/trænˈzɪʃən/',
    ukIpa: '/trænˈzɪʃən/',
    importance: 4,
    topics: ['writing-structure'],
    ko: '전환; 연결 전개',
    zh: '过渡；衔接',
    englishDefinition: 'a smooth change from one idea or stage to another',
    exampleEn: 'Good transition words help the reader follow the movement between ideas.',
    exampleKo: '좋은 전환 표현은 독자가 생각의 흐름을 따라가도록 도와줍니다.',
    exampleZh: '好的过渡词可以帮助读者跟上观点之间的转换。',
    collocations: ['transition sentence', 'smooth transition', 'transition word'],
  }),
  makeEntry({
    id: 'assignment',
    word: 'assignment',
    usIpa: '/əˈsaɪnmənt/',
    ukIpa: '/əˈsaɪnmənt/',
    importance: 4,
    topics: ['campus-life'],
    ko: '과제',
    zh: '作业',
    englishDefinition: 'a task or piece of work that someone is required to complete',
    exampleEn: 'The assignment must be uploaded before midnight on Friday.',
    exampleKo: '그 과제는 금요일 자정 전에 업로드해야 합니다.',
    exampleZh: '这份作业必须在周五午夜之前上传。',
    collocations: ['group assignment', 'submit the assignment', 'major assignment'],
  }),
  makeEntry({
    id: 'lecture',
    word: 'lecture',
    usIpa: '/ˈlektʃər/',
    ukIpa: '/ˈlektʃə/',
    importance: 5,
    topics: ['campus-life', 'speaking-listening'],
    ko: '강의',
    zh: '讲座；课程',
    englishDefinition: 'a formal talk given to teach a subject',
    exampleEn: 'The lecture focused on how cities respond to climate pressure.',
    exampleKo: '그 강의는 도시가 기후 압력에 어떻게 대응하는지에 초점을 맞추었습니다.',
    exampleZh: '该讲座重点讨论了城市如何应对气候压力。',
    collocations: ['attend a lecture', 'lecture notes', 'lecture hall'],
  }),
  makeEntry({
    id: 'orientation',
    word: 'orientation',
    usIpa: '/ˌɔriənˈteɪʃən/',
    ukIpa: '/ˌɔːrienˈteɪʃən/',
    importance: 3,
    topics: ['campus-life'],
    ko: '오리엔테이션',
    zh: '迎新说明会',
    englishDefinition: 'an introductory session that helps new people understand a place or program',
    exampleEn: 'New students must attend orientation before classes begin.',
    exampleKo: '신입생은 수업이 시작되기 전에 오리엔테이션에 참석해야 합니다.',
    exampleZh: '新生必须在开课前参加迎新说明会。',
    collocations: ['orientation session', 'student orientation', 'orientation day'],
  }),
  makeEntry({
    id: 'scholarship',
    word: 'scholarship',
    usIpa: '/ˈskɑlərˌʃɪp/',
    ukIpa: '/ˈskɒləʃɪp/',
    importance: 4,
    topics: ['campus-life'],
    ko: '장학금',
    zh: '奖学金',
    englishDefinition: 'money awarded to support a student’s education',
    exampleEn: 'She applied for a scholarship to reduce her annual tuition cost.',
    exampleKo: '그녀는 연간 등록금 부담을 줄이기 위해 장학금을 신청했습니다.',
    exampleZh: '她申请奖学金以减轻每年的学费负担。',
    collocations: ['apply for a scholarship', 'full scholarship', 'scholarship fund'],
  }),
  makeEntry({
    id: 'tuition',
    word: 'tuition',
    usIpa: '/tuˈɪʃən/',
    ukIpa: '/tjuˈɪʃən/',
    importance: 4,
    topics: ['campus-life'],
    ko: '등록금',
    zh: '学费',
    englishDefinition: 'the money paid for teaching or instruction at a school or university',
    exampleEn: 'Many students work part-time to help cover tuition fees.',
    exampleKo: '많은 학생들이 등록금을 충당하기 위해 아르바이트를 합니다.',
    exampleZh: '许多学生兼职工作来帮助支付学费。',
    collocations: ['tuition fee', 'pay tuition', 'tuition support'],
  }),
  makeEntry({
    id: 'collaborate',
    word: 'collaborate',
    usIpa: '/kəˈlæbəˌreɪt/',
    ukIpa: '/kəˈlæbəreɪt/',
    importance: 4,
    topics: ['work-professional', 'campus-life'],
    ko: '협업하다',
    zh: '合作',
    englishDefinition: 'to work together with other people on a task or project',
    exampleEn: 'Engineers and designers collaborated on the final product update.',
    exampleKo: '엔지니어와 디자이너가 최종 제품 업데이트를 위해 협업했습니다.',
    exampleZh: '工程师和设计师合作完成了最终的产品更新。',
    collocations: ['collaborate closely', 'collaborate with', 'collaborative project'],
  }),
  makeEntry({
    id: 'negotiate',
    word: 'negotiate',
    usIpa: '/nɪˈɡoʊʃiˌeɪt/',
    ukIpa: '/nɪˈɡəʊʃieɪt/',
    importance: 4,
    topics: ['work-professional', 'opinion-argument'],
    ko: '협상하다',
    zh: '谈判',
    englishDefinition: 'to discuss something in order to reach an agreement',
    exampleEn: 'The team negotiated a later deadline with the client.',
    exampleKo: '그 팀은 고객과 더 늦은 마감일을 협상했습니다.',
    exampleZh: '团队与客户协商了更晚的截止日期。',
    collocations: ['negotiate terms', 'negotiate successfully', 'negotiate a contract'],
  }),
  makeEntry({
    id: 'priority',
    word: 'priority',
    usIpa: '/praɪˈɔrəti/',
    ukIpa: '/praɪˈɒrɪti/',
    importance: 5,
    topics: ['work-professional', 'campus-life'],
    ko: '우선순위',
    zh: '优先事项',
    englishDefinition: 'something that should be treated as more important than other things',
    exampleEn: 'Her first priority was to complete the report before the meeting.',
    exampleKo: '그녀의 첫 번째 우선순위는 회의 전에 보고서를 끝내는 것이었습니다.',
    exampleZh: '她的首要任务是在会议前完成报告。',
    collocations: ['top priority', 'set priorities', 'priority task'],
  }),
  makeEntry({
    id: 'schedule',
    word: 'schedule',
    usIpa: '/ˈskedʒuːl/',
    ukIpa: '/ˈʃedjuːl/',
    importance: 5,
    topics: ['work-professional', 'campus-life'],
    ko: '일정; 일정을 잡다',
    zh: '日程；安排',
    englishDefinition: 'a plan of activities and times, or the act of arranging them',
    exampleEn: 'The manager adjusted the schedule to match the new delivery time.',
    exampleKo: '매니저는 새 배송 시간에 맞춰 일정을 조정했습니다.',
    exampleZh: '经理调整了日程以配合新的送货时间。',
    collocations: ['adjust the schedule', 'tight schedule', 'schedule a meeting'],
  }),
  makeEntry({
    id: 'supervisor',
    word: 'supervisor',
    usIpa: '/ˈsuːpərˌvaɪzər/',
    ukIpa: '/ˈsuːpəvaɪzə/',
    importance: 4,
    topics: ['work-professional'],
    ko: '상사; 감독자',
    zh: '主管；监督人',
    englishDefinition: 'a person who oversees the work of other people',
    exampleEn: 'You should inform your supervisor before changing your shift.',
    exampleKo: '근무 시간을 바꾸기 전에 상사에게 알려야 합니다.',
    exampleZh: '更改班次前，你应该先通知主管。',
    collocations: ['direct supervisor', 'supervisor approval', 'report to a supervisor'],
  }),
  makeEntry({
    id: 'decline',
    word: 'decline',
    usIpa: '/dɪˈklaɪn/',
    ukIpa: '/dɪˈklaɪn/',
    importance: 4,
    topics: ['charts-data', 'opinion-argument'],
    ko: '감소하다; 하락',
    zh: '下降；减少',
    englishDefinition: 'to become smaller or weaker over time',
    exampleEn: 'The chart shows a steady decline in newspaper sales after 2019.',
    exampleKo: '그 그래프는 2019년 이후 신문 판매량이 꾸준히 감소했음을 보여 줍니다.',
    exampleZh: '图表显示，自 2019 年后报纸销量持续下降。',
    collocations: ['sharp decline', 'decline steadily', 'decline in demand'],
  }),
  makeEntry({
    id: 'fluctuate',
    word: 'fluctuate',
    usIpa: '/ˈflʌktʃuˌeɪt/',
    ukIpa: '/ˈflʌktʃueɪt/',
    importance: 4,
    topics: ['charts-data'],
    ko: '변동하다',
    zh: '波动',
    englishDefinition: 'to go up and down irregularly',
    exampleEn: 'Fuel prices often fluctuate due to seasonal demand and supply issues.',
    exampleKo: '연료 가격은 계절 수요와 공급 문제로 인해 자주 변동합니다.',
    exampleZh: '燃料价格常因季节性需求和供应问题而波动。',
    collocations: ['fluctuate widely', 'prices fluctuate', 'fluctuating demand'],
  }),
  makeEntry({
    id: 'peak',
    word: 'peak',
    usIpa: '/piːk/',
    ukIpa: '/piːk/',
    importance: 4,
    topics: ['charts-data'],
    ko: '정점; 최고치에 이르다',
    zh: '峰值；达到顶点',
    englishDefinition: 'the highest point or level, or the act of reaching it',
    exampleEn: 'Online traffic peaked in the final week of the campaign.',
    exampleKo: '온라인 트래픽은 캠페인 마지막 주에 최고치에 도달했습니다.',
    exampleZh: '在线流量在活动最后一周达到峰值。',
    collocations: ['reach a peak', 'peak level', 'peak season'],
  }),
  makeEntry({
    id: 'proportion',
    word: 'proportion',
    usIpa: '/prəˈpɔrʃən/',
    ukIpa: '/prəˈpɔːʃən/',
    importance: 5,
    topics: ['charts-data', 'academic-reading'],
    ko: '비율',
    zh: '比例',
    englishDefinition: 'a part or share of a whole',
    exampleEn: 'A large proportion of respondents said they preferred remote learning.',
    exampleKo: '응답자의 큰 비율이 원격 학습을 선호한다고 말했습니다.',
    exampleZh: '相当大比例的受访者表示他们更喜欢远程学习。',
    collocations: ['large proportion', 'in proportion to', 'proportion of students'],
  }),
  makeEntry({
    id: 'ratio',
    word: 'ratio',
    usIpa: '/ˈreɪʃioʊ/',
    ukIpa: '/ˈreɪʃiəʊ/',
    importance: 4,
    topics: ['charts-data'],
    ko: '비율; 비',
    zh: '比率；比例',
    englishDefinition: 'the relationship in size or number between two things',
    exampleEn: 'The ratio of full-time to part-time staff changed during the year.',
    exampleKo: '정규직과 시간제 직원의 비율이 한 해 동안 변했습니다.',
    exampleZh: '全职员工与兼职员工的比例在这一年中发生了变化。',
    collocations: ['ratio of A to B', 'student-teacher ratio', 'cost ratio'],
  }),
  makeEntry({
    id: 'trend',
    word: 'trend',
    usIpa: '/trend/',
    ukIpa: '/trend/',
    importance: 5,
    topics: ['charts-data', 'technology-science'],
    ko: '추세',
    zh: '趋势',
    englishDefinition: 'a general direction in which something is developing or changing',
    exampleEn: 'The long-term trend suggests more people are choosing online services.',
    exampleKo: '장기적인 추세는 더 많은 사람들이 온라인 서비스를 선택하고 있음을 시사합니다.',
    exampleZh: '长期趋势表明，越来越多人正在选择在线服务。',
    collocations: ['long-term trend', 'current trend', 'trend line'],
  }),
  makeEntry({
    id: 'automate',
    word: 'automate',
    usIpa: '/ˈɔtəˌmeɪt/',
    ukIpa: '/ˈɔːtəmeɪt/',
    importance: 4,
    topics: ['technology-science', 'work-professional'],
    ko: '자동화하다',
    zh: '使自动化',
    englishDefinition: 'to make a process operate by machine or software with little human effort',
    exampleEn: 'The company plans to automate routine customer service tasks.',
    exampleKo: '그 회사는 반복적인 고객 서비스 업무를 자동화할 계획입니다.',
    exampleZh: '公司计划将常规客户服务任务自动化。',
    collocations: ['automate a process', 'fully automated', 'automate tasks'],
  }),
  makeEntry({
    id: 'innovation',
    word: 'innovation',
    usIpa: '/ˌɪnəˈveɪʃən/',
    ukIpa: '/ˌɪnəʊˈveɪʃən/',
    importance: 4,
    topics: ['technology-science'],
    ko: '혁신',
    zh: '创新',
    englishDefinition: 'a new idea, method, or product that improves something',
    exampleEn: 'Innovation in battery design has changed how people use portable devices.',
    exampleKo: '배터리 설계의 혁신은 사람들이 휴대용 기기를 사용하는 방식을 바꾸었습니다.',
    exampleZh: '电池设计方面的创新改变了人们使用便携设备的方式。',
    collocations: ['technological innovation', 'drive innovation', 'innovation strategy'],
  }),
  makeEntry({
    id: 'simulate',
    word: 'simulate',
    usIpa: '/ˈsɪmjəˌleɪt/',
    ukIpa: '/ˈsɪmjʊleɪt/',
    importance: 3,
    topics: ['technology-science'],
    ko: '모의 실험하다; 시뮬레이션하다',
    zh: '模拟',
    englishDefinition: 'to create a model of a real situation for study or practice',
    exampleEn: 'The software can simulate traffic flow under different weather conditions.',
    exampleKo: '그 소프트웨어는 다양한 기상 조건에서의 교통 흐름을 시뮬레이션할 수 있습니다.',
    exampleZh: '该软件可以模拟不同天气条件下的交通流量。',
    collocations: ['simulate conditions', 'simulate a system', 'computer simulation'],
  }),
  makeEntry({
    id: 'virtual',
    word: 'virtual',
    usIpa: '/ˈvɝtʃuəl/',
    ukIpa: '/ˈvɜːtʃuəl/',
    importance: 4,
    topics: ['technology-science', 'campus-life'],
    ko: '가상의; 온라인의',
    zh: '虚拟的；在线的',
    englishDefinition: 'existing in digital form rather than in a physical place',
    exampleEn: 'The seminar switched to a virtual format after the travel advisory changed.',
    exampleKo: '출장 지침이 바뀐 뒤 그 세미나는 온라인 형식으로 전환되었습니다.',
    exampleZh: '在出行建议改变后，研讨会改成了虚拟形式。',
    collocations: ['virtual classroom', 'virtual meeting', 'virtual platform'],
  }),
  makeEntry({
    id: 'device',
    word: 'device',
    usIpa: '/dɪˈvaɪs/',
    ukIpa: '/dɪˈvaɪs/',
    importance: 3,
    topics: ['technology-science'],
    ko: '기기; 장치',
    zh: '设备；装置',
    englishDefinition: 'a tool or piece of equipment designed for a specific purpose',
    exampleEn: 'Students were asked to silence every device before the presentation began.',
    exampleKo: '발표가 시작되기 전에 학생들은 모든 기기의 소리를 꺼 달라는 요청을 받았습니다.',
    exampleZh: '演讲开始前，学生们被要求将所有设备调成静音。',
    collocations: ['mobile device', 'electronic device', 'smart device'],
  }),
  makeEntry({
    id: 'epidemic',
    word: 'epidemic',
    usIpa: '/ˌepəˈdemɪk/',
    ukIpa: '/ˌepɪˈdemɪk/',
    importance: 4,
    topics: ['health-society'],
    ko: '전염병 유행',
    zh: '流行病',
    englishDefinition: 'a rapid spread of disease among many people in one area',
    exampleEn: 'The lecture examined how cities respond during an epidemic.',
    exampleKo: '그 강의는 전염병 유행 기간 동안 도시들이 어떻게 대응하는지 살펴보았습니다.',
    exampleZh: '讲座探讨了城市在流行病期间如何应对。',
    collocations: ['epidemic outbreak', 'during an epidemic', 'prevent an epidemic'],
  }),
  makeEntry({
    id: 'nutrition',
    word: 'nutrition',
    usIpa: '/nuˈtrɪʃən/',
    ukIpa: '/njuˈtrɪʃən/',
    importance: 3,
    topics: ['health-society'],
    ko: '영양',
    zh: '营养',
    englishDefinition: 'the food and substances needed for health and growth',
    exampleEn: 'Good nutrition is linked to stronger concentration and better recovery.',
    exampleKo: '좋은 영양 상태는 더 강한 집중력과 더 나은 회복과 관련이 있습니다.',
    exampleZh: '良好的营养与更强的专注力和更好的恢复有关。',
    collocations: ['proper nutrition', 'nutrition program', 'nutrition advice'],
  }),
  makeEntry({
    id: 'therapy',
    word: 'therapy',
    usIpa: '/ˈθerəpi/',
    ukIpa: '/ˈθerəpi/',
    importance: 3,
    topics: ['health-society'],
    ko: '치료; 요법',
    zh: '治疗；疗法',
    englishDefinition: 'medical or psychological treatment meant to improve health',
    exampleEn: 'The patient continued therapy after leaving the hospital.',
    exampleKo: '그 환자는 병원을 나온 뒤에도 치료를 계속했습니다.',
    exampleZh: '病人在出院后仍继续接受治疗。',
    collocations: ['physical therapy', 'group therapy', 'therapy session'],
  }),
  makeEntry({
    id: 'welfare',
    word: 'welfare',
    usIpa: '/ˈwelfer/',
    ukIpa: '/ˈwelfeə/',
    importance: 3,
    topics: ['health-society', 'environment-policy'],
    ko: '복지; 안녕',
    zh: '福利；福祉',
    englishDefinition: 'health, happiness, and general well-being, especially supported by public systems',
    exampleEn: 'The policy focused on child welfare in low-income neighborhoods.',
    exampleKo: '그 정책은 저소득 지역의 아동 복지에 초점을 맞추었습니다.',
    exampleZh: '该政策重点关注低收入社区的儿童福利。',
    collocations: ['public welfare', 'animal welfare', 'social welfare'],
  }),
  makeEntry({
    id: 'resilience',
    word: 'resilience',
    usIpa: '/rɪˈzɪliəns/',
    ukIpa: '/rɪˈzɪliəns/',
    importance: 4,
    topics: ['health-society', 'opinion-argument'],
    ko: '회복력; 탄력성',
    zh: '韧性；复原力',
    englishDefinition: 'the ability to recover quickly after difficulty or change',
    exampleEn: 'Community resilience improved after the city expanded emergency support.',
    exampleKo: '도시가 긴급 지원을 확대한 뒤 지역사회의 회복력이 향상되었습니다.',
    exampleZh: '在城市扩大紧急支援后，社区的复原力提高了。',
    collocations: ['build resilience', 'emotional resilience', 'community resilience'],
  }),
  makeEntry({
    id: 'conserve',
    word: 'conserve',
    usIpa: '/kənˈsɝv/',
    ukIpa: '/kənˈsɜːv/',
    importance: 4,
    topics: ['environment-policy'],
    ko: '보존하다; 절약하다',
    zh: '保护；节约',
    englishDefinition: 'to protect something or use it carefully so it lasts longer',
    exampleEn: 'The campaign encouraged households to conserve water during the dry season.',
    exampleKo: '그 캠페인은 건기 동안 가정이 물을 절약하도록 장려했습니다.',
    exampleZh: '该活动鼓励家庭在旱季节约用水。',
    collocations: ['conserve energy', 'conserve water', 'conserve resources'],
  }),
  makeEntry({
    id: 'emission',
    word: 'emission',
    usIpa: '/ɪˈmɪʃən/',
    ukIpa: '/ɪˈmɪʃən/',
    importance: 4,
    topics: ['environment-policy', 'technology-science'],
    ko: '배출; 배출물',
    zh: '排放；排放物',
    englishDefinition: 'gas or other material sent out into the air',
    exampleEn: 'The report compared vehicle emissions in urban and suburban areas.',
    exampleKo: '그 보고서는 도심과 교외 지역의 차량 배출량을 비교했습니다.',
    exampleZh: '该报告比较了城市和郊区的车辆排放量。',
    collocations: ['carbon emission', 'reduce emissions', 'emission standard'],
  }),
  makeEntry({
    id: 'policy',
    word: 'policy',
    usIpa: '/ˈpɑləsi/',
    ukIpa: '/ˈpɒlɪsi/',
    importance: 5,
    topics: ['environment-policy', 'work-professional'],
    ko: '정책; 규정',
    zh: '政策；制度',
    englishDefinition: 'an official plan, rule, or principle used to guide decisions',
    exampleEn: 'The school introduced a new policy on late submissions.',
    exampleKo: '그 학교는 지각 제출에 관한 새 정책을 도입했습니다.',
    exampleZh: '学校出台了关于迟交作业的新政策。',
    collocations: ['public policy', 'company policy', 'policy change'],
  }),
  makeEntry({
    id: 'renewable',
    word: 'renewable',
    usIpa: '/rɪˈnuːəbəl/',
    ukIpa: '/rɪˈnjuːəbəl/',
    importance: 3,
    topics: ['environment-policy'],
    ko: '재생 가능한',
    zh: '可再生的',
    englishDefinition: 'able to be replaced naturally and used again',
    exampleEn: 'The article argues that renewable energy will become cheaper over time.',
    exampleKo: '그 기사는 재생 에너지가 시간이 지나며 더 저렴해질 것이라고 주장합니다.',
    exampleZh: '文章认为，可再生能源会随着时间推移变得更便宜。',
    collocations: ['renewable energy', 'renewable source', 'renewable technology'],
  }),
  makeEntry({
    id: 'sustainable',
    word: 'sustainable',
    usIpa: '/səˈsteɪnəbəl/',
    ukIpa: '/səˈsteɪnəbəl/',
    importance: 4,
    topics: ['environment-policy', 'opinion-argument'],
    ko: '지속 가능한',
    zh: '可持续的',
    englishDefinition: 'able to continue for a long time without causing serious harm',
    exampleEn: 'Experts questioned whether the rapid growth was economically sustainable.',
    exampleKo: '전문가들은 그 급속한 성장이 경제적으로 지속 가능한지 의문을 제기했습니다.',
    exampleZh: '专家质疑这种快速增长在经济上是否可持续。',
    collocations: ['sustainable growth', 'sustainable policy', 'sustainable future'],
  }),
  makeEntry({
    id: 'advocate',
    word: 'advocate',
    usIpa: '/ˈædvəkeɪt/',
    ukIpa: '/ˈædvəkət/',
    importance: 4,
    topics: ['opinion-argument', 'environment-policy'],
    ko: '옹호하다; 지지자',
    zh: '提倡；拥护者',
    englishDefinition: 'to publicly support an idea or action',
    exampleEn: 'Several experts advocate stronger rules for online privacy.',
    exampleKo: '여러 전문가가 온라인 개인정보 보호를 위한 더 강한 규칙을 지지합니다.',
    exampleZh: '多位专家主张制定更严格的在线隐私保护规定。',
    collocations: ['advocate change', 'advocate for', 'policy advocate'],
  }),
  makeEntry({
    id: 'controversy',
    word: 'controversy',
    usIpa: '/ˈkɑntrəˌvɝsi/',
    ukIpa: '/ˈkɒntrəvɜːsi/',
    importance: 4,
    topics: ['opinion-argument'],
    ko: '논란',
    zh: '争议',
    englishDefinition: 'a public disagreement with strong opposing views',
    exampleEn: 'The proposal sparked controversy because residents feared higher costs.',
    exampleKo: '주민들이 더 높은 비용을 우려했기 때문에 그 제안은 논란을 불러일으켰습니다.',
    exampleZh: '由于居民担心成本上升，该提案引发了争议。',
    collocations: ['spark controversy', 'public controversy', 'controversial issue'],
  }),
  makeEntry({
    id: 'evidence',
    word: 'evidence',
    usIpa: '/ˈevɪdəns/',
    ukIpa: '/ˈevɪdəns/',
    importance: 5,
    topics: ['opinion-argument', 'academic-reading'],
    ko: '증거; 근거',
    zh: '证据；依据',
    englishDefinition: 'facts or information that support a belief or conclusion',
    exampleEn: 'The writer gives two pieces of evidence to support the main claim.',
    exampleKo: '필자는 핵심 주장을 뒷받침하기 위해 두 가지 근거를 제시합니다.',
    exampleZh: '作者提供了两条证据来支持主要观点。',
    collocations: ['strong evidence', 'supporting evidence', 'evidence suggests'],
  }),
  makeEntry({
    id: 'justify',
    word: 'justify',
    usIpa: '/ˈdʒʌstəˌfaɪ/',
    ukIpa: '/ˈdʒʌstɪfaɪ/',
    importance: 4,
    topics: ['opinion-argument', 'writing-structure'],
    ko: '정당화하다; 근거를 제시하다',
    zh: '证明合理；论证',
    englishDefinition: 'to show that something is reasonable or necessary',
    exampleEn: 'Students must justify their recommendation with clear reasons.',
    exampleKo: '학생들은 명확한 이유로 자신의 추천을 정당화해야 합니다.',
    exampleZh: '学生必须用清晰的理由来论证自己的建议。',
    collocations: ['justify a decision', 'justify the cost', 'justify your answer'],
  }),
  makeEntry({
    id: 'perspective',
    word: 'perspective',
    usIpa: '/pərˈspektɪv/',
    ukIpa: '/pəˈspektɪv/',
    importance: 4,
    topics: ['opinion-argument', 'academic-reading'],
    ko: '관점',
    zh: '观点；视角',
    englishDefinition: 'a particular way of seeing or thinking about something',
    exampleEn: 'The reading presents both a consumer perspective and a government perspective.',
    exampleKo: '그 읽기 지문은 소비자 관점과 정부 관점을 모두 제시합니다.',
    exampleZh: '这篇阅读文章同时呈现了消费者视角和政府视角。',
    collocations: ['different perspectives', 'historical perspective', 'broaden perspective'],
  }),
  makeEntry({
    id: 'assess',
    word: 'assess',
    usIpa: '/əˈses/',
    ukIpa: '/əˈses/',
    importance: 5,
    topics: ['academic-reading', 'work-professional'],
    ko: '평가하다',
    zh: '评估',
    englishDefinition: 'to judge the quality, importance, or value of something',
    exampleEn: 'The committee will assess whether the proposal is realistic.',
    exampleKo: '위원회는 그 제안이 현실적인지 평가할 것입니다.',
    exampleZh: '委员会将评估该提案是否现实可行。',
    collocations: ['assess risk', 'assess performance', 'assess the impact'],
  }),
  makeEntry({
    id: 'evaluate',
    word: 'evaluate',
    usIpa: '/ɪˈvæljəˌweɪt/',
    ukIpa: '/ɪˈvæljueɪt/',
    importance: 4,
    topics: ['academic-reading', 'opinion-argument'],
    ko: '평가하다',
    zh: '评估',
    englishDefinition: 'to examine something carefully and form a judgment about it',
    exampleEn: 'The task asks candidates to evaluate the strengths of each option.',
    exampleKo: '그 과제는 응시자에게 각 선택지의 강점을 평가하라고 요구합니다.',
    exampleZh: '该任务要求考生评估每个选项的优点。',
    collocations: ['evaluate carefully', 'evaluate options', 'evaluate the results'],
  }),
  makeEntry({
    id: 'allocate',
    word: 'allocate',
    usIpa: '/ˈæləˌkeɪt/',
    ukIpa: '/ˈæləkeɪt/',
    importance: 4,
    topics: ['work-professional', 'environment-policy'],
    ko: '할당하다; 배분하다',
    zh: '分配',
    englishDefinition: 'to assign resources, time, or money for a specific purpose',
    exampleEn: 'The department allocated extra funding to language support services.',
    exampleKo: '그 부서는 언어 지원 서비스에 추가 자금을 배분했습니다.',
    exampleZh: '该部门为语言支持服务分配了额外资金。',
    collocations: ['allocate resources', 'allocate funding', 'allocate time'],
  }),
  makeEntry({
    id: 'significant',
    word: 'significant',
    usIpa: '/sɪɡˈnɪfɪkənt/',
    ukIpa: '/sɪɡˈnɪfɪkənt/',
    importance: 5,
    topics: ['academic-reading', 'charts-data'],
    ko: '중요한; 상당한',
    zh: '重要的；显著的',
    englishDefinition: 'large or important enough to have a clear effect',
    exampleEn: 'There was a significant rise in applications after the announcement.',
    exampleKo: '그 발표 이후 지원서 수가 크게 증가했습니다.',
    exampleZh: '公告发布后，申请数量显著上升。',
    collocations: ['significant increase', 'significant result', 'statistically significant'],
  }),
  makeEntry({
    id: 'maintain',
    word: 'maintain',
    usIpa: '/meɪnˈteɪn/',
    ukIpa: '/meɪnˈteɪn/',
    importance: 4,
    topics: ['opinion-argument', 'work-professional'],
    ko: '유지하다; 주장하다',
    zh: '保持；坚持认为',
    englishDefinition: 'to keep something at a certain level, or to continue claiming something',
    exampleEn: 'The author maintains that face-to-face classes still offer unique benefits.',
    exampleKo: '그 필자는 대면 수업이 여전히 고유한 장점을 제공한다고 주장합니다.',
    exampleZh: '作者坚持认为，面对面课堂仍然具有独特优势。',
    collocations: ['maintain quality', 'maintain that', 'maintain control'],
  }),
  makeEntry({
    id: 'interpret',
    word: 'interpret',
    usIpa: '/ɪnˈtɝprət/',
    ukIpa: '/ɪnˈtɜːprɪt/',
    importance: 4,
    topics: ['charts-data', 'academic-reading'],
    ko: '해석하다',
    zh: '解读；解释',
    englishDefinition: 'to explain the meaning of information, behavior, or data',
    exampleEn: 'Candidates must interpret the graph before describing the main trend.',
    exampleKo: '응시자는 핵심 추세를 설명하기 전에 그래프를 해석해야 합니다.',
    exampleZh: '考生必须先解读图表，再描述主要趋势。',
    collocations: ['interpret data', 'interpret the chart', 'interpret meaning'],
  }),
  makeEntry({
    id: 'outcome',
    word: 'outcome',
    usIpa: '/ˈaʊtˌkʌm/',
    ukIpa: '/ˈaʊtkʌm/',
    importance: 4,
    topics: ['work-professional', 'health-society'],
    ko: '결과',
    zh: '结果',
    englishDefinition: 'the final result of an action, process, or event',
    exampleEn: 'Better planning often leads to a more stable outcome.',
    exampleKo: '더 나은 계획은 종종 더 안정적인 결과로 이어집니다.',
    exampleZh: '更好的规划通常会带来更稳定的结果。',
    collocations: ['positive outcome', 'final outcome', 'desired outcome'],
  }),
  makeEntry({
    id: 'precise',
    word: 'precise',
    usIpa: '/prɪˈsaɪs/',
    ukIpa: '/prɪˈsaɪs/',
    importance: 4,
    topics: ['writing-structure', 'charts-data'],
    ko: '정확한; 정밀한',
    zh: '精确的',
    englishDefinition: 'very exact and accurate',
    exampleEn: 'Use precise language when describing percentages and time changes.',
    exampleKo: '백분율과 시간 변화를 설명할 때는 정확한 표현을 사용하세요.',
    exampleZh: '描述百分比和时间变化时要使用精确的语言。',
    collocations: ['precise wording', 'precise figure', 'precise description'],
  }),
  makeEntry({
    id: 'regulate',
    word: 'regulate',
    usIpa: '/ˈreɡjəˌleɪt/',
    ukIpa: '/ˈreɡjʊleɪt/',
    importance: 4,
    topics: ['environment-policy', 'health-society'],
    ko: '규제하다; 조절하다',
    zh: '监管；调节',
    englishDefinition: 'to control something through rules or to keep it at the right level',
    exampleEn: 'The government wants to regulate online advertising to children.',
    exampleKo: '정부는 아동 대상 온라인 광고를 규제하려고 합니다.',
    exampleZh: '政府希望对面向儿童的在线广告进行监管。',
    collocations: ['regulate the market', 'strictly regulate', 'regulate emissions'],
  }),
  makeEntry({
    id: 'strategy',
    word: 'strategy',
    usIpa: '/ˈstrætədʒi/',
    ukIpa: '/ˈstrætədʒi/',
    importance: 4,
    topics: ['work-professional', 'opinion-argument'],
    ko: '전략',
    zh: '策略',
    englishDefinition: 'a plan designed to achieve a particular goal',
    exampleEn: 'The speaker outlined a strategy for improving student participation.',
    exampleKo: '그 화자는 학생 참여를 높이기 위한 전략을 설명했습니다.',
    exampleZh: '讲者概述了一项提高学生参与度的策略。',
    collocations: ['effective strategy', 'long-term strategy', 'communication strategy'],
  }),
  makeEntry({
    id: 'vary',
    word: 'vary',
    usIpa: '/ˈveri/',
    ukIpa: '/ˈveəri/',
    importance: 4,
    topics: ['charts-data', 'academic-reading'],
    ko: '다르다; 변하다',
    zh: '变化；不同',
    englishDefinition: 'to change or to be different from one case to another',
    exampleEn: 'Results vary depending on age, location, and previous experience.',
    exampleKo: '결과는 나이, 지역, 이전 경험에 따라 달라집니다.',
    exampleZh: '结果会因年龄、地点和过往经验而有所不同。',
    collocations: ['vary widely', 'vary by region', 'results vary'],
  }),
  makeEntry({
    id: 'mitigate',
    word: 'mitigate',
    usIpa: '/ˈmɪtɪɡeɪt/',
    ukIpa: '/ˈmɪtɪɡeɪt/',
    importance: 4,
    topics: ['environment-policy', 'opinion-argument'],
    ko: '완화하다; 경감하다',
    zh: '缓解；减轻',
    englishDefinition: 'to make something harmful or serious less severe',
    exampleEn: 'Planting trees can help mitigate the effects of climate change.',
    exampleKo: '나무를 심으면 기후 변화의 영향을 완화하는 데 도움이 됩니다.',
    exampleZh: '植树有助于减轻气候变化的影响。',
    collocations: ['mitigate risk', 'mitigate the impact', 'mitigate damage'],
  }),
  makeEntry({
    id: 'substantial',
    word: 'substantial',
    usIpa: '/səbˈstænʃəl/',
    ukIpa: '/səbˈstænʃəl/',
    importance: 4,
    topics: ['charts-data', 'academic-reading'],
    ko: '상당한; 실질적인',
    zh: '大量的；实质的',
    englishDefinition: 'large in amount, size, or importance',
    exampleEn: 'The study found a substantial increase in online learning.',
    exampleKo: '그 연구는 온라인 학습의 상당한 증가를 발견했습니다.',
    exampleZh: '研究发现在线学习大幅增加。',
    collocations: ['substantial increase', 'substantial evidence', 'a substantial amount'],
  }),
  makeEntry({
    id: 'hypothesis',
    word: 'hypothesis',
    usIpa: '/haɪˈpɑːθəsɪs/',
    ukIpa: '/haɪˈpɒθəsɪs/',
    importance: 4,
    topics: ['academic-reading', 'technology-science'],
    ko: '가설',
    zh: '假设',
    englishDefinition: 'an idea suggested as an explanation that has not yet been proven',
    exampleEn: 'Researchers tested the hypothesis with a controlled experiment.',
    exampleKo: '연구자들은 통제된 실험으로 그 가설을 검증했습니다.',
    exampleZh: '研究人员通过对照实验检验了这一假设。',
    collocations: ['test a hypothesis', 'support the hypothesis', 'form a hypothesis'],
  }),
  makeEntry({
    id: 'deteriorate',
    word: 'deteriorate',
    usIpa: '/dɪˈtɪriəreɪt/',
    ukIpa: '/dɪˈtɪəriəreɪt/',
    importance: 4,
    topics: ['health-society', 'environment-policy'],
    ko: '악화되다; 나빠지다',
    zh: '恶化；变坏',
    englishDefinition: 'to become progressively worse over time',
    exampleEn: 'Air quality can deteriorate rapidly during wildfire season.',
    exampleKo: '산불 시즌에는 공기 질이 빠르게 악화될 수 있습니다.',
    exampleZh: '在野火季节，空气质量会迅速恶化。',
    collocations: ['deteriorate rapidly', 'conditions deteriorate', 'deteriorate over time'],
  }),
  makeEntry({
    id: 'comprehensive',
    word: 'comprehensive',
    usIpa: '/ˌkɑːmprɪˈhensɪv/',
    ukIpa: '/ˌkɒmprɪˈhensɪv/',
    importance: 4,
    topics: ['academic-reading', 'writing-structure'],
    ko: '포괄적인; 종합적인',
    zh: '全面的；综合的',
    englishDefinition: 'complete and including everything that is necessary',
    exampleEn: 'The report offers a comprehensive overview of the findings.',
    exampleKo: '그 보고서는 연구 결과에 대한 포괄적인 개요를 제공합니다.',
    exampleZh: '这份报告提供了研究结果的全面概述。',
    collocations: ['comprehensive review', 'comprehensive overview', 'comprehensive analysis'],
  }),
  makeEntry({
    id: 'paradigm',
    word: 'paradigm',
    usIpa: '/ˈpærədaɪm/',
    ukIpa: '/ˈpærədaɪm/',
    importance: 3,
    topics: ['academic-reading', 'technology-science'],
    ko: '패러다임; 전형적 틀',
    zh: '范式；典范',
    englishDefinition: 'a typical model or pattern for how something works',
    exampleEn: 'Remote work has created a new paradigm for many companies.',
    exampleKo: '원격 근무는 많은 기업에 새로운 패러다임을 만들었습니다.',
    exampleZh: '远程办公为许多公司创造了新的范式。',
    collocations: ['a new paradigm', 'paradigm shift', 'dominant paradigm'],
  }),
  makeEntry({
    id: 'empirical',
    word: 'empirical',
    usIpa: '/ɪmˈpɪrɪkəl/',
    ukIpa: '/ɪmˈpɪrɪkəl/',
    importance: 3,
    topics: ['academic-reading', 'opinion-argument'],
    ko: '경험적인; 실증적인',
    zh: '经验的；实证的',
    englishDefinition: 'based on observation or experiment rather than theory alone',
    exampleEn: 'The claim is supported by strong empirical evidence.',
    exampleKo: '그 주장은 강력한 실증적 증거로 뒷받침됩니다.',
    exampleZh: '这一说法有强有力的实证证据支持。',
    collocations: ['empirical evidence', 'empirical data', 'empirical study'],
  }),
  makeEntry({
    id: 'facilitate',
    word: 'facilitate',
    usIpa: '/fəˈsɪlɪteɪt/',
    ukIpa: '/fəˈsɪlɪteɪt/',
    importance: 4,
    topics: ['work-professional', 'technology-science'],
    ko: '용이하게 하다; 촉진하다',
    zh: '促进；使便利',
    englishDefinition: 'to make an action or process easier',
    exampleEn: 'The new platform facilitates communication between teams.',
    exampleKo: '새 플랫폼은 팀 간의 소통을 용이하게 합니다.',
    exampleZh: '新平台促进了团队之间的沟通。',
    collocations: ['facilitate communication', 'facilitate the process', 'facilitate learning'],
  }),
  makeEntry({
    id: 'prevalent',
    word: 'prevalent',
    usIpa: '/ˈprevələnt/',
    ukIpa: '/ˈprevələnt/',
    importance: 3,
    topics: ['health-society', 'charts-data'],
    ko: '만연한; 널리 퍼진',
    zh: '普遍的；流行的',
    englishDefinition: 'common or widespread in a particular place or time',
    exampleEn: 'Smartphone use is highly prevalent among teenagers.',
    exampleKo: '스마트폰 사용은 청소년들 사이에서 매우 만연합니다.',
    exampleZh: '智能手机的使用在青少年中非常普遍。',
    collocations: ['highly prevalent', 'become prevalent', 'prevalent among'],
  }),
  makeEntry({
    id: 'ambiguous',
    word: 'ambiguous',
    usIpa: '/æmˈbɪɡjuəs/',
    ukIpa: '/æmˈbɪɡjuəs/',
    importance: 3,
    topics: ['writing-structure', 'opinion-argument'],
    ko: '모호한; 애매한',
    zh: '模糊的；含糊的',
    englishDefinition: 'having more than one possible meaning; unclear',
    exampleEn: 'The instructions were ambiguous, so students interpreted them differently.',
    exampleKo: '지시사항이 모호해서 학생들이 서로 다르게 해석했습니다.',
    exampleZh: '说明含糊不清，因此学生们有不同的理解。',
    collocations: ['ambiguous meaning', 'remain ambiguous', 'an ambiguous statement'],
  }),
  makeEntry({
    id: 'correlation',
    word: 'correlation',
    usIpa: '/ˌkɔːrəˈleɪʃən/',
    ukIpa: '/ˌkɒrəˈleɪʃən/',
    importance: 4,
    topics: ['charts-data', 'academic-reading'],
    ko: '상관관계',
    zh: '相关性；关联',
    englishDefinition: 'a connection between two things in which they change together',
    exampleEn: 'There is a clear correlation between sleep and academic performance.',
    exampleKo: '수면과 학업 성취 사이에는 명확한 상관관계가 있습니다.',
    exampleZh: '睡眠与学业表现之间存在明显的相关性。',
    collocations: ['strong correlation', 'positive correlation', 'a clear correlation'],
  }),
  makeEntry({
    id: 'undermine',
    word: 'undermine',
    usIpa: '/ˌʌndərˈmaɪn/',
    ukIpa: '/ˌʌndəˈmaɪn/',
    importance: 3,
    topics: ['opinion-argument', 'work-professional'],
    ko: '약화시키다; 훼손하다',
    zh: '削弱；破坏',
    englishDefinition: 'to gradually weaken something such as confidence or authority',
    exampleEn: 'Constant criticism can undermine the confidence of students.',
    exampleKo: '끊임없는 비판은 학생들의 자신감을 약화시킬 수 있습니다.',
    exampleZh: '不断的批评会削弱学生的自信心。',
    collocations: ['undermine confidence', 'undermine authority', 'undermine trust'],
  }),
  makeEntry({
    id: 'compelling',
    word: 'compelling',
    usIpa: '/kəmˈpelɪŋ/',
    ukIpa: '/kəmˈpelɪŋ/',
    importance: 4,
    topics: ['opinion-argument', 'writing-structure'],
    ko: '설득력 있는; 강렬한',
    zh: '令人信服的；引人入胜的',
    englishDefinition: 'convincing and able to hold your attention',
    exampleEn: 'She made a compelling argument for extending the deadline.',
    exampleKo: '그녀는 마감일 연장에 대해 설득력 있는 주장을 펼쳤습니다.',
    exampleZh: '她提出了延长截止日期的有力论据。',
    collocations: ['a compelling argument', 'compelling evidence', 'compelling reason'],
  }),
  makeEntry({
    id: 'robust',
    word: 'robust',
    usIpa: '/roʊˈbʌst/',
    ukIpa: '/rəˈbʌst/',
    importance: 3,
    topics: ['technology-science', 'charts-data'],
    ko: '견고한; 탄탄한',
    zh: '强健的；稳健的',
    englishDefinition: 'strong and able to perform well in difficult conditions',
    exampleEn: 'The system needs a robust design to handle heavy traffic.',
    exampleKo: '그 시스템은 대규모 트래픽을 처리할 견고한 설계가 필요합니다.',
    exampleZh: '该系统需要稳健的设计来应对大流量。',
    collocations: ['robust system', 'robust growth', 'a robust design'],
  }),
]

export const PTE_VOCABULARY = [...PTE_VOCABULARY_BASE]
