#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Property Tests for Trace ID Middleware
Feature: error-tracking
"""

import uuid
import pytest
from hypothesis import given, strategies as st, settings, HealthCheck
from flask import Flask

from src.common.trace_middleware import setup_trace_middleware


# Test fixtures
@pytest.fixture
def app():
    """Create Flask app with trace middleware"""
    app = Flask(__name__)
    app.config['TESTING'] = True
    setup_trace_middleware(app)
    
    # Add test route
    @app.route('/test')
    def test_route():
        from flask import g
        return {'trace_id': getattr(g, 'trace_id', 'NO_TRACE')}
    
    return app


@pytest.fixture
def client(app):
    """Create test client"""
    return app.test_client()


# Helper strategies
valid_uuid_strategy = st.builds(lambda: str(uuid.uuid4()))
invalid_uuid_strategy = st.text(min_size=1, max_size=50).filter(
    lambda x: not _is_valid_uuid(x) and '\n' not in x and '\r' not in x
)


def _is_valid_uuid(value: str) -> bool:
    """Check if string is valid UUID"""
    try:
        uuid.UUID(value)
        return True
    except (ValueError, AttributeError):
        return False


# Property 1: Trace ID Generation and Preservation
@settings(max_examples=100, suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(
    has_header=st.booleans(),
    trace_id=st.one_of(valid_uuid_strategy, invalid_uuid_strategy, st.none())
)
def test_property_trace_id_generation_and_preservation(client, has_header, trace_id):
    """
    Property 1: Trace ID Generation and Preservation
    Validates: Requirements 1.1, 1.2, 1.3
    
    For any request:
    - If no x-trace-id header provided, a valid UUID v4 should be generated
    - If valid x-trace-id header provided, that trace ID should be preserved
    - If invalid x-trace-id header provided, a new valid UUID v4 should be generated
    """
    headers = {}
    if has_header and trace_id is not None:
        headers['x-trace-id'] = trace_id
    
    response = client.get('/test', headers=headers)
    
    # Response should always be successful
    assert response.status_code == 200
    
    # Extract trace_id from response
    data = response.get_json()
    response_trace_id = data['trace_id']
    
    # Verify trace_id is valid UUID format
    assert _is_valid_uuid(response_trace_id), f"Response trace_id '{response_trace_id}' is not a valid UUID"
    
    # Check preservation logic
    if has_header and trace_id is not None and _is_valid_uuid(trace_id):
        # Valid trace_id provided, should be preserved
        assert response_trace_id == trace_id, "Valid trace_id should be preserved"
    else:
        # No header or invalid trace_id, should generate new one
        assert response_trace_id != trace_id if trace_id else True, "New trace_id should be generated"


# Property 2: Trace ID Response Header Propagation
@settings(max_examples=100, suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(
    path=st.sampled_from(['/test', '/test?param=value']),
    method=st.sampled_from(['GET', 'POST', 'PUT', 'DELETE'])
)
def test_property_trace_id_response_header(client, path, method):
    """
    Property 2: Trace ID Response Header Propagation
    Validates: Requirements 1.4
    
    For any request, the x-trace-id header should be present in the response
    and contain a valid UUID.
    """
    # Make request with specified method
    if method == 'GET':
        response = client.get(path)
    elif method == 'POST':
        response = client.post(path)
    elif method == 'PUT':
        response = client.put(path)
    else:  # DELETE
        response = client.delete(path)
    
    # Check x-trace-id header exists
    assert 'x-trace-id' in response.headers, "x-trace-id header should be present in response"
    
    # Extract and validate trace_id
    trace_id = response.headers['x-trace-id']
    assert _is_valid_uuid(trace_id) or trace_id in ['NO_TRACE', 'ERROR_TRACE'], \
        f"Response header trace_id '{trace_id}' should be valid UUID or fallback value"


# Unit test: Missing trace ID fallback
def test_missing_trace_id_fallback(app):
    """
    Test that when trace_id is not in flask.g, the system handles it gracefully
    """
    with app.test_client() as client:
        # Create route that doesn't access g.trace_id
        @app.route('/no-trace')
        def no_trace_route():
            return {'status': 'ok'}
        
        response = client.get('/no-trace')
        
        # Should still have x-trace-id header
        assert 'x-trace-id' in response.headers
        trace_id = response.headers['x-trace-id']
        
        # Should be valid UUID (generated by middleware)
        assert _is_valid_uuid(trace_id) or trace_id in ['NO_TRACE', 'ERROR_TRACE']


# Unit test: UUID format validation
def test_uuid_format_validation(client):
    """
    Test that invalid UUID formats are rejected and new ones generated
    """
    invalid_uuids = [
        'not-a-uuid',
        '12345',
        'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        '',
        'null',
    ]
    
    for invalid_uuid in invalid_uuids:
        response = client.get('/test', headers={'x-trace-id': invalid_uuid})
        data = response.get_json()
        response_trace_id = data['trace_id']
        
        # Should generate new valid UUID, not use invalid one
        assert _is_valid_uuid(response_trace_id)
        assert response_trace_id != invalid_uuid


# Unit test: Valid UUID preservation
def test_valid_uuid_preservation(client):
    """
    Test that valid UUIDs are preserved exactly
    """
    test_uuid = str(uuid.uuid4())
    
    response = client.get('/test', headers={'x-trace-id': test_uuid})
    data = response.get_json()
    response_trace_id = data['trace_id']
    
    # Should preserve exact UUID
    assert response_trace_id == test_uuid
    
    # Response header should also match
    assert response.headers['x-trace-id'] == test_uuid
