/**
 * Domain Glossaries
 * 도메인별 전문 용어 사전
 * 
 * 구조: { domain: { sourceLang_targetLang: { term: translation } } }
 */

// IT / Tech 용어
export const IT_GLOSSARY = {
  // English to Korean
  en_ko: {
    'API': 'API',
    'backend': '백엔드',
    'frontend': '프론트엔드',
    'database': '데이터베이스',
    'server': '서버',
    'client': '클라이언트',
    'deploy': '배포',
    'deployment': '배포',
    'repository': '저장소',
    'branch': '브랜치',
    'merge': '병합',
    'commit': '커밋',
    'push': '푸시',
    'pull': '풀',
    'pull request': '풀 리퀘스트',
    'code review': '코드 리뷰',
    'bug': '버그',
    'debug': '디버그',
    'debugging': '디버깅',
    'framework': '프레임워크',
    'library': '라이브러리',
    'module': '모듈',
    'component': '컴포넌트',
    'function': '함수',
    'variable': '변수',
    'constant': '상수',
    'class': '클래스',
    'object': '객체',
    'instance': '인스턴스',
    'method': '메서드',
    'property': '속성',
    'interface': '인터페이스',
    'abstract': '추상',
    'inheritance': '상속',
    'polymorphism': '다형성',
    'encapsulation': '캡슐화',
    'refactoring': '리팩토링',
    'algorithm': '알고리즘',
    'data structure': '자료구조',
    'array': '배열',
    'list': '리스트',
    'stack': '스택',
    'queue': '큐',
    'tree': '트리',
    'graph': '그래프',
    'hash': '해시',
    'cache': '캐시',
    'caching': '캐싱',
    'authentication': '인증',
    'authorization': '권한 부여',
    'token': '토큰',
    'session': '세션',
    'cookie': '쿠키',
    'encryption': '암호화',
    'decryption': '복호화',
    'SSL': 'SSL',
    'HTTPS': 'HTTPS',
    'REST': 'REST',
    'GraphQL': 'GraphQL',
    'microservice': '마이크로서비스',
    'container': '컨테이너',
    'Docker': '도커',
    'Kubernetes': '쿠버네티스',
    'CI/CD': 'CI/CD',
    'DevOps': '데브옵스',
    'agile': '애자일',
    'scrum': '스크럼',
    'sprint': '스프린트',
    'backlog': '백로그',
    'user story': '사용자 스토리',
    'endpoint': '엔드포인트',
    'payload': '페이로드',
    'request': '요청',
    'response': '응답',
    'status code': '상태 코드',
    'middleware': '미들웨어',
    'routing': '라우팅',
    'state management': '상태 관리',
    'hook': '훅',
    'callback': '콜백',
    'promise': '프로미스',
    'async': '비동기',
    'sync': '동기',
    'thread': '스레드',
    'process': '프로세스',
    'memory': '메모리',
    'CPU': 'CPU',
    'GPU': 'GPU',
    'cloud': '클라우드',
    'AWS': 'AWS',
    'Azure': '애저',
    'GCP': 'GCP',
    'serverless': '서버리스',
    'lambda': '람다',
    'machine learning': '머신러닝',
    'deep learning': '딥러닝',
    'neural network': '신경망',
    'AI': 'AI',
    'artificial intelligence': '인공지능',
    'model': '모델',
    'training': '학습',
    'inference': '추론',
    'dataset': '데이터셋',
    'feature': '피처',
    'label': '레이블',
    'regression': '회귀',
    'classification': '분류',
    'clustering': '클러스터링',
  },
  // Korean to English
  ko_en: {
    '백엔드': 'backend',
    '프론트엔드': 'frontend',
    '데이터베이스': 'database',
    '서버': 'server',
    '클라이언트': 'client',
    '배포': 'deployment',
    '저장소': 'repository',
    '브랜치': 'branch',
    '병합': 'merge',
    '커밋': 'commit',
    '버그': 'bug',
    '디버그': 'debug',
    '디버깅': 'debugging',
    '프레임워크': 'framework',
    '라이브러리': 'library',
    '모듈': 'module',
    '컴포넌트': 'component',
    '함수': 'function',
    '변수': 'variable',
    '상수': 'constant',
    '클래스': 'class',
    '객체': 'object',
    '인스턴스': 'instance',
    '메서드': 'method',
    '속성': 'property',
    '인터페이스': 'interface',
    '상속': 'inheritance',
    '다형성': 'polymorphism',
    '캡슐화': 'encapsulation',
    '리팩토링': 'refactoring',
    '알고리즘': 'algorithm',
    '자료구조': 'data structure',
    '배열': 'array',
    '리스트': 'list',
    '스택': 'stack',
    '큐': 'queue',
    '트리': 'tree',
    '그래프': 'graph',
    '해시': 'hash',
    '캐시': 'cache',
    '캐싱': 'caching',
    '인증': 'authentication',
    '권한 부여': 'authorization',
    '토큰': 'token',
    '세션': 'session',
    '쿠키': 'cookie',
    '암호화': 'encryption',
    '복호화': 'decryption',
    '마이크로서비스': 'microservice',
    '컨테이너': 'container',
    '도커': 'Docker',
    '쿠버네티스': 'Kubernetes',
    '데브옵스': 'DevOps',
    '애자일': 'agile',
    '스크럼': 'scrum',
    '스프린트': 'sprint',
    '백로그': 'backlog',
    '엔드포인트': 'endpoint',
    '페이로드': 'payload',
    '요청': 'request',
    '응답': 'response',
    '미들웨어': 'middleware',
    '라우팅': 'routing',
    '상태 관리': 'state management',
    '훅': 'hook',
    '콜백': 'callback',
    '프로미스': 'promise',
    '비동기': 'async',
    '동기': 'sync',
    '스레드': 'thread',
    '프로세스': 'process',
    '메모리': 'memory',
    '클라우드': 'cloud',
    '서버리스': 'serverless',
    '람다': 'lambda',
    '머신러닝': 'machine learning',
    '딥러닝': 'deep learning',
    '신경망': 'neural network',
    '인공지능': 'artificial intelligence',
    '학습': 'training',
    '추론': 'inference',
    '데이터셋': 'dataset',
    '피처': 'feature',
    '레이블': 'label',
    '회귀': 'regression',
    '분류': 'classification',
    '클러스터링': 'clustering',
  },
}


// Medical 용어
export const MEDICAL_GLOSSARY = {
  en_ko: {
    'diagnosis': '진단',
    'symptom': '증상',
    'treatment': '치료',
    'prescription': '처방',
    'medication': '약물',
    'surgery': '수술',
    'patient': '환자',
    'doctor': '의사',
    'nurse': '간호사',
    'hospital': '병원',
    'clinic': '클리닉',
    'emergency': '응급',
    'chronic': '만성',
    'acute': '급성',
    'infection': '감염',
    'inflammation': '염증',
    'allergy': '알레르기',
    'vaccine': '백신',
    'antibiotics': '항생제',
    'blood pressure': '혈압',
    'heart rate': '심박수',
    'temperature': '체온',
    'X-ray': '엑스레이',
    'MRI': 'MRI',
    'CT scan': 'CT 스캔',
    'ultrasound': '초음파',
    'biopsy': '생검',
    'cancer': '암',
    'tumor': '종양',
    'diabetes': '당뇨병',
    'hypertension': '고혈압',
    'stroke': '뇌졸중',
    'heart attack': '심장마비',
    'anesthesia': '마취',
    'ICU': '중환자실',
    'outpatient': '외래 환자',
    'inpatient': '입원 환자',
  },
  ko_en: {
    '진단': 'diagnosis',
    '증상': 'symptom',
    '치료': 'treatment',
    '처방': 'prescription',
    '약물': 'medication',
    '수술': 'surgery',
    '환자': 'patient',
    '의사': 'doctor',
    '간호사': 'nurse',
    '병원': 'hospital',
    '응급': 'emergency',
    '만성': 'chronic',
    '급성': 'acute',
    '감염': 'infection',
    '염증': 'inflammation',
    '알레르기': 'allergy',
    '백신': 'vaccine',
    '항생제': 'antibiotics',
    '혈압': 'blood pressure',
    '심박수': 'heart rate',
    '체온': 'temperature',
    '초음파': 'ultrasound',
    '생검': 'biopsy',
    '암': 'cancer',
    '종양': 'tumor',
    '당뇨병': 'diabetes',
    '고혈압': 'hypertension',
    '뇌졸중': 'stroke',
    '심장마비': 'heart attack',
    '마취': 'anesthesia',
    '중환자실': 'ICU',
    '외래 환자': 'outpatient',
    '입원 환자': 'inpatient',
  },
}

// Legal 용어
export const LEGAL_GLOSSARY = {
  en_ko: {
    'contract': '계약',
    'agreement': '합의',
    'clause': '조항',
    'liability': '책임',
    'warranty': '보증',
    'indemnity': '배상',
    'plaintiff': '원고',
    'defendant': '피고',
    'lawsuit': '소송',
    'verdict': '판결',
    'appeal': '항소',
    'jurisdiction': '관할권',
    'arbitration': '중재',
    'mediation': '조정',
    'settlement': '합의',
    'damages': '손해배상',
    'breach': '위반',
    'termination': '해지',
    'confidentiality': '기밀유지',
    'non-disclosure': '비공개',
    'intellectual property': '지적재산권',
    'patent': '특허',
    'trademark': '상표',
    'copyright': '저작권',
    'license': '라이선스',
    'compliance': '준수',
    'regulation': '규정',
    'statute': '법령',
    'amendment': '수정',
    'notarization': '공증',
  },
  ko_en: {
    '계약': 'contract',
    '합의': 'agreement',
    '조항': 'clause',
    '책임': 'liability',
    '보증': 'warranty',
    '배상': 'indemnity',
    '원고': 'plaintiff',
    '피고': 'defendant',
    '소송': 'lawsuit',
    '판결': 'verdict',
    '항소': 'appeal',
    '관할권': 'jurisdiction',
    '중재': 'arbitration',
    '조정': 'mediation',
    '손해배상': 'damages',
    '위반': 'breach',
    '해지': 'termination',
    '기밀유지': 'confidentiality',
    '지적재산권': 'intellectual property',
    '특허': 'patent',
    '상표': 'trademark',
    '저작권': 'copyright',
    '라이선스': 'license',
    '준수': 'compliance',
    '규정': 'regulation',
    '법령': 'statute',
    '수정': 'amendment',
    '공증': 'notarization',
  },
}

// Business 용어
export const BUSINESS_GLOSSARY = {
  en_ko: {
    'revenue': '매출',
    'profit': '이익',
    'loss': '손실',
    'budget': '예산',
    'forecast': '예측',
    'ROI': 'ROI',
    'KPI': 'KPI',
    'stakeholder': '이해관계자',
    'shareholder': '주주',
    'investor': '투자자',
    'acquisition': '인수',
    'merger': '합병',
    'IPO': 'IPO',
    'valuation': '가치평가',
    'equity': '자본',
    'debt': '부채',
    'asset': '자산',
    'liability': '부채',
    'balance sheet': '대차대조표',
    'income statement': '손익계산서',
    'cash flow': '현금흐름',
    'quarterly': '분기별',
    'annual': '연간',
    'fiscal year': '회계연도',
    'market share': '시장점유율',
    'competitive advantage': '경쟁우위',
    'strategy': '전략',
    'execution': '실행',
    'milestone': '마일스톤',
    'deliverable': '산출물',
    'scalability': '확장성',
    'sustainability': '지속가능성',
  },
  ko_en: {
    '매출': 'revenue',
    '이익': 'profit',
    '손실': 'loss',
    '예산': 'budget',
    '예측': 'forecast',
    '이해관계자': 'stakeholder',
    '주주': 'shareholder',
    '투자자': 'investor',
    '인수': 'acquisition',
    '합병': 'merger',
    '가치평가': 'valuation',
    '자본': 'equity',
    '부채': 'debt',
    '자산': 'asset',
    '대차대조표': 'balance sheet',
    '손익계산서': 'income statement',
    '현금흐름': 'cash flow',
    '분기별': 'quarterly',
    '연간': 'annual',
    '회계연도': 'fiscal year',
    '시장점유율': 'market share',
    '경쟁우위': 'competitive advantage',
    '전략': 'strategy',
    '실행': 'execution',
    '마일스톤': 'milestone',
    '산출물': 'deliverable',
    '확장성': 'scalability',
    '지속가능성': 'sustainability',
  },
}

// Academic 용어
export const ACADEMIC_GLOSSARY = {
  en_ko: {
    'thesis': '논문',
    'dissertation': '학위논문',
    'abstract': '초록',
    'hypothesis': '가설',
    'methodology': '방법론',
    'literature review': '문헌검토',
    'citation': '인용',
    'reference': '참고문헌',
    'peer review': '동료평가',
    'publication': '출판',
    'journal': '학술지',
    'conference': '학회',
    'research': '연구',
    'experiment': '실험',
    'analysis': '분석',
    'conclusion': '결론',
    'findings': '연구결과',
    'sample': '표본',
    'variable': '변수',
    'correlation': '상관관계',
    'significance': '유의성',
    'qualitative': '정성적',
    'quantitative': '정량적',
    'empirical': '실증적',
    'theoretical': '이론적',
  },
  ko_en: {
    '논문': 'thesis',
    '학위논문': 'dissertation',
    '초록': 'abstract',
    '가설': 'hypothesis',
    '방법론': 'methodology',
    '문헌검토': 'literature review',
    '인용': 'citation',
    '참고문헌': 'reference',
    '동료평가': 'peer review',
    '출판': 'publication',
    '학술지': 'journal',
    '학회': 'conference',
    '연구': 'research',
    '실험': 'experiment',
    '분석': 'analysis',
    '결론': 'conclusion',
    '연구결과': 'findings',
    '표본': 'sample',
    '변수': 'variable',
    '상관관계': 'correlation',
    '유의성': 'significance',
    '정성적': 'qualitative',
    '정량적': 'quantitative',
    '실증적': 'empirical',
    '이론적': 'theoretical',
  },
}

// 도메인별 glossary 매핑
export const GLOSSARIES = {
  general: {},
  it: IT_GLOSSARY,
  medical: MEDICAL_GLOSSARY,
  legal: LEGAL_GLOSSARY,
  business: BUSINESS_GLOSSARY,
  academic: ACADEMIC_GLOSSARY,
}
